'use strict';
const defaultSupplyOrder=['vial','water','pen','cartridge'];
function supplyOrder(){return [...new Set([...(Array.isArray(S.settings.supplyOrder)?S.settings.supplyOrder:[]),...defaultSupplyOrder])].filter(k=>defaultSupplyOrder.includes(k));}
function categorySummary(key){const list=S.vials.filter(v=>groupFor(v)===key),unit=key==='water'?'mL':'mg',sizes=new Map();for(const v of list){const n=stock(v).total;sizes.set(n,(sizes.get(n)||0)+1);}const capacity=[...sizes].sort((a,b)=>a[0]-b[0]).map(([size,n])=>`${n} × ${fmt(size)} ${unit}`).join(' + ');return {list,unit,capacity:capacity||'0 containers',remaining:list.reduce((n,v)=>n+stock(v).remaining,0),used:list.reduce((n,v)=>n+stock(v).used,0)};}
function supplyMini(type){const bottle=type==='vial'||type==='water',label=type==='water'?'BAC':'RET';return `<svg class="supply-mini" viewBox="0 0 48 56" aria-hidden="true" focusable="false">${bottle?`<rect x="15" y="5" width="18" height="7" rx="2" fill="var(--accent-readable)"/><path d="M17 12v6l-5 5v24q0 4 4 4h16q4 0 4-4V23l-5-5v-6Z" fill="var(--soft)" stroke="var(--muted)" stroke-width="1.4"/><rect x="13" y="28" width="22" height="15" rx="2" fill="var(--card)"/><text x="24" y="38.5" text-anchor="middle" fill="var(--ink)" font-family="system-ui" font-size="8.5" font-weight="750">${label}</text><path d="M17 24v20" stroke="var(--accent-readable)" opacity=".25"/>`:type==='pen'?`<g transform="rotate(24 24 28)"><rect x="18" y="4" width="12" height="48" rx="5" fill="var(--soft)" stroke="var(--muted)" stroke-width="1.4"/><path d="M18 34h12M18 14h12" stroke="var(--accent-readable)" stroke-width="2"/><rect x="21" y="19" width="6" height="9" rx="1" fill="var(--card)" stroke="var(--muted)"/><path d="M26 37v10" stroke="var(--accent-readable)" stroke-width="2"/></g>`:`<rect x="16" y="7" width="16" height="42" rx="5" fill="var(--soft)" stroke="var(--muted)" stroke-width="1.4"/><rect x="17" y="8" width="14" height="6" rx="2" fill="var(--accent-readable)"/><path d="M17 39h14m-14 4h14" stroke="var(--muted)" stroke-width="3"/><path d="M20 19v15" stroke="var(--accent-readable)" opacity=".4"/>`}</svg>`;}
const supplyCard173=supplyCard17;supplyCard17=function(v){const box=document.createElement('div');box.innerHTML=supplyCard173(v);const name=box.querySelector('summary .grow'),identity=document.createElement('div');identity.className='supply-identity grow';name.before(identity);identity.innerHTML=supplyMini(groupFor(v));identity.append(name);const b=stock(v);if(b.unit==='mg'&&b.remaining<=3){const amount=box.querySelector('.stock-summary>b');amount.classList.add('low-amount');if(b.remaining>0)amount.insertAdjacentHTML('afterend','<span class="low-label">Low</span>');}return box.innerHTML;};
supplyBreakdown=function(){return '<div class="balance-breakdown">'+supplyOrder().map(k=>{const b=categorySummary(k),title=supplyGroups.find(g=>g[0]===k)[1];return `<div class="balance-category"><b>${title}</b><p>${b.capacity} · <strong>${fmt(b.remaining)} ${b.unit} left</strong> · ${fmt(b.used)} ${b.unit} used</p></div>`;}).join('')+'</div>';};
const inventory173=inventory;inventory=function(){const box=document.createElement('div');box.innerHTML=inventory173();const groups=[...box.querySelectorAll('.supply-group')];groups.forEach(el=>el.remove());const arrange=document.createElement('button');arrange.className='link';arrange.textContent='Arrange categories ⠿';arrange.setAttribute('onclick','arrangeSupplies()');box.append(arrange);supplyOrder().forEach(key=>{const el=groups.find(g=>g.id==='group-'+key);if(!el)return;const b=categorySummary(key),title=supplyGroups.find(g=>g[0]===key)[1];el.querySelector('summary').innerHTML=`<div class="category-heading"><div class="supply-category-title">${supplyMini(key)}<b>${title}</b></div><span class="hint">${b.capacity} · <strong>${fmt(b.remaining)} ${b.unit} left</strong> · ${fmt(b.used)} ${b.unit} used</span></div>`;box.append(el);});return box.innerHTML;};
function arrangeSupplies(){modal('Arrange supply categories',`<p class="hint" id="move-help">Hold a six-dot handle and drag. Keyboard: ↑ / ↓.</p><div id="home-sort">${supplyOrder().map(k=>`<div class="home-sort-row" data-key="${k}"><b class="grow">${supplyGroups.find(g=>g[0]===k)[1]}</b><button class="drag-handle" aria-label="Move ${supplyGroups.find(g=>g[0]===k)[1]}" onkeydown="moveSupplyKey(event,'${k}')"><svg viewBox="0 0 24 24" width="24" height="24" aria-hidden="true">${[6,12,18].map(y=>`<circle cx="8" cy="${y}" r="1.8"/><circle cx="16" cy="${y}" r="1.8"/>`).join('')}</svg></button></div>`).join('')}</div><p id="sort-status" class="hint" aria-live="polite">Order saves when you release.</p>${button('Done','closeModal();render()')}`);setupHomeDrag(keys=>change(()=>S.settings.supplyOrder=keys));}
function moveSupplyKey(e,k){if(!['ArrowUp','ArrowDown'].includes(e.key))return;e.preventDefault();const a=supplyOrder(),i=a.indexOf(k),j=i+(e.key==='ArrowUp'?-1:1);if(j<0||j>=a.length)return;[a[i],a[j]]=[a[j],a[i]];if(change(()=>S.settings.supplyOrder=a)){arrangeSupplies();document.querySelector(`[data-key="${k}"] .drag-handle`).focus();}}
const editSupply173=editVial;editVial=function(id){editSupply173(id);const sheet=$('#modal .sheet'),save=sheet.querySelector('button.primary'),remove=sheet.querySelector('button.danger');save.remove();if(remove)remove.remove();const bar=()=>`<div class="supply-form-actions"><button class="compact-action save-action" onclick="saveVial('${id||''}')" aria-label="Save supply"><svg class="icon" viewBox="0 0 24 24"><path d="M5 3h12l3 3v15H4V3h1Zm2 0v7h10V3M8 21v-7h8v7"/></svg><span>Save</span></button>${id?`<button class="compact-action remove-action" onclick="removeVial('${id}')" aria-label="Remove supply"><svg class="icon" viewBox="0 0 24 24"><path d="M3 6h18M9 6V3h6v3M6 6l1 15h10l1-15M10 10v7m4-7v7"/></svg><span>Remove</span></button>`:''}</div>`;$('#form-error').insertAdjacentHTML('afterend',bar());sheet.insertAdjacentHTML('beforeend',bar());};
const measureNames={neck:'Neck',chest:'Chest',biceps:'Biceps',waist:'Waist',hips:'Hips',thigh:'Thigh',calf:'Calf'};
const measureHelp={neck:'Measure around the neck. Keep the tape level.',chest:'Measure around the chest at a consistent level.',biceps:'Measure around the upper arm; use the same arm and relaxed or flexed position each time.',waist:'Use the same waist landmark each time and record it in your note.',hips:'Measure around the widest part of the hips.',thigh:'Measure around the thigh at the same level and on the same leg each time.',calf:'Measure around the widest part of the calf, using the same leg each time.'};
function bodyMeasureArt(){const female=S.profile.sex==='female';const zones=[['neck',158,56,202,56],['chest',133,100,227,100],['biceps',106,117,130,117],['waist',141,144,219,144],['hips',132,181,228,181],['thigh',137,221,175,221],['calf',142,284,165,284]];return `<svg class="body-measure-art" viewBox="0 0 360 330" role="img" aria-label="${female?'Female':'Male'} body circumference locations"><circle cx="180" cy="27" r="20" fill="var(--soft)" stroke="var(--muted)"/><path d="M162 46L160 61Q135 62 120 77L92 151L108 159L135 107${female?'Q138 131 146 145L132 182':'L140 147L134 182'}L135 211L139 313H166L180 222L194 313H221L225 211L226 182${female?'L214 145Q222 131 225 107':'L220 147L225 107'}L252 159L268 151L240 77Q225 62 200 61L198 46" fill="var(--soft)" stroke="var(--muted)" stroke-width="1.6"/>${zones.map(([k,x1,y1,x2,y2],i)=>`<g id="zone-${k}" class="measure-zone" role="button" tabindex="0" aria-label="Measure ${measureNames[k]}" onclick="selectMeasure('${k}',true)" onkeydown="if(event.key==='Enter'||event.key===' '){event.preventDefault();selectMeasure('${k}',true)}"><path d="M${x1} ${y1}H${x2}" class="measure-hit"/><path d="M${x1} ${y1}H${x2}" class="measure-line"/><text x="${i%2?235:12}" y="${y1+4}">${measureNames[k]}</text></g>`).join('')}</svg>`;}
function selectMeasure(k,focus){document.querySelectorAll('.measure-zone').forEach(el=>el.classList.toggle('selected',el.id==='zone-'+k));$('#measure-instruction').textContent=measureHelp[k];if(focus){const input=$('#circ-'+k);input.focus({preventScroll:true});input.scrollIntoView({block:'nearest',behavior:'smooth'});}}
function editCircumferences(id){const r=(S.circumferences||[]).find(x=>x.id===id)||{values:{}};modal('Body circumferences',`${field('circ-at','Date & time',local(r.at),'datetime-local')}<p class="hint">Optional measurements in cm. Tap a line or a field to highlight the matching area.</p>${bodyMeasureArt()}<p class="hint" id="measure-instruction">Use the same position, body side and tape placement for comparisons.</p><div class="grid2">${Object.entries(measureNames).map(([k,n])=>field('circ-'+k,n+' · cm',r.values[k]??'','number')).join('')}</div>${field('circ-note','Note · side / measurement position (optional)',r.note||'')}${button('Save measurements',`saveCircumferences('${id||''}')`)}${id?button('Delete measurements',`deleteCircumferences('${id}')`,'danger'):''}`);Object.keys(measureNames).forEach(k=>$('#circ-'+k).onfocus=()=>selectMeasure(k,false));}
function saveCircumferences(id){try{const at=new Date(val('circ-at')).toISOString();if(Date.parse(at)>Date.now())throw Error('Choose a current or past time.');const values={};for(const k of Object.keys(measureNames))if(val('circ-'+k)!==''){values[k]=Core.positive(val('circ-'+k),measureNames[k]);if(values[k]>300)throw Error('Check measurements in cm.');}if(!Object.keys(values).length)throw Error('Enter at least one measurement.');const r={id:id||uid(),at,values,note:val('circ-note')};if(change(()=>{S.circumferences=(S.circumferences||[]).filter(x=>x.id!==id);S.circumferences.push(r);},true)){closeModal();render();toast('Body measurements saved.',true);}}catch(e){formError(e);}}
function deleteCircumferences(id){if(confirm('Delete these body measurements?')&&change(()=>S.circumferences=S.circumferences.filter(x=>x.id!==id),true)){closeModal();render();toast('Measurements deleted.',true);}}
function circumferenceCard(){const rows=[...(S.circumferences||[])].sort((a,b)=>Date.parse(b.at)-Date.parse(a.at));return card(`<h2>Body circumferences</h2><p class="hint">Optional · cm · dated records</p>${button('+ Add body measurements','editCircumferences()','secondary')}${rows.length?`<details class="circ-history"><summary>${rows.length} records · latest ${dayDate(rows[0].at)}</summary>${rows.map(r=>`<div class="list-item"><div class="row spread"><b>${dayDate(r.at)} · ${clock(r.at)}</b><button class="icon-button" aria-label="Edit body measurements" onclick="editCircumferences('${r.id}')">${icon('edit')}</button></div><p>${Object.entries(r.values).map(([k,v])=>measureNames[k]+': '+fmt(v)+' cm').join(' · ')}</p>${r.note?`<p class="hint">${esc(r.note)}</p>`:''}</div>`).join('')}</details>`:'<p class="hint">No measurements yet.</p>'}`);}
const profile173=profile;profile=function(){return profile173()+circumferenceCard();};
const render173=render;render=function(){render173();document.querySelectorAll('main>.card:not(.hero)').forEach(el=>{if(el.querySelector('canvas'))el.classList.add('graph-surface');});};
// Boot is owned by app18 after additive extensions have been installed.
