'use strict';
Core.migrate18(S);
if(!S.settings.dateOrder||!S.settings.timeFormat){let formats={};try{formats=window.Native?.deviceFormats?JSON.parse(Native.deviceFormats()):{dateOrder:navigator.language==='en-US'?'MDY':'DMY',timeFormat:new Intl.DateTimeFormat(undefined,{hour:'numeric'}).resolvedOptions().hour12?'12':'24'};}catch(e){}S.settings.dateOrder=S.settings.dateOrder||formats.dateOrder||'DMY';S.settings.timeFormat=S.settings.timeFormat||formats.timeFormat||'24';}
const imperial=()=>S.settings.units==='imperial';
const icon18=icon;icon=function(k){if(k==='syringe')return '<svg class="icon" viewBox="0 0 24 24"><path d="m15 3 6 6m-4-4-3 3m-3-2 7 7M4 17l3 3 10-10-3-3L4 17Zm0 0-2 5m6-9 3 3m0-6 3 3"/></svg>';if(k==='food')return '<svg class="icon" viewBox="0 0 24 24"><path d="M3 8h11v8H3zM14 11h6a2 2 0 0 1 0 4h-6M3 8l3-4 3 1 2-2 3 5M5 19h7"/></svg>';if(k==='wrench')return '<svg class="icon" viewBox="0 0 24 24"><path d="M14 3a6 6 0 0 0-5 8L3 17a3 3 0 0 0 4 4l6-6a6 6 0 0 0 8-7l-4 4-4-4 4-4z"/></svg>';return icon18(k);};
const unitLabel=k=>({weight:imperial()?'lb':'kg',length:imperial()?'in':'cm',water:imperial()?'US fl oz':'mL'})[k];
const displayValue=(v,k)=>Core.unitValue(v,k,imperial());
const canonicalValue=(v,k)=>Core.unitValue(v,k,imperial(),true);
const weightText=v=>fmt(displayValue(v,'weight'),1)+' '+unitLabel('weight');
date=(x)=>new Date(x).toLocaleDateString(S.settings.dateOrder==='MDY'?'en-US':'en-GB',{day:'2-digit',month:'2-digit',year:'2-digit'});
clock=x=>new Date(x).toLocaleTimeString('en-GB',{hour:'2-digit',minute:'2-digit',hour12:S.settings.timeFormat==='12'});
dayDate=t=>new Date(t).toLocaleDateString('en-GB',{weekday:'short'})+' · '+date(t);
latestWeight=()=>Core.currentWeight(S.measurements);
const theme18=applyTheme;applyTheme=function(){theme18();document.body.classList.toggle('new-design',S.settings.design==='new');let color=S.settings.color||'#087580';for(let i=0;i<12&&Core.contrast(color,'#f0f5f9')<4.5;i++){color='#'+color.slice(1).match(/../g).map(x=>Math.floor(parseInt(x,16)*.85).toString(16).padStart(2,'0')).join('');}document.documentElement.style.setProperty('--light-card-accent',color);if(window.Native?.fontScale)document.body.classList.toggle('large-text',Native.fontScale()>=1.25);};
function designSwitch(value){setSetting('design',value?'new':'classic');}
const settings18=settings;settings=function(){return settings18()+card(`<h2>Compare designs</h2><label class="check"><input id="new-design" type="checkbox" ${S.settings.design==='new'?'checked':''} onchange="designSwitch(this.checked)">New design</label><p class="hint">Off: Classic. On: new navigation and Today layout. Both views share all records and settings.</p>`)+card(`<h2>Display preferences</h2>${select('units18','Units',[['metric','Metric · kg / cm / mL'],['imperial','Imperial · lb / in / US fl oz']],S.settings.units||'metric')}${select('date18','Date',[['DMY','DD/MM/YY'],['MDY','MM/DD/YY']],S.settings.dateOrder||'DMY')}${select('time18','Time',[['24','24 hours'],['12','12 hours · AM/PM']],S.settings.timeFormat||'24')}${select('mode18','Daily weight',[['latest','Latest record'],['lowest','Lowest weight'],['average','Average weight']],S.settings.weightMode)}${button('Save display preferences','saveDisplay18()')}<p class="hint">Stored data remains in kg, cm, mL and g. Medical units and calculator volumes do not change.</p>`)+card(`<h2>Supply alerts</h2>${field('low-mg','Low threshold · mg',S.settings.lowMg??3,'number')}${field('low-ml','Water Low threshold · mL (optional)',S.settings.lowMl??'','number')}${button('Save thresholds','saveThreshold18()','secondary')}`);};
function saveDisplay18(){if(change(()=>{S.settings.units=val('units18');S.settings.dateOrder=val('date18');S.settings.timeFormat=val('time18');S.settings.weightMode=val('mode18');}))render();}
function saveThreshold18(){try{const mg=Core.positive(val('low-mg')),ml=val('low-ml')?Core.positive(val('low-ml')):null;if(change(()=>{S.settings.lowMg=mg;S.settings.lowMl=ml;}))render();}catch(e){formError(e);}}
setWeightMode=function(value){if(['latest','lowest','average'].includes(value))setSetting('weightMode',value);};
function editProteinRange(){const p=S.profile;modal('Protein target range',`${field('range-weight','Target weight · '+unitLabel('weight'),p.target?displayValue(p.target,'weight'):'','number')}${select('range-mode','Calculation',[['weight','Target weight × g/kg'],['manual','Manual range · grams']],p.proteinRangeMode||'weight')}<div class="grid2">${field('range-low','Minimum · g/kg',p.proteinKMin??1.6,'number')}${field('range-high','Maximum · g/kg',p.proteinKMax??2.2,'number')}</div><div class="grid2">${field('range-min','Manual minimum · g',p.proteinMin||'','number')}${field('range-max','Manual maximum · g',p.proteinMax||'','number')}</div><p class="hint">An adjustable planning preset, not an individual medical recommendation. Your previous nutrition target (${fmt(p.protein)} g) remains separate. The midpoint is the arithmetic average of the range.</p>${button('Save range','saveProteinRange()')}`);}
function saveProteinRange(){try{const p={...S.profile,target:val('range-weight')?canonicalValue(Core.positive(val('range-weight')),'weight'):null,proteinRangeMode:val('range-mode'),proteinKMin:Core.positive(val('range-low')),proteinKMax:Core.positive(val('range-high')),proteinMin:val('range-min')?Core.positive(val('range-min')):null,proteinMax:val('range-max')?Core.positive(val('range-max')):null};if(!Core.proteinRange(p))throw Error('Set target weight or a manual range.');if(change(()=>S.profile=p)){closeModal();render();}}catch(e){formError(e);}}
function targetTile(kind,day){const totals=Core.dayTotals(S,day),water=kind==='water',range=water?{min:Number(S.settings.waterTarget)||0,max:Number(S.settings.waterTarget)||0}:Core.proteinRange(S.profile),value=water?totals.water:totals.protein,p=range&&range.min?Core.targetProgress(value,range.min,range.max):null,unit=water?unitLabel('water'):'g',show=n=>fmt(water?displayValue(n,'water'):n,0),enabled=water?S.settings.waterLogging:S.settings.proteinLogging;return card(`<div class="row spread">${icon(water?'water':'food')}<h3>${water?'Hydration':'Protein intake'}</h3></div><p class="hint">${p?'Target '+show(p.min)+(p.max!==p.min?'–'+show(p.max):'')+' '+unit+(!water?'<br>Midpoint '+show(range.mid)+' g':''):water?'Set hydration target':'Set target weight'}</p><div class="big status-${p?.color||'unset'}">${show(value)} <small>${unit}</small></div><p class="hint">${p?p.label:'Logged today'}${enabled?'':' · logging off'}</p>${p?`<progress max="100" value="${p.fill}" aria-label="Progress to minimum target"></progress><p class="hint">${fmt(p.percent,0)}% of minimum target<br>${show(p.remaining)} ${unit} · ${fmt(p.remainingPercent,0)}% to minimum</p>`:''}${enabled?water?`<div class="chipbar">${[250,300,500].map(n=>`<button onclick="quickWater(${n})">+${show(n)} ${unit}</button>`).join('')}</div>`:button('+ Add protein',"editDaily('protein')",'secondary'):''}<button class="link" onclick="${water?'dailySettings()':'editProteinRange()'}">Edit target →</button>`,'target-tile');}
dailyTargets17=function(){return `<div class="daily-pair">${targetTile('water',page==='wellness'?dailyDay:Core.isoDay(Date.now()))}${targetTile('protein',page==='wellness'?dailyDay:Core.isoDay(Date.now()))}</div>`;};
function celebrateTargets18(before,day){if(day!==Core.isoDay(Date.now()))return;const after=Core.dayTotals(S,day),r=Core.proteinRange(S.profile),targets={water:+S.settings.waterTarget,protein:r?.min};for(const k of ['water','protein']){const target=targets[k],key=day+':'+k;if(target>0&&before[k]<target&&after[k]>=target&&!S.settings.reachedTargets?.includes(key)){if(change(()=>{S.settings.reachedTargets=[...(S.settings.reachedTargets||[]),key].slice(-730);}))toast('✓ Great work — daily '+(k==='water'?'hydration':'protein')+' target reached.');}}}
const quickWater18=quickWater;quickWater=function(ml){const day=Core.isoDay(Date.now()),before=Core.dayTotals(S,day);quickWater18(ml);celebrateTargets18(before,day);};
const editDaily18=editDaily;editDaily=function(type,id,repeat){editDaily18(type,id,repeat);if(type==='water'&&imperial()){const input=$('#daily-amount');if(input.value)input.value=displayValue(+input.value,'water');input.previousElementSibling.textContent='Drink volume · US fl oz';}};
const saveDaily18=saveDaily;saveDaily=function(type,id){if(!$('#daily-at'))return;const day=Core.isoDay(val('daily-at')),before=Core.dayTotals(S,day),input=$('#daily-amount'),entered=input.value;if(type==='water'&&imperial())input.value=canonicalValue(entered,'water');saveDaily18(type,id);if($('#daily-amount'))input.value=entered;else celebrateTargets18(before,day);};
const dailySettings18=dailySettings;dailySettings=function(){dailySettings18();$('#modal .sheet').insertAdjacentHTML('beforeend',button('Edit protein target range','editProteinRange()','secondary'));};
const overview18=overview;
function checkInCard18(){const f=[...S.feelings].filter(f=>Core.isoDay(f.at)===Core.isoDay(Date.now())).sort((a,b)=>Date.parse(b.at)-Date.parse(a.at))[0];return card(`<div class="row spread"><h2>Daily check-in</h2>${button(f?'Edit':'+ Check in',`editFeeling('${f?.id||''}')`,'secondary')}</div><p class="hint">${dayDate(Date.now())}</p>${f?`<p>${esc(f.note||'Your check-in is recorded.')}</p>`:'<p class="hint">How do you feel today?</p>'}`);}
overview=function(){if(S.settings.design!=='new')return overview18();const tools=[['learn','Equipment & Learn',"navigate('learn')"],['journal','Daily records',"navigate('wellness')"],['shield','Backup & reports',"navigate('data')"],['settings','Arrange cards','editHome()'],['calc','Calculator',"navigate('calculator')"]];return header(S.profile.name?'Hello, '+esc(S.profile.name.split(' ')[0])+'.':'Your day, clearly.','Your records. Your daily rhythm.')+`<div class="quickrow">${button('+ Log','quickLog()')}${button('Tracking settings','dailySettings()','secondary')}</div>`+homeContent()+checkInCard18()+card(`<h2 class="row">${icon('wrench')} Your toolkit</h2><div class="toolkit-grid">${tools.map(([i,n,a])=>button(icon(i)+'<span>'+n+'</span>',a,'secondary')).join('')}</div>`);};
const weightHome18=weightHome;weightHome=function(){const w=latestWeight(),days=Core.weightDays(S.measurements,S.settings.weightMode).filter(r=>r.t>=Date.now()-7*Core.DAY);const min=Math.min(...days.map(x=>x.weight)),max=Math.max(...days.map(x=>x.weight));const dots=days.map(r=>{const x=4+92*(r.t-(Date.now()-7*Core.DAY))/(7*Core.DAY),y=27-20*(r.weight-min)/(max-min||1);return `<circle cx="${x}" cy="${y}" r="2"/>`;}).join('');return card(`<div class="row spread"><div class="eyebrow">Latest weight</div><button class="icon-button" aria-label="Open weight chart" onclick="openWeight()">${icon('arrow')}</button></div><div class="stat">${w?weightText(w.values.weight):'—'}</div><p class="hint">${w?dayDate(w.at)+' · '+clock(w.at)+'<br>'+esc(w.source||'Manual'):'Add a measurement'}</p><svg class="weight-spark" viewBox="0 0 100 34" role="img" aria-label="Last 7 days: ${weightModeLabel()}">${dots}</svg>`);};
const render18=render;render=function(){render18();if(S.settings.design==='new'){$('#app>nav').innerHTML=[['overview','home','Today'],['journal','journal','Journal'],['insights','chart','Progress'],['inventory','box','Supplies'],['profile','user','Profile']].map(([p,i,n])=>`<button aria-label="${n}" class="${p===page?'active':''}" ${p===page?'aria-current="page"':''} onclick="navigate('${p}')">${icon(i)}<span>${n}</span></button>`).join('');}document.querySelectorAll('select[id^="weight-"]').forEach(el=>{if(!el.querySelector('[value="lowest"]'))el.add(new Option('Lowest weight','lowest'));el.value=S.settings.weightMode;});const half=$('#half');if(half){half.parentElement.classList.add('model-settings18');const save=[...half.parentElement.querySelectorAll('button')].find(x=>x.getAttribute('onclick')==='saveHalf()');if(save)save.textContent='Save';}document.querySelectorAll('.supply-card').forEach(el=>{const v=S.vials.find(v=>'supply-'+v.id===el.id);if(!v)return;el.querySelectorAll('.low-label').forEach(x=>x.remove());const b=stock(v),limit=v.type==='water'?S.settings.lowMl:S.settings.lowMg??3;if(limit&&b.remaining>0&&b.remaining<=limit&&!Core.bacExpiry(v)?.expired){el.querySelector('.stock-summary')?.insertAdjacentHTML('beforeend','<span class="low-label">Low</span>');el.querySelector('.stock-summary')?.classList.add('status-low');}});};
let feelingEdit18='';const feelingForm18=editFeeling;editFeeling=function(id=''){feelingEdit18=id;feelingForm18();const f=S.feelings.find(x=>x.id===id);if(f){$('#feeling-at').value=local(f.at);Object.entries(f.values).forEach(([k,v])=>{if($('#feel-'+k))$('#feel-'+k).value=v;});$('#feeling-note').value=f.note||'';$('#feeling-day').textContent=dayDate(f.at);}$('#modal .sheet').insertAdjacentHTML('beforeend',button('Cancel','closeModal()','secondary'));};
saveFeeling=function(){try{if(!$('#feeling-at'))return;const at=new Date(val('feeling-at')).toISOString();if(Date.parse(at)>Date.now())throw Error('Choose a current or past date.');const values={};['Appetite','Nausea','Energy','Mood','Libido','Digestion'].forEach(k=>{if(val('feel-'+k))values[k]=+val('feel-'+k);});const id=feelingEdit18||uid(),old=S.feelings.find(f=>f.id===id),record={...old,id,at,values,note:val('feeling-note')};if(change(()=>{S.feelings=S.feelings.filter(f=>f.id!==id);S.feelings.push(record);},true)){closeModal();render();toast('Check-in saved.',true);}}catch(e){formError(e);}};
let journalFilter18='dose';const journal18=journal;journal=function(){const filters=`<div class="chipbar">${[['dose','Doses'],['all','All'],['water','Hydration'],['protein','Protein'],['feeling','Check-ins']].map(([k,n])=>`<button class="${journalFilter18===k?'on':''}" onclick="journalFilter18='${k}';render()">${n}</button>`).join('')}</div>`;if(journalFilter18==='dose')return filters+journal18().replace('Your journal',icon('syringe')+' Your journal');const rows=[...S.hydration.map(r=>({...r,kind:'water'})),...S.proteinLog.map(r=>({...r,kind:'protein'})),...S.feelings.map(r=>({...r,kind:'feeling'})),...S.entries.map(r=>({...r,kind:'dose'}))].filter(r=>journalFilter18==='all'||r.kind===journalFilter18).sort((a,b)=>Date.parse(b.at)-Date.parse(a.at));return header('Your Journal','All your original records, in one place.')+filters+button('+ Log','quickLog()')+rows.map(r=>{const label=r.kind==='water'?fmt(displayValue(r.ml,'water'))+' '+unitLabel('water'):r.kind==='protein'?fmt(r.grams)+' g · '+proteinSources[r.source]:r.kind==='dose'?fmt(r.mg)+' mg':'Check-in',edit=r.kind==='dose'?`editEntry('${r.id}')`:r.kind==='feeling'?`editFeeling('${r.id}')`:`editDaily('${r.kind}','${r.id}')`;return card(`<div class="row spread">${icon(r.kind==='water'?'water':r.kind==='protein'?'food':r.kind==='dose'?'syringe':'user')}<b>${label}</b><span class="grow"></span><button class="icon-button" aria-label="Edit entry" onclick="${edit}">${icon('edit')}</button><button class="icon-button" aria-label="Delete entry" onclick="confirmRecord18('${r.kind}','${r.id}')">${trash18()}</button></div><p class="hint">${dayDate(r.at)} · ${clock(r.at)}</p>${r.note?'<p>'+esc(r.note)+'</p>':''}`);}).join('');};
function trash18(){return '<svg class="icon" viewBox="0 0 24 24"><path d="M3 6h18M9 6V3h6v3M5 6l1 15h12l1-15M10 10v7m4-7v7"/></svg>';}
function confirmRecord18(kind,id){const key={dose:'entries',feeling:'feelings',water:'hydration',protein:'proteinLog'}[kind],r=S[key]?.find(x=>x.id===id);if(!r)return;modal('Delete this entry?',`<p>${dayDate(r.at)} · ${clock(r.at)}</p><p>${r.mg?fmt(r.mg)+' mg':r.ml?fmt(r.ml)+' mL':r.grams?fmt(r.grams)+' g':esc(r.note||'Check-in')}</p><p>This action will remove the selected record.</p>${button('Cancel','closeModal()','secondary')}${button('Delete',`deleteRecord18('${kind}','${id}')`,'danger')}`);}
function deleteRecord18(kind,id){const key={dose:'entries',feeling:'feelings',water:'hydration',protein:'proteinLog'}[kind];if(key&&change(()=>S[key]=S[key].filter(x=>x.id!==id),true)){closeModal();render();toast('Entry deleted.',true);}}
deleteDaily=(type,id)=>confirmRecord18(type,id);removeFeeling=id=>confirmRecord18('feeling',id);
const saveEntry18=saveEntry;saveEntry=function(id){try{if(!$('#entry-mg'))return;const vial=val('entry-vial'),v=S.vials.find(v=>v.id===vial);if(v&&val('entry-status')==='taken'){const used=Core.supplyBalance(v,S.entries.filter(e=>e.id!==id)).used;if(v.discardedAt||used+Core.positive(val('entry-mg'))>Number(v.mg)+1e-8)throw Error('This entry exceeds the available supply. Correct the amount or explicitly select another supply.');}saveEntry18(id);}catch(e){formError(e);}};
const profile18=profile;profile=function(){const w=latestWeight(),r=Core.proteinRange(S.profile);return card(`<h2>Current weight</h2><div class="big">${w?weightText(w.values.weight):'—'}</div><p class="hint">${w?dayDate(w.at)+' · '+clock(w.at)+' · '+esc(w.source||'Manual'):'No measurement recorded.'}</p>${button('Record weight','editMeasurement()','secondary')}`)+card(`<h2>Protein target</h2><p>${r?'Target '+fmt(r.min,0)+'–'+fmt(r.max,0)+' g · Midpoint '+fmt(r.mid,0)+' g':'Set target weight'}</p>${S.profile.protein?'<p class="hint">Saved nutrition target: '+fmt(S.profile.protein)+' g (separate from range midpoint)</p>':''}${button('Edit range','editProteinRange()','secondary')}`)+profile18();};
const editProfile18=editProfile;editProfile=function(){editProfile18();const w=latestWeight();$('#p-weight').previousElementSibling.textContent='Current weight · kg';if(w){$('#p-weight').value=w.values.weight;$('#p-weight').readOnly=true;$('#p-weight').insertAdjacentHTML('afterend','<p class="hint">From your latest measurement. Use Record weight to add a new reading.</p>');}};
saveProfile=function(){try{const p=readProfile();Core.macros(p);if(change(()=>{S.profile=p;if(!S.measurements.some(r=>Number(r.values?.weight)>0))S.measurements.push({id:uid(),at:new Date().toISOString(),source:'Profile initial weight',values:{weight:p.weight}});})){closeModal();render();toast('Profile saved.');}}catch(e){formError(e);}};
const weightMarkup18=weightChartMarkup;weightChartMarkup=function(){return weightMarkup18().replace('<button onclick="weightRange(30)">','<button onclick="weightRange(14)">14D</button><button onclick="weightRange(30)">');};
const setupChart18=setupChart;setupChart=function(){setupChart18();if(chart)chartRange(7);};
const setupWeight18=setupWeightChart;setupWeightChart=function(){setupWeight18();if(weightChart)weightRange(7);};
openWeight=function(){navigate('insights');requestAnimationFrame(()=>{$('.weight-chart-card')?.scrollIntoView({block:'start'});});};
const full18=toggleFull;toggleFull=function(){full18();NativeImmersive18();};
const fullWeight18=toggleWeightFull;toggleWeightFull=function(){fullWeight18();NativeImmersive18();};
function NativeImmersive18(){window.Native?.setImmersive?.(document.body.classList.contains('full-chart')||document.body.classList.contains('full-weight'));}
const navigate18=navigate;navigate=function(p){navigate18(p);NativeImmersive18();};
const insights18=insights;insights=function(){return insights18().replace('Estimated amount · mg','Estimated amount (mg)').replace('<button onclick="chartRange(30)"','<button onclick="chartRange(14)">14D</button><button onclick="chartRange(30)"')+circumferenceCard();};
equipmentFigure=function(file,title,body){return `<figure class="equipment-figure"><h3>${title}</h3><img class="equipment-photo" src="${file}" alt="Illustrated ${esc(title)}" loading="lazy"><figcaption class="hint">AI illustration · not to scale or a compatibility reference.</figcaption><p>${body}</p></figure>`;};
// Water expiry metadata is explicit, never inferred from a purchase date.
const stock18=stock;stock=function(v){const b=stock18(v);return {...b,discarded:Number(v.discardedAmount)||0,remaining:v.discardedAt?0:b.remaining};};
const editVial18=editVial;editVial=function(id){editVial18(id);const v=S.vials.find(v=>v.id===id)||{},input=$('#v-opened');input.type='datetime-local';input.removeAttribute('max');input.value=v.openedAt?(v.openedAt.length===10?v.openedAt+'T00:00':local(v.openedAt)):'';input.previousElementSibling.textContent='First opening / puncture · date & time (optional)';$('#v-water-fields').insertAdjacentHTML('beforeend',`${select('bac-kind','Manufacturer container label',[['unknown','Not confirmed'],['multi','Multidose'],['single','Single-use']],v.multidose===true?'multi':v.multidose===false?'single':'unknown')}${field('bac-expiry','Factory expiry (optional; start of selected date)',v.expiresAt||'','date')}${field('bac-days','Manufacturer post-opening days (optional)',v.afterOpeningDays??'','number')}<p class="hint">28 days applies only when Multidose is confirmed and no different manufacturer period is entered. Single-use water is not assigned 28 days. Countdown does not guarantee sterility.</p>`);};
saveVial=function(id){try{if(!$('#v-name'))return;const old=S.vials.find(v=>v.id===id)||{},water=val('v-type')==='water',opened=val('v-opened');if(opened&&Date.parse(opened)>Date.now())throw Error('Opening time cannot be in the future.');if(water&&old.type&&old.type!=='water'&&S.entries.some(e=>e.vial===id))throw Error('This supply has linked doses; create a separate water vial.');const v={...old,id:id||uid(),name:val('v-name').trim(),type:val('v-type'),state:water?'Water':val('v-state'),mg:water?0:Core.positive(val('v-mg')),volume:val('v-volume')?Core.positive(val('v-volume')):null,usedMl:water?Core.num(val('v-used')):0,prepared:val('v-prepared'),openedAt:opened?new Date(opened).toISOString():'',note:val('v-note')};if(!v.name)throw Error('Give the supply a label.');if(water){v.multidose=val('bac-kind')==='multi'?true:val('bac-kind')==='single'?false:null;v.expiresAt=val('bac-expiry');v.afterOpeningDays=val('bac-days')?Core.positive(val('bac-days')):null;if(!v.volume||!Number.isFinite(v.usedMl)||v.usedMl<0||v.usedMl>v.volume)throw Error('Water used must be between zero and total volume.');if(v.usedMl>(old.usedMl||0)&&(!v.openedAt||!Core.bacExpiry(v).usable))throw Error('New water use is blocked: enter the opening date and check the expiry and manufacturer label.');if(old.discardedAt&&v.usedMl!==(old.usedMl||0))throw Error('This vial was discarded. History is retained.');}else if(Core.supplyBalance(v,S.entries).overdrawn>0)throw Error('Capacity cannot be lower than the amount already recorded.');if(change(()=>{S.vials=S.vials.filter(x=>x.id!==id);S.vials.push(v);},true)){closeModal();render();toast('Supply saved.',true);}}catch(e){formError(e);}};
markOpened=function(id){editVial(id);$('#v-opened').value=local();};
function expiryPanel18(v){const x=Core.bacExpiry(v);if(!x)return '';const text=x.state==='discarded'?'Discarded':x.expired?'Expired — do not use. Discard this vial.':x.state==='unknown'?'Opening date or manufacturer period needed':x.state==='unopened'?'Unopened':x.state==='soon'?'Expires soon':'Opened';const time=x.deadline?dayDate(x.deadline)+' · '+clock(x.deadline):'No confirmed deadline';const remain=x.deadline&&!x.expired?(x.remaining<Core.DAY?Math.ceil(x.remaining/3600000)+' hours':x.days+' days')+' remaining · ':'';return `<div class="bac-status status-${x.expired?'low':x.state==='soon'?'almost':'unset'}"><b>${text}</b><p class="hint">${remain}${time}</p>${v.discardedAt?'<p class="hint">'+fmt(v.discardedAmount)+' mL discarded, not used.</p>':button('Mark as discarded',`discardVial18('${v.id}')`,'secondary')}</div>`;}
const supplyCard18=supplyCard17;supplyCard17=function(v){const box=document.createElement('div');box.innerHTML=supplyCard18(v);box.querySelector('.supply-detail')?.insertAdjacentHTML('afterbegin',expiryPanel18(v));const x=Core.bacExpiry(v);if(x&&(x.expired||x.state==='discarded'||x.state==='soon'||x.state==='unknown')){const badge=box.querySelector('.stock-badge');if(badge){badge.textContent=x.expired?'Expired':x.state==='discarded'?'Discarded':x.state==='soon'?'Expires soon':'Opening date needed';badge.className='stock-badge '+(x.expired?'status-low':'status-almost');}}return box.innerHTML;};
function discardVial18(id){const v=S.vials.find(x=>x.id===id);if(!v||v.discardedAt)return;modal('Discard this supply?',`<p>${esc(v.name)} · ${fmt(stock(v).remaining)} ${stock(v).unit} remaining</p><p>History stays unchanged. Discarded contents will not be counted as used or injected.</p>${button('Cancel','closeModal()','secondary')}${button('Mark as discarded',`commitDiscard18('${id}')`,'danger')}`);}
function commitDiscard18(id){const v=S.vials.find(x=>x.id===id);if(v&&!v.discardedAt&&change(()=>{v.discardedAmount=stock(v).remaining;v.discardedAt=new Date().toISOString();},true)){closeModal();render();}}
const inventory18=inventory;inventory=function(){return inventory18()+button('Calculator',"navigate('calculator')",'secondary');};
const inventoryDiscard18=inventory;inventory=function(){const box=document.createElement('div');box.innerHTML=inventoryDiscard18();for(const key of supplyOrder()){const discarded=S.vials.filter(v=>groupFor(v)===key).reduce((n,v)=>n+(Number(v.discardedAmount)||0),0);if(discarded)box.querySelector('#group-'+key+' .category-heading .hint')?.insertAdjacentHTML('beforeend',` · ${fmt(discarded)} ${key==='water'?'mL':'mg'} discarded`);}return box.innerHTML;};
const duplicate18=duplicateSupply;duplicateSupply=function(id){duplicate18(id);const v=S.vials.find(v=>v.id===id);if(v?.type==='water'){$('#bac-kind').value=v.multidose===true?'multi':v.multidose===false?'single':'unknown';$('#bac-days').value=v.afterOpeningDays||'';}};
function refreshExpiry18(){if(page==='inventory'&&!$('#modal').innerHTML&&(!window.retaV2SupplyRefresh||window.retaV2SupplyRefresh()))render();}
document.addEventListener('visibilitychange',()=>{if(!document.hidden)refreshExpiry18();});setInterval(refreshExpiry18,30000);
// Keep raw side-specific circumference records; legacy unsided fields remain.
for(const base of ['biceps','thigh','calf'])for(const side of ['Left','Right']){measureNames[base+side]=measureNames[base]+' · '+side;measureHelp[base+side]=measureHelp[base];}
const selectMeasure18=selectMeasure;selectMeasure=function(k,focus){const base=k.replace(/Left|Right$/,'');selectMeasure18(base,false);if(focus)$('#circ-'+k)?.focus();};
const editCirc18=editCircumferences;editCircumferences=function(id){editCirc18(id);if(imperial()){for(const k of Object.keys(measureNames)){const el=$('#circ-'+k);if(el.value)el.value=displayValue(+el.value,'length');el.previousElementSibling.textContent=measureNames[k]+' · in';}}};
const saveCirc18=saveCircumferences;saveCircumferences=function(id){if(!$('#circ-at'))return;const entered={};for(const k of Object.keys(measureNames)){const el=$('#circ-'+k);entered[k]=el.value;if(el.value&&imperial())el.value=canonicalValue(el.value,'length');}saveCirc18(id);if($('#circ-at'))for(const k of Object.keys(entered))$('#circ-'+k).value=entered[k];};
const circCard18=circumferenceCard;circumferenceCard=function(){const rows=[...S.circumferences].sort((a,b)=>Date.parse(a.at)-Date.parse(b.at));return circCard18()+((page==='insights'&&rows.length>1)?card(`<h3>Circumference changes</h3><p class="hint">First to latest actual record for each location.</p>${Object.keys(measureNames).map(k=>{const rs=rows.filter(r=>r.values[k]!=null);return rs.length>1?`<div class="list-item"><b>${measureNames[k]}</b><p>${fmt(displayValue(rs[0].values[k],'length'))} → ${fmt(displayValue(rs.at(-1).values[k],'length'))} ${unitLabel('length')}</p><p class="hint">${dayDate(rs[0].at)} — ${dayDate(rs.at(-1).at)}</p></div>`:'';}).join('')}`):'');};
const nativeEvent18=window.nativeEvent;window.nativeEvent=function(name,data){if(name==='resume'){refreshExpiry18();return;}nativeEvent18?.(name,data);};
deleteEntry=id=>confirmRecord18('dose',id);
const homeVisible18=homeVisible;homeVisible=function(k){return homeVisible18(k)&&!(S.settings.design==='new'&&!S.settings.homeOrder&&['weekly','estimate','forecast'].includes(k)&&!(S.settings.homeEnabled18||[]).includes(k));};
const toggleHome18=toggleHome;toggleHome=function(k,value){if(value&&S.settings.design==='new')change(()=>{S.settings.homeEnabled18=[...new Set([...(S.settings.homeEnabled18||[]),k])];});toggleHome18(k,value);};
const insightsMore18=insights;insights=function(){return insightsMore18()+(S.settings.design==='new'?weeklyCard()+forecastPanel():'');};
const drawChart18=drawChart;drawChart=function(){drawChart18();const labels={model:'Model',daily:'24h avg',trend:'7-day avg',average:'View average',weight:'Weight · '+unitLabel('weight'),peaks:'Peaks & troughs',planned:'Planned'};const legend=$('.chart-card .legend');if(legend)legend.innerHTML=Object.entries(labels).map(([k,n])=>`<button class="series-toggle ${$('#layer-'+k)?.checked===false?'series-off':''}" aria-pressed="${$('#layer-'+k)?.checked!==false}" onclick="toggleSeries18('${k}')">${n}</button>`).join('');if(chart&&Object.keys(labels).every(k=>$('#layer-'+k)?.checked===false)){const c=chart.canvas.getContext('2d');c.save();c.setTransform(1,0,0,1,0,0);c.clearRect(0,0,chart.canvas.width,chart.canvas.height);c.restore();$('#chart-value').textContent='Select a series to display';}};
function toggleSeries18(k){const el=$('#layer-'+k);if(!el)return;el.checked=!el.checked;chart?.draw();}
const renderMore18=render;render=function(){renderMore18();if(page==='insights'){const peaks=$('#layer-peaks');if(peaks&&!$('#layer-model'))peaks.closest('label').insertAdjacentHTML('beforebegin','<label class="check"><input id="layer-model" type="checkbox" checked onchange="chart.draw()">Model estimate</label>');chart?.draw();}if(page==='journal'&&journalFilter18==='dose'){document.querySelectorAll('.journal-entry').forEach(el=>{const id=el.id.replace('entry-',''),edit=el.querySelector('[aria-label="Edit entry"]');if(edit&&!el.querySelector('[aria-label="Delete entry"]'))edit.insertAdjacentHTML('afterend',`<button class="icon-button" aria-label="Delete entry" onclick="confirmRecord18('dose','${id}')">${trash18()}</button>`);});}};
const chartRange18=chartRange;chartRange=function(n){chartRange18(n);document.querySelectorAll('[onclick^="chartRange("]').forEach(el=>el.classList.toggle('on',el.getAttribute('onclick')==='chartRange('+n+')'));};
saveHalf=function(){try{const h=Core.positive(val('half'),'Half-life');if(change(()=>S.settings.half=h)){render();toast('Model assumption saved.');}}catch(e){formError(e);}};
const entryForm18=editEntry;editEntry=function(id){entryForm18(id);const sheet=$('#modal .sheet'),save=sheet.querySelector('button.primary');if(save)$('#form-error').insertAdjacentHTML('afterend',save.outerHTML);};
// Convert UI inputs only. Original canonical readings are never rewritten by a units toggle.
const profileForm18=editProfile;editProfile=function(){profileForm18();if(imperial())for(const [id,kind,label]of [['p-weight','weight','Current weight'],['p-target','weight','Goal weight'],['p-height','length','Height']]){const el=$('#'+id);if(el.value)el.value=displayValue(el.value,kind);el.previousElementSibling.textContent=label+' · '+unitLabel(kind);}};
const profileRead18=readProfile;readProfile=function(){const vals={};if(imperial())for(const [id,k]of [['p-weight','weight'],['p-target','weight'],['p-height','length']]){const el=$('#'+id);vals[id]=el.value;if(el.value)el.value=canonicalValue(el.value,k);}try{return profileRead18();}finally{for(const [id,value]of Object.entries(vals))$('#'+id).value=value;}};
const measurementForm18=editMeasurement;editMeasurement=function(id){measurementForm18(id);if(imperial())for(const k of ['weight','lean','muscle','bone','skeletal','fatMass','waterMass','headSize']){const el=$('#measure-'+k);if(!el)continue;const kind=k==='headSize'?'length':'weight';if(el.value)el.value=displayValue(el.value,kind);el.previousElementSibling.textContent=Core.metricNames[k].replace(/kg|cm/g,unitLabel(kind));}};
const measurementSaveUnits18=saveMeasurement;saveMeasurement=function(id){const vals={};if(!$('#measure-at'))return;if(imperial())for(const k of ['weight','lean','muscle','bone','skeletal','fatMass','waterMass','headSize']){const el=$('#measure-'+k);if(!el)continue;vals[k]=el.value;if(el.value)el.value=canonicalValue(el.value,k==='headSize'?'length':'weight');}measurementSaveUnits18(id);if($('#measure-at'))for(const[k,v]of Object.entries(vals))$('#measure-'+k).value=v;};
const circHistory18=circumferenceCard;circumferenceCard=function(){let html=circHistory18();if(imperial()){const box=document.createElement('div');box.innerHTML=html;box.querySelectorAll('p').forEach(p=>{p.textContent=p.textContent.replace(/(\d+(?:[.,]\d+)?) cm/g,(_,n)=>fmt(displayValue(Number(n.replace(',','')),'length'))+' in').replace('Optional · cm','Optional · in');});html=box.innerHTML;}return html;};
const learn18=learn;learn=function(){return learn18().replace('The app does not assign a storage life after opening or preparation.','The app can track a documented water-vial deadline; it cannot establish the stability or sterility of a preparation.')+card(`<h2>Water vial dates</h2><p>For a confirmed multidose vial, the tracker uses 28 days after first puncture unless a different manufacturer period is entered. It uses the earlier of that deadline and factory expiry. This does not establish sterility. Single-use water is not assigned a 28-day period.</p><p><a href="https://www.cdc.gov/injection-safety/hcp/clinical-safety/index.html">CDC · multidose vial guidance</a></p><h3>Gauge and compatibility</h3><p>30G, 31G and 32G describe thickness; length in mm is a separate property. These examples are not equipment recommendations. Gauge alone cannot establish compatibility: check the exact pen model, attachment and manufacturer's compatibility list.</p><h3>Your protein planning range</h3><p>The adjustable 1.6–2.2 g/kg target-weight preset is an app planning convention. It is not a universal retatrutide recommendation. Your range midpoint is its mathematical average, and the prior nutrition target remains separately saved.</p>`);};
function reportText18(r){return ['Reta Log · personal records',S.profile.name||'', 'Display: '+(imperial()?'Imperial':'Metric')+' · '+S.settings.dateOrder+' · '+S.settings.timeFormat+'h','Recorded values, not treatment recommendations.','', 'DOSES',...(r.entries||[]).map(e=>dayDate(e.at)+' '+clock(e.at)+' | '+fmt(e.mg)+' mg | '+(e.status||'taken')),'','WEIGHT · ORIGINAL RECORDS',...(r.measurements||[]).filter(m=>m.values.weight).map(m=>dayDate(m.at)+' '+clock(m.at)+' | '+weightText(m.values.weight)+' | '+(m.source||'Manual')),'','CHECK-INS',...(r.feelings||[]).map(f=>dayDate(f.at)+' '+clock(f.at)+' | '+Object.entries(f.values||{}).map(([k,v])=>k+' '+v+'/5').join(', ')+' | '+(f.note||'')),'','HYDRATION',...(r.hydration||[]).map(h=>dayDate(h.at)+' '+clock(h.at)+' | '+fmt(displayValue(h.ml,'water'))+' '+unitLabel('water')),'','PROTEIN',...(r.proteinLog||[]).map(p=>dayDate(p.at)+' '+clock(p.at)+' | '+fmt(p.grams)+' g | '+proteinSources[p.source]),'','BODY CIRCUMFERENCES',...(r.circumferences||[]).map(c=>dayDate(c.at)+' '+clock(c.at)+' | '+Object.entries(c.values).map(([k,v])=>measureNames[k]+' '+fmt(displayValue(v,'length'))+' '+unitLabel('length')).join(', ')+' | '+(c.note||''))].join('\n');}
summaryText=()=>reportText18({...reportData17(),circumferences:S.circumferences.filter(c=>Date.parse(c.at)>=reportData17().start)});
exportSummary17=function(){const text=summaryText();if(window.Native)Native.exportReport(JSON.stringify({reportTitle:'Personal records summary',reportText:text}));else saveFile('Reta-Log-summary.txt','text/plain',text);};
exportReport=function(){const text=reportText18(S);if(window.Native)Native.exportReport(JSON.stringify({reportTitle:'Complete records',reportText:text}));else saveFile('Reta-Log-report.txt','text/plain',text);};
exportBackup=function(){saveFile('Reta-Log-backup-'+Core.isoDay(Date.now())+'.json','application/json',JSON.stringify({...S,backupMetadata:{appVersion:'2.0.1',createdAt:new Date().toISOString(),timeZone:Intl.DateTimeFormat().resolvedOptions().timeZone,utcOffsetMinutes:-new Date().getTimezoneOffset(),canonicalUnits:'kg,cm,mL,g'}},null,2));};
function circumferenceTrend18(k='waist'){const rs=S.circumferences.filter(r=>r.values[k]!=null).sort((a,b)=>Date.parse(a.at)-Date.parse(b.at));const ts=rs.map(r=>Date.parse(r.at)),vs=rs.map(r=>displayValue(r.values[k],'length')),a=Math.min(...ts),b=Math.max(...ts),lo=Math.min(...vs),hi=Math.max(...vs);const points=rs.map((r,i)=>({x:25+(ts[i]-a)/(b-a||1)*260,y:105-(vs[i]-lo)/(hi-lo||1)*70,r,v:vs[i]}));modal('Circumference trend',`${select('circ-trend','Location',Object.entries(measureNames),k)}${rs.length?`<svg viewBox="0 0 310 145" class="circ-trend" role="img" aria-label="${measureNames[k]} trend in ${unitLabel('length')}"><path d="${points.map((p,i)=>(i?'L':'M')+p.x+' '+p.y).join(' ')}" fill="none" stroke="currentColor" stroke-dasharray="4 3"/>${points.map(p=>`<circle cx="${p.x}" cy="${p.y}" r="4" fill="currentColor"><title>${dayDate(p.r.at)} · ${fmt(p.v)} ${unitLabel('length')}</title></circle>`).join('')}</svg><p class="hint">Dashed line connects recorded points; missing dates are not measurements.</p>${rs.map((r,i)=>`<div class="list-item row spread"><span>${dayDate(r.at)} · ${clock(r.at)}</span><b>${fmt(vs[i])} ${unitLabel('length')}</b></div>`).join('')}`:'<p>No readings for this location.</p>'}`);$('#circ-trend').onchange=e=>circumferenceTrend18(e.target.value);}
const circTrendCard18=circumferenceCard;circumferenceCard=function(){return circTrendCard18()+(page==='insights'?button('Explore circumference trends','circumferenceTrend18()','secondary'):'');};
weightDetails=function(t){const r=Core.weightDays(S.measurements,S.settings.weightMode).find(r=>r.key===Core.dayKey(t));if(r)modal('Weight · '+dayDate(r.t),`<div class="big">${weightText(r.weight)}</div><p class="hint">${weightModeLabel()} · ${r.count} original readings</p>${r.rows.map(x=>`<div class="list-item row spread"><span>${dayDate(x.t)} · ${clock(x.t)}</span><b>${weightText(x.weight)}</b></div>`).join('')}`);};
const waterSettings18=dailySettings;dailySettings=function(){waterSettings18();if(imperial()){const el=$('#water-target');if(el.value)el.value=displayValue(el.value,'water');el.previousElementSibling.textContent='Personal drinks goal · US fl oz/day (optional)';}};
const waterSaveSettings18=saveDailySettings;saveDailySettings=function(){if(!$('#water-target'))return;const el=$('#water-target'),value=el.value;if(value&&imperial())el.value=canonicalValue(value,'water');waterSaveSettings18();if($('#water-target'))el.value=value;};
const historyUnits18=dailyHistory;dailyHistory=function(type){if(type!=='water'||!imperial())return historyUnits18(type);const box=document.createElement('div');box.innerHTML=historyUnits18(type);box.querySelectorAll('b').forEach(el=>{if(el.textContent.endsWith(' mL'))el.textContent=fmt(displayValue(Number(el.textContent.replace(/[^0-9.]/g,'')),'water'))+' US fl oz';});return box.innerHTML;};
function weightHtml18(html){if(!imperial())return html;const box=document.createElement('div');box.innerHTML=html;const walker=document.createTreeWalker(box,NodeFilter.SHOW_TEXT);let node;while(node=walker.nextNode()){if(node.parentElement.closest('script,style'))continue;node.textContent=node.textContent.replace(/(-?\d[\d,]*(?:\.\d+)?) kg\b/g,(_,n)=>weightText(Number(n.replaceAll(',',''))));}return box.innerHTML;}
const progressUnits18=progressPanel;progressPanel=()=>weightHtml18(progressUnits18());const forecastUnits18=forecastPanel;forecastPanel=()=>weightHtml18(forecastUnits18());const periodUnits18=periodRows;periodRows=rows=>weightHtml18(periodUnits18(rows));
const insightUnits18=insights;insights=function(){const box=document.createElement('div');box.innerHTML=weightHtml18(insightUnits18());const row=box.querySelector('#layer-weight')?.closest('label');if(row){for(const n of row.childNodes)if(n.nodeType===Node.TEXT_NODE)n.textContent='Measured weight · '+unitLabel('weight')+' (right axis)';}const body=box.querySelector('.weight-chart-card')?.closest('section');if(body&&imperial()){const big=body.querySelector('.big');if(big&&big.querySelector('small')?.textContent==='kg'){const w=selectedWeightRecords().at(-1);if(w)big.innerHTML=fmt(displayValue(w.values.weight,'weight'))+' <small>lb</small>';}}return box.innerHTML;};
bodyHistory=function(){modal('Body measurements',button('Add measurement','editMeasurement()')+[...S.measurements].sort((a,b)=>Date.parse(b.at)-Date.parse(a.at)).map(m=>`<div class="import-row"><div class="row spread"><b>${dayDate(m.at)} · ${clock(m.at)}</b>${button('Edit',`editMeasurement('${m.id}')`,'secondary')}</div><p class="hint">${esc(m.source||'Manual')}</p>${Object.entries(m.values).map(([k,v])=>{const kind=k==='headSize'?'length':['weight','lean','muscle','bone','skeletal','fatMass','waterMass'].includes(k)?'weight':null;return `<p>${esc(Core.metricNames[k]||k)}: <b>${k==='bodyType'?esc(v):fmt(kind?displayValue(v,kind):v)}${kind?' '+unitLabel(kind):''}</b></p>`;}).join('')}</div>`).join(''));};
let expiryTimer18;const finalRender18=render;render=function(){finalRender18();clearTimeout(expiryTimer18);if(page==='inventory'){const future=S.vials.map(v=>Core.bacExpiry(v)?.deadline).filter(t=>t>Date.now());if(future.length)expiryTimer18=setTimeout(refreshExpiry18,Math.min(2147483647,Math.max(1,Math.min(...future)-Date.now()+5)));}};
render();if(!S.onboarded&&!loadError)setTimeout(onboard,350);
