'use strict';
let doseOffset=0,weekIndex=null,inventoryReturn=null,weightChart=null;
const supplyExpanded=new Map();
const selectedWeightRecords=()=>Core.selectedWeights(S.measurements,S.settings.weightMode||'average');
const weightModeLabel=()=>S.settings.weightMode==='latest'?'Latest measurement':S.settings.weightMode==='lowest'?'Lowest weight':'Daily average';
function doseWindow(){const end=new Date();end.setHours(0,0,0,0);end.setDate(end.getDate()+1-7*doseOffset);const start=new Date(end);start.setDate(start.getDate()-7);const rows=S.entries.filter(e=>(!e.status||e.status==='taken')&&Date.parse(e.at)>=+start&&Date.parse(e.at)<+end&&Date.parse(e.at)<=Date.now());return {start,end,rows,total:rows.reduce((sum,e)=>sum+ +e.mg,0)};}
function doseWindowCard(){const d=doseWindow();return card(`<div class="orb"></div><div class="row spread"><div class="eyebrow">Recorded · ${doseOffset?'previous':'last'} 7 days</div><span class="pill">${d.rows.length} entries</span></div><div class="big">${fmt(d.total)} <small>mg</small></div><p>${date(d.start)} — ${date(+d.end-1)}</p><p class="hint">Calendar-day totals of confirmed entries.</p><canvas id="mini" style="width:100%;height:105px;touch-action:pan-y"></canvas><div class="window-controls"><button aria-label="Previous 7 days" onclick="shiftDoseWindow(1)">← Previous</button><button onclick="doseOffset=0;render()">Today</button><button aria-label="Next 7 days" ${doseOffset===0?'disabled':''} onclick="shiftDoseWindow(-1)">Next →</button></div><button class="link" onclick="navigate('insights')">Explore insights →</button>`,'hero');}
function shiftDoseWindow(n){doseOffset=Math.max(0,doseOffset+n);render();}
drawMini=function(){const ca=$('#mini');if(!ca)return;const d=doseWindow(),ratio=devicePixelRatio||1,w=ca.clientWidth,h=105;ca.width=w*ratio;ca.height=h*ratio;const c=ca.getContext('2d');c.scale(ratio,ratio);const bars=Array.from({length:7},(_,i)=>{const a=new Date(d.start);a.setDate(a.getDate()+i);const b=new Date(a);b.setDate(b.getDate()+1);return {at:a,v:d.rows.filter(e=>Date.parse(e.at)>=+a&&Date.parse(e.at)<+b).reduce((s,e)=>s+ +e.mg,0)}}),max=Math.max(1,...bars.map(b=>b.v));bars.forEach((b,i)=>{const x=i*w/7+5,bw=w/7-10,bh=Math.max(3,b.v/max*42);c.fillStyle='#82ded5';c.beginPath();c.roundRect(x,65-bh,bw,bh,4);c.fill();c.textAlign='center';c.font='11px sans-serif';c.fillStyle='#d1e4ef';c.fillText(fmt(b.v,1),x+bw/2,57-bh);c.fillText(b.at.toLocaleDateString('en-GB',{weekday:'short'}),x+bw/2,83);c.fillText(String(b.at.getDate()),x+bw/2,100);});let x=null;ca.onpointerdown=e=>x=e.clientX;ca.onpointerup=e=>{if(x!==null&&Math.abs(e.clientX-x)>45)shiftDoseWindow(e.clientX>x?1:-1);x=null;};};
function weeklyCard(){const weeks=Core.weekBuckets(S.entries);if(!weeks.length)return card('<h2>Weekly dose history</h2><p class="hint">Your first confirmed entry starts Week 1. Each week covers seven calendar days.</p>');const i=weekIndex===null?weeks.length-1:Math.min(weeks.length-1,Math.max(0,weekIndex)),w=weeks[i];return card(`<div class="row spread"><h2>Weekly dose history</h2><span class="pill">Week ${w.number}</span></div><div class="big">${fmt(w.total)} <small>mg recorded</small></div><p>${dayDate(w.start)} — ${dayDate(w.end-1)}</p>${w.entries.length?w.entries.map(e=>`<div class="list-item row spread"><span>${dayDate(e.at)} · ${clock(e.at)}</span><b>${fmt(e.mg)} mg</b></div>`).join(''):'<p class="hint">No confirmed entries in this week.</p>'}<div class="window-controls"><button ${i===0?'disabled':''} onclick="weekIndex=${i-1};render()">← Week</button><button onclick="weekIndex=null;render()">Current</button><button ${i===weeks.length-1?'disabled':''} onclick="weekIndex=${i+1};render()">Week →</button></div><p class="hint">Week 1 starts on ${dayDate(weeks[0].start)}. Recorded history, not a titration recommendation.</p>`);}
function macroTable(m){return `<div class="macro-table">${[['Protein',m.protein,m.proteinPct],['Carbohydrates',m.carbs,m.carbPct],['Fat',m.fat,m.fatPct]].map(([n,g,p])=>`<div class="row spread"><b>${n}</b><span>${fmt(g,1)} g · ${fmt(p,1)}%</span></div>`).join('')}</div><p class="hint">Protein planning range: <b>${m.min}–${m.max} g/day</b> (${m.low}–${m.high} g/kg × ${fmt(m.reference)} kg ${m.basis==='target'?'target':'current'} weight). ${m.basis==='target'?'Target-weight range is an adjustable planning convention, not a retatrutide-specific guideline.':''}</p>`;}
function nutritionCard(){try{const m=Core.macros(S.profile);return card(`<div class="row spread"><h2>Daily targets</h2><span class="pill">${S.profile.keto?'Keto':'Balanced'} · ${S.profile.macroMode==='auto'?'Auto':'Custom'}</span></div><div class="big">${m.calories}<small> kcal</small></div>${macroTable(m)}<p class="hint">Estimated maintenance ${m.maintain} kcal. Targets, not food consumed.</p><button class="link" onclick="editProfile()">Adjust nutrition →</button>`);}catch(e){return card(`<h2>Daily targets</h2><p class="hint">${esc(e.message)}</p>${button('Review profile','editProfile()','secondary')}`);}}
const editProfile15=editProfile;
editProfile=function(){editProfile15();const p=S.profile;$('#p-protein').previousElementSibling.insertAdjacentHTML('beforebegin',`<div class="nutrition-options">${select('p-mode','Target calculation',[['auto','Auto targets'],['custom','Custom grams']],p.macroMode||(!p.protein?'auto':'custom'))}${select('p-basis','Protein weight basis',[['current','Current weight'],['target','Target weight']],p.proteinBasis||'current')}<label class="check"><input id="p-resistance" type="checkbox" ${p.resistance?'checked':''}>I train for strength / resistance</label></div>`);$('#p-protein').closest('.grid2').classList.add('nutrition-grid');refreshNutritionInputs();};
readProfile=function(){const p={...S.profile,name:val('p-name').trim(),sex:val('p-sex'),age:Core.positive(val('p-age'),'Age'),height:Core.positive(val('p-height'),'Height'),weight:Core.positive(val('p-weight'),'Weight'),target:val('p-target')?Core.positive(val('p-target'),'Goal weight'):null,activity:+val('p-activity'),deficit:Core.num(val('p-deficit')),macroMode:val('p-mode'),proteinBasis:val('p-basis'),resistance:$('#p-resistance').checked,protein:Core.num(val('p-protein')),carbs:Core.num(val('p-carbs')),keto:$('#p-keto').checked};if(p.age<18||p.age>110||p.height<100||p.height>250||p.weight<30||p.weight>400)throw Error('Check your profile values. Estimates are intended for adults.');const m=Core.macros(p);p.protein=m.protein;p.carbs=m.carbs;return p;};
previewMacros=function(){try{const m=Core.macros(readProfile());$('#macro-preview').innerHTML=card(`<div class="stat">${m.calories} kcal / day</div>${macroTable(m)}<p class="hint">Keto preset: about 5% total carbohydrates, capped at 30 g; balanced preset: 45% carbohydrates. Protein is set first, and fat fills the remaining energy. Percentages adjust to your protein target.</p>`);}catch(e){formError(e);}};
function refreshNutritionInputs(){if(!$('#p-mode'))return;const auto=val('p-mode')==='auto';$('#p-protein').readOnly=auto;$('#p-carbs').readOnly=auto;try{const p=readProfile();if(auto){$('#p-protein').value=p.protein;$('#p-carbs').value=p.carbs;}$('#form-error').textContent='';previewMacros();}catch(e){$('#macro-preview').innerHTML='<p class="hint">Complete your age, height and weight to calculate targets.</p>';}}
ketoDefaults=function(){refreshNutritionInputs();};
document.addEventListener('change',e=>{if(e.target.id.startsWith('p-')&&e.target.id!=='p-name')refreshNutritionInputs();});
function stock(v){if(v.type==='water'){const total=Number(v.volume)||0,used=Number(v.usedMl)||0;return {remaining:Math.max(0,total-used),used,total,unit:'mL'};}const b=Core.supplyBalance(v,S.entries);return {...b,total:b.declared,unit:'mg'};}
const supplyType=v=>v.type==='water'?'Bacteriostatic water':v.type==='cartridge'?'Pen cartridge':'Vial';
inventory=function(){const list=[...S.vials].sort((a,b)=>Number(stock(a).remaining<=0)-Number(stock(b).remaining<=0)),mg=list.filter(v=>v.type!=='water').reduce((s,v)=>s+stock(v).remaining,0),ml=list.filter(v=>v.type==='water').reduce((s,v)=>s+stock(v).remaining,0);return header('Your supplies','A clear view of every container.')+card(`<div class="eyebrow">Available across all supplies</div><div class="stats"><div><div class="stat">${fmt(mg)} mg</div><span class="hint">Retatrutide · recorded balance</span></div><div><div class="stat">${fmt(ml)} mL</div><span class="hint">Bacteriostatic water</span></div></div>`)+button('+ Add a supply','editVial()')+list.map(v=>{const b=stock(v),open=supplyExpanded.get(v.id)??false;return `<details class="card supply-card ${b.remaining>0?'supply-available':'supply-empty'}" id="supply-${v.id}" ${open?'open':''} ontoggle="supplyExpanded.set('${v.id}',this.open)"><summary><div class="row spread"><div><h2>${esc(v.name)}</h2><span class="hint">${supplyType(v)}</span></div><div class="stock-summary"><b>${fmt(b.remaining)} ${b.unit}</b><span class="stock-badge">${b.remaining>0?'Available':'Empty'}</span></div></div></summary><div class="supply-detail">${v.type==='cartridge'?penArt():vialArt()}<div class="stat">${fmt(b.remaining)} ${b.unit} remaining</div><p class="hint">${fmt(b.used)} ${b.unit} ${v.type==='water'?'recorded as used':'logged as taken'} / ${fmt(b.total)} ${b.unit} total${b.overdrawn>0?' · Recorded use exceeds declared capacity.':''}</p>${v.type==='water'?'<p class="hint">Water use is entered manually; it is never counted as an injected retatrutide dose.</p>':supplyHistory(v)}${v.prepared?`<p class="hint">${v.type==='water'?'Opened':'Prepared'}: ${esc(v.prepared)}</p>`:''}${v.note?`<p>${esc(v.note)}</p>`:''}${button('Edit supply',`editVial('${v.id}')`,'secondary')}${button('Duplicate supply',`duplicateSupply('${v.id}')`,'secondary')}</div></details>`}).join('')+(!list.length?card('<h2>No supplies yet</h2><p>Add a vial, cartridge or water bottle.</p>'):'');};
editVial=function(id){const v=S.vials.find(v=>v.id===id)||{};modal('Supply details',`${field('v-name','Label',v.name||'')}${select('v-type','Container',[['vial','Vial · lyophilised retatrutide'],['cartridge','Pen cartridge'],['water','Bacteriostatic water vial']],v.type||'vial')}<div id="v-med-fields">${select('v-state','Current state',[['Lyophilised','Lyophilised'],['Prepared solution','Prepared solution'],['Prefilled solution','Prefilled solution']],v.state||'Lyophilised')}${field('v-mg','Declared total amount · mg',v.mg||'','number')}</div>${field('v-volume',v.type==='water'?'Total water volume · mL':'Final solution volume · mL (optional)',v.volume||'','number')}<div id="v-water-fields">${field('v-used','Water already used · mL',v.usedMl||0,'number')}</div>${field('v-prepared','Prepared / opened date (optional)',v.prepared||'','date')}${field('v-note','Notes',v.note||'')}<p class="hint">Record container information. This does not verify contents, compatibility or storage life.</p>${button('Save supply',`saveVial('${id||''}')`)}${id?button('Remove supply',`removeVial('${id}')`,'danger'):''}`);toggleWater();$('#v-type').onchange=toggleWater;};
function toggleWater(){const water=val('v-type')==='water';$('#v-med-fields').hidden=water;$('#v-water-fields').hidden=!water;document.querySelector('label[for="v-volume"]').textContent=water?'Total water volume · mL':'Final solution volume · mL (optional)';}
saveVial=function(id){try{const water=val('v-type')==='water',old=S.vials.find(v=>v.id===id);if(water&&old?.type!=='water'&&S.entries.some(e=>e.vial===id))throw Error('This supply has linked doses. Create a separate water vial instead.');const v={...old,id:id||uid(),name:val('v-name').trim(),type:val('v-type'),state:water?'Water':val('v-state'),mg:water?0:Core.positive(val('v-mg')),volume:water?Core.positive(val('v-volume'),'Water volume'):val('v-volume')?Core.positive(val('v-volume')):null,usedMl:water?Core.num(val('v-used')):0,prepared:val('v-prepared'),openedAt:$('#v-opened')?.value||'',note:val('v-note')};if(!v.name)throw Error('Give the supply a label.');if(!Number.isFinite(v.usedMl)||v.usedMl<0||(water&&v.usedMl>v.volume))throw Error('Water used must be between zero and total volume.');if(change(()=>{S.vials=S.vials.filter(v=>v.id!==id);S.vials.push(v)},true)){supplyExpanded.set(v.id,false);closeModal();render();toast('Supply saved.',true);}}catch(e){formError(e);}};
function duplicateSupply(id){const v=S.vials.find(v=>v.id===id);if(!v)return;editVial();$('#v-name').value=v.name+' · copy';$('#v-type').value=v.type;$('#v-state').value=v.state||'Lyophilised';$('#v-mg').value=v.mg||'';$('#v-volume').value=v.volume||'';$('#v-used').value=0;$('#v-note').value=v.note||'';toggleWater();$('#form-error').insertAdjacentHTML('afterend','<p class="hint">New container: capacity copied, history empty, dates reset. Review and save.</p>');}
openSupply=function(id,entryId){if(!S.vials.some(v=>v.id===id)){toast('This supply is no longer available.');return;}inventoryReturn=page==='journal'?{entryId,y:scrollY}:null;supplyExpanded.set(id,true);navigate('inventory');requestAnimationFrame(()=>{const el=document.getElementById('supply-'+id);if(el){el.open=true;el.classList.add('supply-focused');el.setAttribute('tabindex','-1');el.scrollIntoView({block:'start'});el.focus({preventScroll:true});}});};
function goBack(){if($('#modal').innerHTML){closeModal();return;}if(document.body.classList.contains('full-chart')){toggleFull();return;}if(document.body.classList.contains('full-weight')){toggleWeightFull();return;}if(page==='inventory'&&inventoryReturn){const back=inventoryReturn;inventoryReturn=null;navigate('journal');requestAnimationFrame(()=>{window.scrollTo(0,back.y);const el=document.getElementById('entry-'+back.entryId);if(el){el.classList.add('supply-focused');el.setAttribute('tabindex','-1');el.focus({preventScroll:true});}});return;}inventoryReturn=null;navigate('overview');}
const originalNav16=navigate;navigate=function(p){document.body.classList.remove('full-weight');if(p!=='inventory')inventoryReturn=null;weightChart=null;originalNav16(p);};
const originalHeader16=header;header=function(title,sub){return (page==='inventory'&&inventoryReturn?'<button class="small-button" onclick="goBack()">← Back to journal entry</button>':'')+originalHeader16(title,sub);};
// Visual location log: all selection targets sit below the chest on the abdomen.
torsoArt=function(selected='',interactive=false){const female=S.profile.sex==='female',outline=female?'M123 22Q90 27 80 54L66 139L88 145L106 86Q108 114 121 135Q127 151 111 181L101 232Q140 246 180 246Q220 246 259 232L249 181Q233 151 239 135Q252 114 254 86L272 145L294 139L280 54Q270 27 237 22L215 35H145Z':'M122 22Q87 23 75 54L59 140L83 148L106 86L113 167L103 234Q143 245 180 245Q217 245 257 234L247 167L254 86L277 148L301 140L285 54Q273 23 238 22L215 35H145Z';const points=[['right-upper',137,149],['left-upper',223,149],['right-middle',133,177],['left-middle',227,177],['right-lower',140,206],['left-lower',220,206]];return svg(`<defs><linearGradient id="body-skin"><stop stop-color="#b99684"/><stop offset=".5" stop-color="#e8c5ac"/><stop offset="1" stop-color="#b99684"/></linearGradient></defs><path d="${outline}" fill="url(#body-skin)"/><path d="${female?'M110 76Q133 60 161 79L180 88L199 79Q227 60 250 76L242 115Q218 131 190 110H170Q142 131 118 115Z':'M110 77Q142 92 173 82M187 82Q218 92 250 77'}" fill="${female?'#38566b':'none'}" stroke="#987b6b" stroke-width="2"/><path d="M107 223Q180 209 253 223L257 242H103Z" fill="#38566b"/><path d="M176 178q4 5 8 0" fill="none" stroke="#987b6b" stroke-width="2"/><ellipse cx="180" cy="178" rx="23" ry="27" fill="none" stroke="#987b6b" stroke-dasharray="3 4"/>${points.map(([id,x,y])=>`<g ${interactive?`onclick="chooseSite('${id}')" onkeydown="if(event.key==='Enter')chooseSite('${id}')" role="button" tabindex="0" aria-label="${id} abdomen"`:''}><circle cx="${x}" cy="${y}" r="13" fill="transparent"/><circle cx="${x}" cy="${y}" r="${selected===id?10:7}" fill="${selected===id?'#087e88':'white'}" stroke="#087e88" stroke-width="2"/></g>`).join('')}<text x="72" y="265" font-size="13" fill="currentColor">YOUR RIGHT</text><text x="220" y="265" font-size="13" fill="currentColor">YOUR LEFT</text>`,'0 0 360 285',`${female?'Female':'Male'} abdominal location log. Schematic, not an injection guide.`);};
function weightChartMarkup(){return `<div class="weight-chart-card"><div class="chart-controls"><span id="weight-range" class="hint"></span><div><button aria-label="Zoom weight in" onclick="zoomWeight(1.6)">+</button><button aria-label="Zoom weight out" onclick="zoomWeight(1/1.6)">−</button><button aria-label="Full weight chart" onclick="toggleWeightFull()"><svg class="icon" viewBox="0 0 24 24"><path d="M8 3H3v5m13-5h5v5M3 16v5h5m13-5v5h-5"/></svg></button></div></div><div class="chipbar"><button onclick="weightRange(30)">30D</button><button onclick="weightRange(90)">90D</button><button onclick="weightRange(0)">All</button><button onclick="weightRange(7)">7D</button></div><canvas id="weight-chart" style="width:100%;height:260px;touch-action:none"></canvas><div id="weight-value" class="chart-value">Tap a dot · drag to pan · pinch to zoom</div><label for="weight-mode-inline">Multiple weigh-ins on one day</label><select id="weight-mode-inline" onchange="setWeightMode(this.value)"><option value="average" ${(S.settings.weightMode||'average')==='average'?'selected':''}>Daily average</option><option value="latest" ${S.settings.weightMode==='latest'?'selected':''}>Latest measurement only</option></select><p class="hint">${weightModeLabel()} per day. Missing days have no point. This choice also applies to the main chart, weight statistics and goal forecast.</p></div>`;}
function setWeightMode(value){if(!['average','latest'].includes(value))return;setSetting('weightMode',value);}
function setupWeightChart(){const ca=$('#weight-chart');if(!ca)return;const rows=Core.weightDays(S.measurements,S.settings.weightMode);const b=Date.now()+Core.DAY,a=rows.length?Math.min(rows[0].t-Core.DAY,b-7*Core.DAY):b-30*Core.DAY;weightChart={ca,a,b,picked:null,pointers:new Map(),draw:drawWeight};let lastX=0,dist=0,startX=0,moved=false;ca.onpointerdown=e=>{ca.setPointerCapture(e.pointerId);weightChart.pointers.set(e.pointerId,e.clientX);startX=e.clientX;lastX=e.clientX;moved=false;if(weightChart.pointers.size===2){const p=[...weightChart.pointers.values()];dist=Math.abs(p[1]-p[0]);}};ca.onpointermove=e=>{const ch=weightChart;if(!ch||!ch.pointers.has(e.pointerId))return;ch.pointers.set(e.pointerId,e.clientX);if(ch.pointers.size===2){const p=[...ch.pointers.values()],d=Math.abs(p[1]-p[0]);if(d>8&&dist>8)zoomWeight(d/dist);dist=d;moved=true;}else{if(Math.abs(e.clientX-startX)>4)moved=true;const dx=(e.clientX-lastX)/(ca.clientWidth-70)*(ch.b-ch.a);ch.a-=dx;ch.b-=dx;lastX=e.clientX;ch.draw();}};ca.onpointerup=e=>{const ch=weightChart;if(!ch)return;if(!moved){const x=e.clientX-ca.getBoundingClientRect().left,nearest=(ch.points||[]).reduce((best,r)=>!best||Math.abs(r.x-x)<Math.abs(best.x-x)?r:best,null);ch.picked=nearest?.key||null;if(nearest&&window.Native)Native.haptic();}ch.pointers.delete(e.pointerId);if(ch.pointers.size)lastX=[...ch.pointers.values()][0];ch.draw();};ca.onpointercancel=e=>weightChart?.pointers.delete(e.pointerId);ca.onwheel=e=>{e.preventDefault();zoomWeight(e.deltaY<0?1.2:1/1.2)};ca.ondblclick=()=>{const row=weightChart.points?.find(r=>r.key===weightChart.picked);if(row)weightDetails(row.t);};weightChart.draw();}
function zoomWeight(f){if(!weightChart)return;const ch=weightChart,mid=(ch.a+ch.b)/2,span=Math.max(Core.DAY,Math.min(15*365*Core.DAY,(ch.b-ch.a)/f));ch.a=mid-span/2;ch.b=mid+span/2;ch.draw();}
function weightRange(days){if(!weightChart)return;const rows=Core.weightDays(S.measurements,S.settings.weightMode);weightChart.b=Date.now()+Core.DAY;weightChart.a=days?weightChart.b-days*Core.DAY:Math.min(Date.now()-7*Core.DAY,...rows.map(r=>r.t))-Core.DAY;weightChart.draw();}
function toggleWeightFull(){document.body.classList.toggle('full-weight');requestAnimationFrame(()=>weightChart?.draw());}
function drawWeight(){const ch=weightChart;if(!ch||!$('#weight-chart'))return;const ca=ch.ca,w=ca.clientWidth,h=ca.clientHeight||260,d=devicePixelRatio||1;ca.width=w*d;ca.height=h*d;const c=ca.getContext('2d');c.scale(d,d);const rows=Core.weightDays(S.measurements,S.settings.weightMode).filter(r=>r.t>=ch.a&&r.t<=ch.b),lo=rows.length?Math.floor(Math.min(...rows.map(r=>r.weight))-1):0,hi=rows.length?Math.ceil(Math.max(...rows.map(r=>r.weight))+1):100,X=t=>48+(t-ch.a)/(ch.b-ch.a)*(w-70),Y=v=>h-48-(v-lo)/(hi-lo)*(h-80),surface=ca.closest('.card')||document.body,styles=getComputedStyle(surface),ink=styles.getPropertyValue('--muted').trim(),accent=styles.getPropertyValue('--accent-readable').trim()||'#78ddd5',line=styles.getPropertyValue('--line').trim();ch.points=rows.map(r=>({...r,x:X(r.t)}));c.font='12px sans-serif';c.fillStyle=ink;c.fillText(unitLabel('weight'),8,16);for(let i=0;i<=4;i++){const value=lo+(hi-lo)*i/4,y=Y(value);c.strokeStyle=line;c.beginPath();c.moveTo(48,y);c.lineTo(w-22,y);c.stroke();c.fillStyle=ink;c.textAlign='right';c.fillText(fmt(displayValue(value,'weight'),1),41,y+4);}const ticks=w<500?3:5;for(let i=0;i<ticks;i++){const t=ch.a+(ch.b-ch.a)*i/(ticks-1),dt=new Date(t);c.textAlign=i===0?'left':i===ticks-1?'right':'center';c.fillText(date(dt),X(t),h-25);c.fillText(String(dt.getFullYear()),X(t),h-9);}$('#weight-range').textContent=date(ch.a)+' — '+date(ch.b);c.strokeStyle=accent;c.lineWidth=2;c.beginPath();rows.forEach((r,i)=>i?c.lineTo(X(r.t),Y(r.weight)):c.moveTo(X(r.t),Y(r.weight)));c.stroke();const boxes=[];const ordered=[...rows].sort((a,b)=>Number(b.key===ch.picked)-Number(a.key===ch.picked));ordered.forEach(r=>{const x=X(r.t),y=Y(r.weight);c.fillStyle=accent;c.beginPath();c.arc(x,y,r.key===ch.picked?6:4,0,7);c.fill();const text=weightText(r.weight),tw=c.measureText(text).width+8,bx=Math.max(48,Math.min(w-22-tw,x-tw/2));const by=[y-24,y+9,y-44].find(v=>v>18&&v+18<h-48&&!boxes.some(b=>bx<b.x+b.w+3&&bx+tw+3>b.x&&v<b.y+20&&v+20>b.y));if(by!==undefined){boxes.push({x:bx,y:by,w:tw});c.fillStyle=styles.getPropertyValue('--card').trim();c.fillRect(bx,by,tw,18);c.fillStyle=accent;c.textAlign='center';c.fillText(text,bx+tw/2,by+13);}});const chosen=rows.find(r=>r.key===ch.picked);$('#weight-value').innerHTML=chosen?`<b>${date(chosen.t)} · ${weightText(chosen.weight)}</b><br>${weightModeLabel()} · ${chosen.count} recorded ${chosen.count===1?'reading':'readings'}<button class="link" onclick="weightDetails(${chosen.t})">See timestamps & readings →</button>`:'Tap a dot · drag to pan · pinch to zoom';}
window.addEventListener('resize',()=>requestAnimationFrame(()=>weightChart?.draw()));
weightDetails=function(t){const row=Core.weightDays(S.measurements,S.settings.weightMode).find(r=>r.key===Core.dayKey(t));if(!row)return;modal('Weight · '+date(row.t),`<div class="big">${fmt(row.weight)} <small>kg</small></div><p class="hint">${weightModeLabel()} · ${row.count} recorded readings</p>${row.rows.map(r=>`<div class="list-item row spread"><span>${date(r.t)} · ${clock(r.t)}</span><b>${fmt(r.weight)} kg</b></div>`).join('')}`);};
const settings15=settings;
settings=function(){return settings15()+card(`<h2>Weight records</h2>${select('weight-choice','When a day has several weigh-ins',[['average','Daily average'],['latest','Latest measurement only']],S.settings.weightMode||'average')}${button('Save weight preference',"setWeightMode(val('weight-choice'))",'secondary')}`);};
const accentOptions=[['#087e88','Ocean'],['#247957','Emerald'],['#7858aa','Violet'],['#566474','Graphite'],['#44ccff','Sky blue'],['#96ff40','Fresh green'],['#ffee44','Golden yellow']];
function readableAccent(color,bg){let c=color==='#ffee44'&&Core.luminance(bg)>.4?'#8a6200':color;for(let i=0;i<30&&Core.contrast(c,bg)<4.8;i++){const light=Core.luminance(bg)<.4;c='#'+[1,3,5].map(j=>{const v=parseInt(c.slice(j,j+2),16);return Math.round(light?v+(255-v)*.12:v*.88).toString(16).padStart(2,'0')}).join('');}return c;}
function accentPalette(){const bg=getComputedStyle(document.body).getPropertyValue('--card').trim();return '<div class="accent-palette">'+accentOptions.map(([c,n])=>`<button class="swatch ${S.settings.color===c?'selected':''}" style="background:${readableAccent(c,bg)}" aria-label="${n}" aria-pressed="${S.settings.color===c}" onclick="setSetting('color','${c}')"></button>`).join('')+'</div>';}
applyTheme=function(){const root=document.documentElement,t=S.settings.theme,dark=['dark','midnight','forest'].includes(t)||(t==='system'&&matchMedia('(prefers-color-scheme:dark)').matches);document.body.classList.toggle('dark',dark);document.body.dataset.theme=t;document.body.style.backgroundColor='';document.body.style.color='';delete S.settings.background;const style=getComputedStyle(document.body),bg=style.getPropertyValue('--card').trim(),base=accentOptions.some(([c])=>c===S.settings.color)?S.settings.color:'#087e88',accent=readableAccent(base,bg);root.style.setProperty('--accent',accent);root.style.setProperty('--accent-readable',accent);root.style.setProperty('--accent-ink',Core.inkFor(accent));root.style.setProperty('--page-ink',style.getPropertyValue('--ink').trim());if(window.Native)Native.setBars(dark);};

const reminderEdit15=editReminder;
editReminder=function(id){reminderEdit15(id);const r=S.reminders.find(r=>r.id===id)||{};$('#r-enabled').closest('label').insertAdjacentHTML('beforebegin',`${select('r-end-mode','Repeat until',[['never','No end date'],['date','A specific date']],r.until?'date':'never')}<div id="r-end-wrap">${field('r-until','Last reminder date (inclusive)',r.until||'','date')}</div>`);const sync=()=>$('#r-end-wrap').hidden=val('r-end-mode')==='never';$('#r-end-mode').onchange=sync;sync();};
saveReminder=function(id){try{const days=[0,1,2,3,4,5,6].filter(d=>$('#r-day-'+d).checked),until=val('r-end-mode')==='date'?val('r-until'):null;if(!days.length||!val('r-time'))throw Error('Choose a time and at least one weekday.');if(val('r-end-mode')==='date'&&!until)throw Error('Choose an end date.');if(until&&until<local().slice(0,10))throw Error('Choose today or a future end date.');const r={id:id||uid(),label:val('r-label')||'Personal reminder',time:val('r-time'),days,until,enabled:$('#r-enabled').checked};if(change(()=>{S.reminders=S.reminders.filter(r=>r.id!==id);S.reminders.push(r)})){if(window.Native)Native.scheduleReminders(JSON.stringify(S.reminders));closeModal();render();toast('Reminder saved.');}}catch(e){formError(e);}};
reminders=function(){return header('A gentle reminder.','Your schedule, with a clear finish date.')+button('+ Create reminder','editReminder()')+S.reminders.map(r=>card(`<div class="row spread"><h2>${esc(r.label)}</h2><span class="pill">${r.until&&r.until<local().slice(0,10)?'Ended':r.enabled?'Active':'Off'}</span></div><p>${esc(r.time)} · ${r.days.map(d=>['Sun','Mon','Tue','Wed','Thu','Fri','Sat'][d]).join(', ')}</p><p>${r.until?'Repeats through '+date(r.until+'T12:00:00'):'No end date'}</p>${button('Edit reminder',`editReminder('${r.id}')`,'secondary')}`)).join('')+card('<p class="hint">Private notifications contain no substance or dose. Android battery settings can delay delivery.</p>');};
const learn15=learn;
learn=function(){return header('Understand your tools.','Equipment, nutrition and your personal records.')+card(`<h2>Vial · cartridge · pen</h2><img src="equipment.png" alt="AI-generated illustration of a vial, pen cartridge and reusable pen" class="equipment-photo"><p class="hint">Illustrative AI-generated product image. Left: vial. Centre: cartridge. Right: pen. Not to scale and not a compatibility reference.</p><p>A reusable pen holds a cartridge; 3 mL is a common cartridge capacity. Some systems use professionally filled cartridges; others accept only their manufacturer's sealed, prefilled product.</p><p class="hint">An empty cartridge being sold as refillable does not establish that it is suitable for your pen or preparation. Self-filling is only appropriate where the device and preparation instructions explicitly allow it. Never refill a cartridge labelled non-refillable. Physical fit alone does not establish compatibility.</p><p class="hint">The app records cartridge contents; it does not provide a filling or sterilisation procedure.</p>`)+card(`<h2>Keep muscle in the picture</h2><p>Weight loss can include lean tissue as well as fat. Adequate protein and resistance training help support muscle retention; protein alone cannot guarantee it.</p><p>Protein stays a separate target in both keto and balanced mode. Current-weight planning uses 1.2–1.6 g/kg/day, or 1.4–2.0 g/kg/day when strength training is selected. The target-weight option uses an editable 1.5–2.2 g/kg planning range; it is not a validated retatrutide-specific recommendation.</p><p class="hint">The upper figure is the top of a planning range, not a universal safe maximum. Body size, activity, calorie intake and medical conditions can change requirements. A target-weight calculation is an approximation, not an automatically determined ideal weight.</p><p>Auto mode estimates energy from your age, height, weight and activity. It sets protein first, then carbohydrates and remaining fat. Keto does not reduce the protein target.</p><p class="hint">Balanced preset starts with 45% carbohydrate energy. Keto starts near 5% total carbohydrates, up to 30 g. These are editable app presets, not a guarantee of ketosis. Percentages shift with protein needs.</p>${button('Set nutrition targets','editProfile()','secondary')}<p class="sources hint"><a href="https://link.springer.com/article/10.1186/s12970-017-0177-8">ISSN: protein and exercise</a> · <a href="https://pubmed.ncbi.nlm.nih.gov/?term=Nutritional+priorities+to+support+GLP-1+therapy+for+obesity">Joint GLP-1 nutrition advisory</a></p>`)+learn15().replace(/^.*?(?=<section class="card)/s,'');};
const insights16=insights;
insights=function(){let html=insights16();if(S.settings.weightMode==='latest')html=html.replaceAll('daily average','latest measurement').replaceAll('daily averages','latest daily measurements').replaceAll("that calendar day's average","that calendar day's latest measurement");return html;};
const drawChart16=drawChart;drawChart=function(){drawChart16();const el=$('#chart-value');if(el&&S.settings.weightMode==='latest')el.textContent=el.textContent.replace(/daily average, (\d+) readings/g,'latest of $1 readings');};
function dayDate(t){return new Date(t).toLocaleDateString('en-GB',{weekday:'short',day:'numeric',month:'short',year:'numeric'});}
const expandedEntries=new Set();
function toggleJournalAll(open){document.querySelectorAll('.journal-details').forEach(el=>{el.open=open;const id=el.dataset.entry;if(open)expandedEntries.add(id);else expandedEntries.delete(id);});}
const journal16=journal;
journal=function(){const box=document.createElement('div');box.innerHTML=journal16();const cards=box.querySelectorAll('.journal-entry');if(cards.length){const controls=document.createElement('div');controls.className='journal-controls';controls.innerHTML='<button class="small-button" onclick="toggleJournalAll(true)">Open all</button><button class="small-button" onclick="toggleJournalAll(false)">Close all</button>';cards[0].before(controls);}cards.forEach(el=>{const id=el.id.slice(6),header=el.querySelector('.entry'),edit=header.querySelector('.edit'),details=document.createElement('details'),summary=document.createElement('summary');details.className='journal-details';details.dataset.entry=id;if(expandedEntries.has(id))details.open=true;details.setAttribute('ontoggle',"if(this.open)expandedEntries.add(this.dataset.entry);else expandedEntries.delete(this.dataset.entry)");edit.remove();summary.append(header);details.append(summary);while(el.firstChild)details.append(el.firstChild);const actions=document.createElement('div');actions.className='journal-edit';actions.append(edit);el.append(details,actions);});return box.innerHTML;};
const feeling16=editFeeling;
editFeeling=function(){feeling16();const input=$('#feeling-at'),hint=document.createElement('p');hint.className='hint';hint.id='feeling-day';input.after(hint);const update=()=>hint.textContent=input.value?dayDate(input.value):'';input.addEventListener('input',update);update();};
// Boot is owned by app17.js.

const applyTheme174=applyTheme;applyTheme=function(){applyTheme174();const base=accentOptions.some(([c])=>c===S.settings.color)?S.settings.color:'#087e88',cardAccent=readableAccent(base,'#233e57');document.documentElement.style.setProperty('--card-accent',cardAccent);document.documentElement.style.setProperty('--card-accent-ink',Core.inkFor(cardAccent));};
