'use strict';
/* UX V2 adapters. All legacy renderers, forms, transactions and charts remain delegates. */
const legacy20={overview,journal,insights,inventory,profile,settings,learn,calculator,dataPage,render,navigate,goBack,quickLog,openWeight,setupChart,setupWeightChart,drawWeight,header,reportText18};
const v2=()=>S.settings.design==='new';
window.retaV2SupplyRefresh=()=>!v2()||ui20.supplies==='inventory';
const switchBefore20=designSwitch;
designSwitch=function(value){if(!value&&v2()&&page==='profile'&&ui20.you==='settings')page='settings';stack20=[];switchBefore20(value);};
const ui20={progress:'overview',supplies:'inventory',you:'goals',filter:'all',day:'',period:7,metric:'fat'};
let rendered20='',stack20=[],restoring20=false;
const charts20={},scroll20={};
const extra20=kind=>S.uxV2?.[kind]||[];
const routeKey20=()=>page+':'+(page==='insights'?ui20.progress:page==='inventory'?ui20.supplies:page==='profile'?ui20.you:'');
const routes20=[['overview','home','Today'],['journal','journal','Journal'],['insights','chart','Progress'],['inventory','box','Supplies'],['profile','user','You']];
const sections20={progress:['overview','body','reta','nutrition','activity'],supplies:['inventory','calculator','learn'],you:['goals','health data','connections','settings']};
const title20=s=>s.split(' ').map(w=>w[0].toUpperCase()+w.slice(1)).join(' ');
function strip20(html){const d=document.createElement('div');d.innerHTML=html;[...d.children].forEach(e=>{if(e.matches('.brand,h1')||(e.matches('p.muted')&&!e.previousElementSibling?.matches('section')))e.remove();});return d.innerHTML;}
function tabs20(group){return `<div class="v2-tabs" role="tablist" aria-label="${title20(group)} sections">${sections20[group].map(k=>`<button role="tab" aria-selected="${ui20[group]===k}" class="${ui20[group]===k?'on':''}" onclick="tab20('${group}','${k}')">${k==='reta'?'Reta':title20(k)}</button>`).join('')}</div>`;}
function heading20(title,sub){return `<div class="v2-heading"><div><div class="eyebrow">RETA LOG</div><h1>${title}</h1></div><button class="round" aria-label="App settings" onclick="go20('profile','settings')">${icon('settings')}</button></div><p class="muted v2-subtitle">${sub}</p>`;}
function remember20(){if(!v2()||!rendered20)return;scroll20[rendered20]=scrollY;if(chart?.canvas?.isConnected){charts20[rendered20]={...(charts20[rendered20]||{}),start:chart.start,end:chart.end,picked:chart.picked,layers:Object.fromEntries([...document.querySelectorAll('[id^="layer-"]')].map(e=>[e.id,e.checked]))};}if(weightChart?.ca?.isConnected){charts20[rendered20]={...(charts20[rendered20]||{}),a:weightChart.a,b:weightChart.b,weightPicked:weightChart.picked};}}
function tab20(group,tab){if(!sections20[group].includes(tab))return;remember20();stack20.push({page,ui:{...ui20},y:scrollY});ui20[group]=tab;closeModal();document.body.classList.remove('full-chart','full-weight');NativeImmersive18();render();window.scrollTo(0,scroll20[routeKey20()]||0);}
function go20(destination,tab){if(!v2())return legacy20.navigate(destination);remember20();if(!restoring20)stack20.push({page,ui:{...ui20},y:scrollY});if(destination==='insights'&&page!=='insights'){for(const k of Object.keys(charts20))if(k.startsWith('insights:'))delete charts20[k];}if(tab){if(destination==='insights')ui20.progress=tab;if(destination==='inventory')ui20.supplies=tab;if(destination==='profile')ui20.you=tab;}const previous=returning17;returning17=true;try{legacy20.navigate(destination);}finally{returning17=previous;}}
navigate=function(p){if(!v2())return legacy20.navigate(p);const aliases={calculator:['inventory','calculator'],learn:['inventory','learn'],settings:['profile','settings'],data:['profile','connections'],wellness:['journal',null]};if(aliases[p])return go20(...aliases[p]);if(p==='inventory')return go20(p,'inventory');return go20(p);};
goBack=function(){if(!v2())return legacy20.goBack();if($('#modal').innerHTML){closeModal();return;}if(document.body.classList.contains('full-chart')){toggleFull();return;}if(document.body.classList.contains('full-weight')){toggleWeightFull();return;}const prev=stack20.pop();if(prev){remember20();Object.assign(ui20,prev.ui);restoring20=true;try{go20(prev.page);}finally{restoring20=false;}window.scrollTo(0,prev.y);return;}restoring20=true;try{go20('overview');}finally{restoring20=false;}};
openWeight=function(){if(!v2())return legacy20.openWeight();go20('insights','body');};
function quickAdd20(){dailyDay=page==='journal'&&ui20.day?ui20.day:Core.isoDay(Date.now());modal('Quick Add',`<p class="hint">Choose what you want to record.</p><div class="v2-add-grid">${[['syringe','Log Injection','editEntry()'],['chart','Weight','editMeasurement()'],['food','Protein / Meal',"editDaily('protein')"],['water','Water',"editDaily('water')"],['user','Check-in','editFeeling()'],['activity','Workout / Activity',"editExtra20('activity')"],['body','Body Measurement','editCircumferences()'],['note','Note',"editExtra20('notes')"]].map(([i,n,a])=>button(icon(i)+'<span>'+n+'</span>',`newRecord20('${i}')`,'secondary')).join('')}</div>${quickExtras20()}`);}
quickLog=function(){return v2()?quickAdd20():legacy20.quickLog();};
const iconBefore20=icon;icon=function(k){const shapes={activity:'<path d="M3 13h4l3-8 4 14 3-6h4"/>',note:'<path d="M5 3h14v18H5zM8 8h8M8 12h8M8 16h5"/>',body:'<circle cx="12" cy="5" r="2"/><path d="M5 9h14M12 7v8m0 0-5 6m5-6 5 6"/>'};return shapes[k]?`<svg class="icon" viewBox="0 0 24 24" aria-hidden="true">${shapes[k]}</svg>`:iconBefore20(k);};
function spark20(values,label){if(!values.length)return `<p class="hint">No recorded trend yet</p>`;const lo=Math.min(...values.map(p=>p.v)),hi=Math.max(...values.map(p=>p.v)),a=values[0].t,b=values.at(-1).t;const points=values.map(p=>({x:5+190*(p.t-a)/(b-a||1),y:49-42*(p.v-lo)/(hi-lo||1),...p}));return `<svg class="v2-spark" viewBox="0 0 200 56" role="img" aria-label="${esc(label)}"><path d="${points.map((p,i)=>(i?'L':'M')+p.x.toFixed(1)+' '+p.y.toFixed(1)).join(' ')}" fill="none" stroke="currentColor" stroke-width="2" ${label.includes('Model')?'':'stroke-dasharray="3 3"'}/>${points.map(p=>`<circle cx="${p.x}" cy="${p.y}" r="2.5" fill="currentColor"><title>${esc(dayDate(p.t))} · ${fmt(p.v)}</title></circle>`).join('')}</svg>`;}
function planned20(){return S.entries.filter(e=>e.status==='planned'&&Date.parse(e.at)>=Date.now()).sort((a,b)=>Date.parse(a.at)-Date.parse(b.at))[0];}
function target20(kind){const water=kind==='water',total=Core.dayTotals(S,Core.isoDay(Date.now()))[water?'water':'protein'],r=water?{min:+S.settings.waterTarget,max:+S.settings.waterTarget}:Core.proteinRange(S.profile),p=r?.min?Core.targetProgress(total,r.min,r.max):null,show=n=>fmt(water?displayValue(n,'water'):n,0),unit=water?unitLabel('water'):'g';return card(`<div class="row">${icon(water?'water':'food')}<h3>${water?'Hydration':'Protein'}</h3></div><div class="stat status-${p?.color||'unset'}">${show(total)} <small>${unit}</small></div><p class="hint">${p?'Target '+show(p.min)+(p.max!==p.min?'–'+show(p.max):'')+' '+unit:'No target set'}</p>${p?`<progress max="100" value="${p.fill}" aria-label="${water?'Hydration':'Protein'} daily progress"></progress><p class="hint">${fmt(p.percent,0)}% · ${show(p.remaining)} ${unit} remaining</p>`:''}${button('+ '+(water?'Water':'Protein'),`editDaily('${kind}')`,'secondary')}`,'v2-target');}
function today20(){const now=Date.now(),w=latestWeight(),p=Core.progress(S.entries,selectedWeightRecords()),ds=Core.doses(S.entries),next=planned20(),last=ds.at(-1),weights=Core.weightDays(S.measurements,S.settings.weightMode).filter(r=>r.t>=now-7*Core.DAY),amount=Core.amount(ds,now,S.settings.half),totals=Core.dayTotals(S,Core.isoDay(now)),range=Core.proteinRange(S.profile),acts=extra20('activity').filter(r=>Core.isoDay(r.at)===Core.isoDay(now)),minutes=acts.reduce((s,r)=>s+(r.minutes||0),0),steps=acts.reduce((s,r)=>s+(r.steps||0),0),plan=[];
 if(next)plan.push([`${dayDate(next.at)} · ${clock(next.at)}`,`Planned injection · ${fmt(next.mg)} mg`,`editEntry('${next.id}')`]);
 if(range&&totals.protein<range.min)plan.push(['Protein',`${fmt(range.min-totals.protein,0)} g to minimum target`,"editDaily('protein')"]);
 if(S.settings.waterTarget>totals.water)plan.push(['Hydration',`${fmt(displayValue(S.settings.waterTarget-totals.water,'water'),0)} ${unitLabel('water')} to target`,"editDaily('water')"]);
 if(!S.feelings.some(r=>Core.isoDay(r.at)===Core.isoDay(now)))plan.push(['Check-in','How do you feel today?','editFeeling()']);
 if(!w||Core.isoDay(w.at)!==Core.isoDay(now))plan.push(['Weight','No weight recorded today','editMeasurement()']);
 for(const v of S.vials){if(v.discardedAt)continue;const x=Core.bacExpiry(v),b=stock(v),limit=v.type==='water'?S.settings.lowMl:S.settings.lowMg??3;if(x&&['expired','soon','unknown'].includes(x.state))plan.push(['BAC water',esc(v.name)+' · '+(x.expired?'Expired':x.state==='soon'?'Approaching configured limit':'Opening information needed'),`openSupply('${v.id}')`]);else if(limit!=null&&b.remaining<=limit)plan.push(['Supply '+(b.remaining?'low':'empty'),esc(v.name)+' · '+fmt(b.remaining)+' '+b.unit,`openSupply('${v.id}')`]);}
 return heading20(S.profile.name?'Hello, '+esc(S.profile.name.split(' ')[0]):'Today',dayDate(now)+(p.days?' · '+p.days+' days since first recorded injection':''))+card(`<div class="row spread"><div class="eyebrow">Current Weight</div>${button(icon('arrow'),"go20('insights','body')",'icon-button')}</div><div class="big">${w?weightText(w.values.weight):'—'}</div><div class="v2-weight-row"><p>${p.weightChange!==null?(p.weightChange>0?'+':'')+weightText(p.weightChange)+'<br><span class="hint">Since journey baseline</span>':'<span class="hint">Add weight to start your trend</span>'}</p>${spark20(weights.map(r=>({t:r.t,v:r.weight})),'Recorded weight, last seven days')}</div><p class="hint">${w?dayDate(w.at)+' · '+clock(w.at)+' · '+esc(w.source||'Manual'):'No measurement recorded'}</p>`,'v2-weight-hero')+card(`<div class="row spread"><div class="eyebrow">Reta · Model estimate</div><span class="badge">ESTIMATED</span></div><div class="v2-weight-row"><div><div class="stat">${ds.length?fmt(amount)+' mg':'—'}</div><p class="hint">${last?'Last taken: '+fmt(last.mg)+' mg':'No taken injections'}</p></div>${ds.length?spark20(Array.from({length:25},(_,i)=>{const t=now-6*Core.DAY+i*Core.DAY/4;return{t,v:Core.amount(ds,t,S.settings.half)};}),'Model estimate, past six days'):''}</div><p class="hint">${next?'Next planned: '+dayDate(next.at)+' · '+fmt(next.mg)+' mg':'No next injection planned'}</p><button class="link" onclick="go20('insights','reta')">Explore model →</button><p class="hint v2-footnote">Mathematical estimate, not a measured blood concentration.</p>`,'v2-reta-hero')+`<div class="v2-pair">${target20('protein')}${target20('water')}</div>`+card(`<div class="row spread"><h3 class="row">${icon('activity')} Activity</h3><button class="link" onclick="editExtra20('activity')">+ Record</button></div><p>${acts.length?`${acts.length} activities · ${fmt(minutes,0)} min · ${fmt(steps,0)} steps`:'No activity recorded today'}</p>`)+card(`<h2>Today's Plan</h2>${plan.length?plan.map(([t,s,a])=>`<button class="v2-plan-row" onclick="${esc(a)}"><span><b>${t}</b><small>${s}</small></span><span aria-hidden="true">›</span></button>`).join(''):'<p class="hint">Your recorded daily targets are met. Add more whenever you need.</p>'}`);
}
overview=function(){return v2()?today20():legacy20.overview();};
function timeline20(){return [['dose',S.entries],['body',S.measurements],['water',S.hydration],['protein',S.proteinLog],['feeling',S.feelings],['circumference',S.circumferences],['activity',extra20('activity')],['notes',extra20('notes')]].flatMap(([kind,rows])=>(rows||[]).map(r=>({...r,kind}))).sort((a,b)=>Date.parse(b.at)-Date.parse(a.at)||a.id.localeCompare(b.id));}
function recordLabel20(r){if(r.kind==='dose')return 'Injection · '+fmt(r.mg)+' mg';if(r.kind==='body')return r.values.weight?'Weight · '+weightText(r.values.weight):'Body composition';if(r.kind==='water')return 'Water · '+fmt(displayValue(r.ml,'water'))+' '+unitLabel('water');if(r.kind==='protein')return 'Protein · '+fmt(r.grams)+' g';if(r.kind==='feeling')return 'Check-in';if(r.kind==='circumference')return 'Body measurement';return r.kind==='notes'?'Note':r.title;}
function recordEdit20(kind,id){if(kind==='dose')editEntry(id);else if(kind==='body')editMeasurement(id);else if(kind==='circumference')editCircumferences(id);else if(kind==='feeling')editFeeling(id);else if(kind==='water'||kind==='protein')editDaily(kind,id);else editExtra20(kind,id);}
function recordBody20(r){if(r.kind==='dose')return `<p class="hint">${esc(r.status||'taken')}${r.site?' · '+esc(r.site.replaceAll('-',' ')):''}</p>${journalSupply(r)}`;if(r.kind==='body')return `<p class="hint">${esc(r.source||'Manual')}</p><p>${Object.entries(r.values).map(([k,v])=>metricText20(k,v)).join(' · ')}</p>`;if(r.kind==='feeling')return `<p>${Object.entries(r.values||{}).map(([k,v])=>esc(k)+' '+fmt(v)+'/5').join(' · ')}</p>`;if(r.kind==='circumference')return `<p>${Object.entries(r.values).map(([k,v])=>esc(measureNames[k]||k)+': '+fmt(displayValue(v,'length'))+' '+unitLabel('length')).join(' · ')}</p>`;if(r.kind==='activity')return `<p>${r.minutes!=null?fmt(r.minutes)+' min · ':''}${r.steps!=null?fmt(r.steps,0)+' steps':''}</p>`;if(r.kind==='protein')return `<p>${esc(r.meal||proteinSources[r.source]||'')}</p>`;return '';}
function deleteTimeline20(kind,id){if(['dose','feeling','water','protein'].includes(kind))return confirmRecord18(kind,id);const r=timeline20().find(r=>r.kind===kind&&r.id===id);if(!r)return;modal('Delete this record?',`<p>${esc(recordLabel20(r))}</p><p class="hint">${dayDate(r.at)} · ${clock(r.at)}</p>${button('Cancel','closeModal()','secondary')}${button('Delete',`commitDelete20('${kind}','${id}')`,'danger')}`);}
function commitDelete20(kind,id){const key={body:'measurements',circumference:'circumferences'}[kind];if(!key&&!['activity','notes','equipment'].includes(kind))return;if(change(()=>{if(key)S[key]=S[key].filter(r=>r.id!==id);else S.uxV2[kind]=extra20(kind).filter(r=>r.id!==id);},true)){closeModal();render();toast('Record deleted.',true);}}
function setDay20(day){ui20.day=day;render();}
function journal20(){const filters=[['all','All'],['dose','Injection'],['body','Body'],['nutrition','Nutrition'],['activity','Activity'],['feeling','Check-in'],['notes','Notes']],base=new Date((ui20.day||Core.isoDay(Date.now()))+'T12:00:00'),days=Array.from({length:7},(_,i)=>{const d=new Date(base);d.setDate(d.getDate()+i-3);return d;}),rows=timeline20().filter(r=>(!ui20.day||Core.isoDay(r.at)===ui20.day)&&(ui20.filter==='all'||ui20.filter===r.kind||ui20.filter==='nutrition'&&['water','protein'].includes(r.kind)||ui20.filter==='body'&&r.kind==='circumference'));
let previous='';return heading20('Journal','Everything you recorded, in one place.')+`<div class="v2-datebar"><label for="v2-date">Calendar</label><input id="v2-date" type="date" value="${ui20.day}" onchange="setDay20(this.value)"><button class="small-button" onclick="setDay20('')">All dates</button><button class="small-button" onclick="setDay20(Core.isoDay(Date.now()))">Today</button></div><div class="v2-week">${days.map(d=>`<button class="${Core.isoDay(d)===ui20.day?'on':''}" aria-label="${dayDate(d)}" onclick="setDay20('${Core.isoDay(d)}')"><small>${d.toLocaleDateString('en-GB',{weekday:'short'})}</small><b>${d.getDate()}</b></button>`).join('')}</div><div class="v2-tabs" aria-label="Journal filters">${filters.map(([k,n])=>`<button aria-pressed="${ui20.filter===k}" class="${ui20.filter===k?'on':''}" onclick="ui20.filter='${k}';render()">${n}</button>`).join('')}</div><p class="hint">${ui20.day?dayDate(ui20.day+'T12:00:00'):'All dates'} · ${rows.length} records</p>`+(rows.length?rows.map(r=>{const day=Core.isoDay(r.at),label=recordLabel20(r),ico={dose:'syringe',body:'chart',water:'water',protein:'food',feeling:'user',circumference:'body',activity:'activity',notes:'note'}[r.kind],group=day!==previous?`<h2 class="v2-day-label">${dayDate(r.at)}</h2>`:'';previous=day;return group+`<article class="card v2-record" id="${r.kind==='dose'?'entry-':'record-'+r.kind+'-'}${r.id}"><div class="row"><span class="v2-record-icon">${icon(ico)}</span><div class="grow"><b>${esc(label)}</b><div class="hint">${clock(r.at)}</div></div><button class="icon-button" aria-label="Edit ${esc(label)}" onclick="recordEdit20('${r.kind}','${r.id}')">${icon('edit')}</button><button class="icon-button" aria-label="Delete ${esc(label)}" onclick="deleteTimeline20('${r.kind}','${r.id}')">${trash18()}</button></div><details ${expandedEntries.has(r.kind+'-'+r.id)?'open':''} ontoggle="if(this.open)expandedEntries.add('${r.kind}-${r.id}');else expandedEntries.delete('${r.kind}-${r.id}')"><summary>Details${r.status==='planned'?' · Planned':''}</summary>${recordBody20(r)}${r.note?'<p>'+esc(r.note)+'</p>':''}</details></article>`;}).join(''):card('<h2>No records for this selection</h2><p class="hint">Change the day or filter, or use + to add a record.</p>'));
}
journal=function(){return v2()?journal20():legacy20.journal();};
function editExtra20(kind,id=''){if(!['activity','notes'].includes(kind))return;const r=extra20(kind).find(r=>r.id===id)||{},at=r.at?local(r.at):page==='journal'&&ui20.day&&ui20.day!==Core.isoDay(Date.now())?ui20.day+'T12:00':local();modal(kind==='activity'?'Workout / Activity':'Note',field('extra-at','Date & time',at,'datetime-local')+(kind==='activity'?field('extra-title','Activity',r.title||'')+`<div class="grid2">${field('extra-minutes','Duration · minutes (optional)',r.minutes??'','number')}${field('extra-steps','Steps (optional)',r.steps??'','number')}</div><p class="hint">Record each activity once. Step counts are summed from your manual records.</p>`:'')+`<label for="extra-note">${kind==='notes'?'Note':'Note (optional)'}</label><textarea id="extra-note" rows="4">${esc(r.note||'')}</textarea>`+button('Save record',`saveExtra20('${kind}','${id}')`)+(id?button('Delete',`deleteTimeline20('${kind}','${id}')`,'danger'):''));}
function putExtra20(kind,row){S.uxV2=S.uxV2||{version:1};S.uxV2[kind]=[...extra20(kind).filter(r=>r.id!==row.id),row];}
function saveExtra20(kind,id){try{if(!['activity','notes'].includes(kind))return;const row={id:id||uid(),at:new Date(val('extra-at')).toISOString(),note:val('extra-note').trim()};if(kind==='activity')Object.assign(row,{title:val('extra-title').trim(),minutes:val('extra-minutes')===''?null:Core.num(val('extra-minutes')),steps:val('extra-steps')===''?null:Core.num(val('extra-steps'))});if(change(()=>putExtra20(kind,row),true)){closeModal();render();toast('Record saved.',true);}}catch(e){formError(e);}}
function metricText20(k,v){const mass=['weight','muscle','skeletal','lean','bone','waterMass','fatMass'].includes(k),length=k==='headSize';return esc((Core.metricNames[k]||k).replace(/ · (kg|cm)$/,''))+': '+(k==='bodyType'?esc(v):fmt(mass||length?displayValue(v,mass?'weight':'length'):v))+(mass?' '+unitLabel('weight'):length?' '+unitLabel('length'):'');}
function period20(){return `<div class="v2-tabs" aria-label="Analysis period">${[7,14,30,90,0].map(n=>`<button class="${ui20.period===n?'on':''}" aria-pressed="${ui20.period===n}" onclick="ui20.period=${n};render()">${n?n+'D':'All'}</button>`).join('')}</div>`;}
function since20(){if(!ui20.period)return -Infinity;const d=new Date();d.setHours(0,0,0,0);d.setDate(d.getDate()-ui20.period+1);return +d;}
function bodyMetrics20(){const keys=Object.keys(Core.metricNames).filter(k=>k!=='weight'),rows=S.measurements.filter(r=>Date.parse(r.at)>=since20()).sort((a,b)=>Date.parse(a.at)-Date.parse(b.at)),metric=ui20.metric,selected=rows.filter(r=>r.values[metric]!=null),mass=['muscle','skeletal','lean','bone','waterMass','fatMass'].includes(metric);return card(`<h2>Body composition</h2><p class="hint">Scale-reported estimates. Missing readings stay empty.</p>${period20()}${select('metric20','Explore a metric',keys.map(k=>[k,Core.metricNames[k]]),metric)}${selected.length?`<p><b>${metricText20(metric,selected.at(-1).values[metric])}</b></p><p class="hint">${dayDate(selected.at(-1).at)} · ${esc(selected.at(-1).source||'Manual')}</p>${metric!=='bodyType'?spark20(selected.map(r=>({t:Date.parse(r.at),v:mass?displayValue(r.values[metric],'weight'):+r.values[metric]})),Core.metricNames[metric]):''}<p class="hint">${selected.length>1&&metric!=='bodyType'?'Change: '+fmt((mass?displayValue(selected.at(-1).values[metric]-selected[0].values[metric],'weight'):selected.at(-1).values[metric]-selected[0].values[metric]))+' · first to last recorded value':'Add another measurement to compare'}</p>`:'<p class="hint">No readings of this metric in this period.</p>'}<details><summary>All imported metrics</summary>${keys.map(k=>{const rs=rows.filter(r=>r.values[k]!=null);return `<div class="list-item">${rs.length?metricText20(k,rs.at(-1).values[k]):esc(Core.metricNames[k])+': —'}${rs.length?'<small class="hint"> · '+dayDate(rs.at(-1).at)+'</small>':''}</div>`;}).join('')}</details>${button('Original readings & timestamps','bodyHistory()','secondary')}`);}
function nutrition20(){const dates=[...new Set([...S.hydration,...S.proteinLog].filter(r=>Date.parse(r.at)>=since20()).map(r=>Core.isoDay(r.at)))].sort().reverse(),range=Core.proteinRange(S.profile),proteinDays=dates.filter(d=>S.proteinLog.some(r=>Core.isoDay(r.at)===d)),waterDays=dates.filter(d=>S.hydration.some(r=>Core.isoDay(r.at)===d)),proteinMet=proteinDays.filter(d=>range&&Core.dayTotals(S,d).protein>=range.min).length,waterMet=waterDays.filter(d=>S.settings.waterTarget&&Core.dayTotals(S,d).water>=S.settings.waterTarget).length;return period20()+card(`<h2>Nutrition & hydration adherence</h2><p>${range?'Protein range '+fmt(range.min,0)+'–'+fmt(range.max,0)+' g · midpoint '+fmt(range.mid,0)+' g':'No protein range configured'}</p><div class="v2-pair"><div><div class="stat">${range&&proteinDays.length?fmt(proteinMet/proteinDays.length*100,0)+'%':'—'}</div><p class="hint">Protein minimum met<br>${proteinMet} / ${proteinDays.length} logged days</p></div><div><div class="stat">${S.settings.waterTarget&&waterDays.length?fmt(waterMet/waterDays.length*100,0)+'%':'—'}</div><p class="hint">Hydration target met<br>${waterMet} / ${waterDays.length} logged days</p></div></div><p class="hint">Uses current targets. Unlogged days are missing, not zero intake.</p>${button('Configure goals',"go20('profile','goals')",'secondary')}`)+stripConfig20(nutritionCard())+card(`<h2>Daily intake trends</h2>${dates.length?`<div class="v2-table-wrap"><table><thead><tr><th>Day</th><th>Protein · g</th><th>Water · ${unitLabel('water')}</th></tr></thead><tbody>${dates.map(d=>{const t=Core.dayTotals(S,d);return `<tr><th><button class="link" onclick="ui20.day='${d}';ui20.filter='nutrition';go20('journal')">${dayDate(d+'T12:00:00')}</button></th><td>${proteinDays.includes(d)?fmt(t.protein):'—'}</td><td>${waterDays.includes(d)?fmt(displayValue(t.water,'water')):'—'}</td></tr>`;}).join('')}</tbody></table></div>`:'<p class="hint">Use + to record protein or water.</p>'}`);}
function stripConfig20(html){const d=document.createElement('div');d.innerHTML=html;d.querySelectorAll('[onclick="editProfile()"],[onclick="editProteinRange()"],[onclick="dailySettings()"]').forEach(el=>el.setAttribute('onclick',"go20('profile','goals')"));return d.innerHTML;}
function activity20(){const rows=extra20('activity').filter(r=>Date.parse(r.at)>=since20()).sort((a,b)=>Date.parse(b.at)-Date.parse(a.at)),days=new Set(rows.map(r=>Core.isoDay(r.at)));return period20()+card(`<h2>Activity & workouts</h2><div class="v2-stat-grid"><div><b>${rows.length}</b><small>Activities</small></div><div><b>${days.size}</b><small>Active days</small></div><div><b>${fmt(rows.reduce((n,r)=>n+(r.minutes||0),0),0)}</b><small>Minutes</small></div><div><b>${fmt(rows.reduce((n,r)=>n+(r.steps||0),0),0)}</b><small>Recorded steps</small></div></div><p class="hint">Manual records only. Health Connect activity import is not available in this build.</p>${button('+ Record activity',"editExtra20('activity')")}`)+rows.map(r=>card(`<div class="row spread"><h3>${esc(r.title)}</h3>${button('Edit',`editExtra20('activity','${r.id}')`,'secondary')}</div><p class="hint">${dayDate(r.at)} · ${clock(r.at)}</p>${recordBody20({...r,kind:'activity'})}${r.note?'<p>'+esc(r.note)+'</p>':''}`)).join('');}
function insights20(){const top=heading20('Progress','See how your records change over time.')+tabs20('progress');if(ui20.progress==='nutrition')return top+nutrition20();if(ui20.progress==='activity')return top+activity20();const d=document.createElement('div');d.innerHTML=legacy20.insights();if(ui20.progress==='body'){const body=d.querySelector('.weight-chart-card')?.closest('section');return top+(body?.outerHTML||card('<h2>Weight trend</h2><p class="hint">Add or import weight readings.</p>'+button('Add measurement','editMeasurement()')))+movingWeight20()+forecastPanel()+bodyMetrics20()+circumferenceCard();}if(ui20.progress==='reta'){const chartEl=d.querySelector('.chart-card'),layers=d.querySelector('#layer-peaks')?.closest('section'),settingsBox=document.createElement('div');settingsBox.innerHTML=legacy20.settings();const model=settingsBox.querySelector('#half')?.closest('section'),ds=Core.doses(S.entries),intervals=ds.slice(1).map((r,i)=>(r.t-ds[i].t)/Core.DAY);return top+card(`<div class="eyebrow">Recorded injection statistics</div><div class="v2-stat-grid"><div><b>${ds.length?fmt(ds.at(-1).mg)+' mg':'—'}</b><small>Last taken dose</small></div><div><b>${fmt(ds.reduce((n,r)=>n+r.mg,0))} mg</b><small>Total injected</small></div><div><b>${fmt(ds.filter(r=>r.t>=Date.now()-28*Core.DAY).reduce((n,r)=>n+r.mg,0)/4)} mg</b><small>Weekly average · past 28D ÷ 4</small></div><div><b>${intervals.length?fmt(intervals.reduce((a,b)=>a+b,0)/intervals.length)+' d':'—'}</b><small>Mean recorded interval</small></div></div>`)+`<div class="chipbar">${[7,14,30,90,0].map(n=>button(n?n+'D':'All',`chartRange(${n})`,'small-button')).join('')}${button('Today','chartToday()','small-button')}</div>`+(chartEl?.outerHTML||'')+(layers?`<details class="card v2-layers"><summary>Model layers & explanation</summary>${layers.innerHTML}</details>`:'')+(model?.outerHTML||'')+doseWindowCard()+weeklyCard()+button('Injection history',"ui20.filter='dose';ui20.day='';go20('journal')",'secondary');}return top+goalSummary20()+progressPanel()+forecastPanel()+card(`<h2>Latest body changes</h2>${['fat','muscle','water','visceral','bmi'].map(k=>{const rows=S.measurements.filter(r=>r.values[k]!=null).sort((a,b)=>Date.parse(a.at)-Date.parse(b.at));return `<div class="list-item">${rows.length?metricText20(k,rows.at(-1).values[k]):esc(Core.metricNames[k])+': —'}${rows.length>1?`<span class="hint"> · change ${fmt(k==='muscle'?displayValue(rows.at(-1).values[k]-rows[0].values[k],'weight'):rows.at(-1).values[k]-rows[0].values[k])}</span>`:''}</div>`;}).join('')}<p class="hint">Change compares first and latest available readings of each metric. Scale estimates vary with hydration.</p>${button('Explore body trends',"tab20('progress','body')",'secondary')}`)+card(`<h2>Check-in history</h2><p class="hint">Appetite, energy, mood, libido, digestion and notes.</p>${button('Open check-ins',"ui20.filter='feeling';ui20.day='';go20('journal')",'secondary')}`);}
insights=function(){return v2()?insights20():legacy20.insights();};
function equipment20(){return card(`<div class="row spread"><h2>Equipment</h2>${button('+ Add',"editEquipment20()",'secondary')}</div><p class="hint">Syringes, needles, swabs and other equipment. Counts are tracked separately from mg and mL.</p>${extra20('equipment').map(r=>`<div class="list-item"><div class="row spread"><div><b>${esc(r.name)}</b><p class="hint">${r.quantity} pcs · <span class="status-${r.quantity===0?'low':r.quantity<=r.low?'almost':'met'}">${r.quantity===0?'EMPTY':r.quantity<=r.low?'LOW':'OK'}</span></p></div>${button('Edit',`editEquipment20('${r.id}')`,'secondary')}</div>${r.note?'<p class="hint">'+esc(r.note)+'</p>':''}${r.quantity?button('Use one',`useEquipment20('${r.id}')`,'secondary'):''}</div>`).join('')}`);}
function editEquipment20(id=''){const r=extra20('equipment').find(r=>r.id===id)||{};modal('Equipment',field('eq-name','Name / model',r.name||'')+select('eq-type','Type',[['syringe','Syringe'],['needle','Needle'],['swab','Alcohol swab'],['other','Other']],r.type||'needle')+field('eq-quantity','Remaining count',r.quantity??0,'number')+field('eq-low','Low threshold',r.low??5,'number')+field('eq-note','Size, gauge, compatibility or other notes',r.note||'')+button('Save equipment',`saveEquipment20('${id}')`)+(id?button('Delete',`removeEquipment20('${id}')`,'danger'):''));}
function saveEquipment20(id){try{const r={id:id||uid(),at:new Date().toISOString(),name:val('eq-name').trim(),type:val('eq-type'),quantity:Core.num(val('eq-quantity')),low:Core.num(val('eq-low')),note:val('eq-note')};if(change(()=>putExtra20('equipment',r),true)){closeModal();render();toast('Equipment saved.',true);}}catch(e){formError(e);}}
function removeEquipment20(id){modal('Delete this equipment?',`<p>The selected equipment record will be removed.</p>${button('Cancel','closeModal()','secondary')}${button('Delete',`commitDelete20('equipment','${id}')`,'danger')}`);}
function useEquipment20(id){const r=extra20('equipment').find(r=>r.id===id);if(r?.quantity>0&&change(()=>r.quantity--,true)){render();toast('One item recorded as used.',true);}}
inventory=function(){if(!v2())return legacy20.inventory();const body=ui20.supplies==='calculator'?calculator20():ui20.supplies==='learn'?legacy20.learn():inventoryPanel20()+equipment20();return heading20('Supplies','Your complete injection toolkit.')+tabs20('supplies')+strip20(body);};
function goals20(){const p=S.profile,r=Core.proteinRange(p);return card(`<h2>My Goals</h2><div class="v2-goal-row"><span>Target weight</span><b>${p.target?weightText(p.target):'Not set'}</b></div><div class="v2-goal-row"><span>Target body fat</span><b>${p.targetFat?fmt(p.targetFat)+'%':'Not set'}</b></div><div class="v2-goal-row"><span>Protein range</span><b>${r?fmt(r.min,0)+'–'+fmt(r.max,0)+' g':'Not set'}</b></div><div class="v2-goal-row"><span>Protein midpoint</span><b>${r?fmt(r.mid,0)+' g':'—'}</b></div><div class="v2-goal-row"><span>Hydration</span><b>${S.settings.waterTarget?fmt(displayValue(S.settings.waterTarget,'water'))+' '+unitLabel('water'):'Not set'}</b></div><div class="v2-goal-row"><span>Keto mode</span><b>${p.keto?'On':'Off'}</b></div>${button('Weight, macros & calorie goals','editProfile()','secondary')}${button('Protein range','editProteinRange()','secondary')}${button('Hydration & tracking','dailySettings()','secondary')}${button('Body fat target','editFat20()','secondary')}`)+nutritionCard();}
function editFat20(){modal('Target body fat',field('goal-fat','Target · % (optional)',S.profile.targetFat??'','number')+button('Save target','saveFat20()'));}
function saveFat20(){try{const n=val('goal-fat')===''?null:Core.num(val('goal-fat'));if(change(()=>S.profile.targetFat=n)){closeModal();render();}}catch(e){formError(e);}}
function healthData20(){const w=latestWeight(),p=S.profile;return card(`<h2>Current Weight</h2><div class="big">${w?weightText(w.values.weight):'—'}</div><p class="hint">${w?dayDate(w.at)+' · '+clock(w.at)+' · '+esc(w.source||'Manual'):'No measurement recorded.'}</p>${button('Record weight','editMeasurement()')}${button('All original body records','bodyHistory()','secondary')}`)+card(`<h2>Personal & reference data</h2><p>${esc(p.name||'Your profile')}${p.height?' · '+fmt(displayValue(p.height,'length'))+' '+unitLabel('length'):''}</p>${button('Edit profile','editProfile()','secondary')}${button('Record circumference','editCircumferences()','secondary')}${button('Explore body history',"go20('insights','body')",'secondary')}`);}
function settings20(){const d=document.createElement('div');d.innerHTML=strip20(legacy20.settings());d.querySelector('#half')?.closest('section')?.remove();d.querySelectorAll('label.check').forEach(el=>{if(['Weight card','Nutrition targets card','Model estimate card'].includes(el.textContent.trim()))el.remove();});return d.innerHTML+card(`<h2>Notifications & reminders</h2><p class="hint">Create your own reminders. In-app inventory and BAC warnings do not automatically schedule notifications.</p>${button('Manage reminders',"go20('reminders')",'secondary')}`)+card(`<h2>Classic dashboard preferences</h2><p class="hint">Your saved Classic card visibility and order remain available.</p>${button('Arrange Classic cards','editHome()','secondary')}</section><section class="card"><h2>About Reta Log</h2><p>2.0.1 · UX Architecture V2</p>${button('About, terms & privacy',"go20('legal')",'secondary')}`);}
profile=function(){if(!v2())return legacy20.profile();return heading20('You','Your goals. Your data. Your space.')+tabs20('you')+(ui20.you==='goals'?goals20():ui20.you==='health data'?healthData20():ui20.you==='connections'?strip20(legacy20.dataPage()):settings20());};
/* Chart delegates stay intact; retain range and series on rerender/rotation. */
setupChart=function(){legacy20.setupChart();if(!v2()||!chart||!$('#pk-chart'))return;const c=charts20[routeKey20()];if(c?.start!=null)Object.assign(chart,{start:c.start,end:c.end,picked:c.picked});else{chart.end=Date.now()+Core.DAY;chart.start=chart.end-7*Core.DAY;}if(c?.layers)for(const [id,on]of Object.entries(c.layers))if($('#'+id))$('#'+id).checked=on;chart.draw();};
setupWeightChart=function(){legacy20.setupWeightChart();if(!v2()||!weightChart||!$('#weight-chart'))return;const c=charts20[routeKey20()];if(c?.a!=null)Object.assign(weightChart,{a:c.a,b:c.b,picked:c.weightPicked});else{weightChart.b=Date.now()+Core.DAY;weightChart.a=weightChart.b-7*Core.DAY;}weightChart.draw();};
render=function(){remember20();if(v2()){if(page==='settings'){page='profile';ui20.you='settings';}else if(page==='data'){page='profile';ui20.you='connections';}else if(page==='learn'||page==='calculator'){ui20.supplies=page;page='inventory';}else if(page==='wellness')page='journal';}legacy20.render();if(!v2()){rendered20='';return;}rendered20=routeKey20();const nav=$('#app>nav');nav.setAttribute('aria-label','Main navigation');nav.innerHTML=routes20.map(([p,i,n])=>`<button aria-label="${n}" ${p===page?'aria-current="page"':''} class="${p===page?'active':''}" onclick="navigate('${p}')">${icon(i)}<span>${n}</span></button>`).join('');nav.insertAdjacentHTML('beforebegin','<button class="v2-fab" aria-label="Quick Add" onclick="quickAdd20()"><svg viewBox="0 0 24 24" width="28" height="28" aria-hidden="true"><path d="M12 5v14M5 12h14" fill="none" stroke="currentColor" stroke-width="2.4" stroke-linecap="round"/></svg></button>');if(page==='insights'&&ui20.progress==='reta'){drawMini();const model=$('#half');if(model){const save=model.parentElement.querySelector('button');if(save)save.textContent='Save';}const remembered=charts20[rendered20];if(remembered?.layers)for(const [id,on]of Object.entries(remembered.layers))if($('#'+id))$('#'+id).checked=on;chart?.draw();}if(page==='inventory'&&ui20.supplies==='inventory')supplyStatuses20();if($('#metric20'))$('#metric20').onchange=e=>{ui20.metric=e.target.value;render();};};
/* Extended records accompany complete and summary exports; legacy sections unchanged. */
reportText18=function(r){let text=legacy20.reportText18(r);const inRange=x=>r.start==null||Date.parse(x.at)>=r.start&&Date.parse(x.at)<=(r.end||Date.now());for(const kind of ['activity','notes']){const rows=extra20(kind).filter(inRange);if(rows.length)text+='\n\n'+kind.toUpperCase()+'\n'+rows.map(x=>dayDate(x.at)+' '+clock(x.at)+' | '+(x.title||'')+(x.minutes!=null?' | '+x.minutes+' min':'')+(x.steps!=null?' | '+x.steps+' steps':'')+' | '+(x.note||'')).join('\n');}return text;};

function newRecord20(type){const forms={syringe:editEntry,chart:editMeasurement,food:()=>editDaily('protein'),water:()=>editDaily('water'),user:editFeeling,activity:()=>editExtra20('activity'),body:editCircumferences,note:()=>editExtra20('notes')};forms[type]?.();if(page==='journal'&&ui20.day&&ui20.day!==Core.isoDay(Date.now())){const input=$('#entry-at,#measure-at,#daily-at,#feeling-at,#circ-at,#extra-at');if(input){input.value=ui20.day+'T12:00';input.dispatchEvent(new Event('input'));}}}
function goalSummary20(){const w=latestWeight(),p=Core.progress(S.entries,selectedWeightRecords()),target=+S.profile.target,base=p.firstWeight,progress=w&&base&&target&&base!==target?Math.max(0,Math.min(100,(base-w.values.weight)/(base-target)*100)):null;return card(`<div class="v2-stat-grid"><div><b>${w?weightText(w.values.weight):'—'}</b><small>Current Weight</small></div><div><b>${target?weightText(target):'—'}</b><small>Target weight</small></div><div><b>${p.days}</b><small>Days since first taken injection</small></div><div><b>${progress==null?'—':fmt(progress,0)+'%'}</b><small>Weight goal progress</small></div></div>${progress!=null?`<progress class="v2-progress" max="100" value="${progress}" aria-label="Weight goal progress"></progress>`:''}`);}
function movingWeight20(){const rows=Core.weightDays(S.measurements,S.settings.weightMode),points=rows.map(r=>{const a=new Date(r.t);a.setHours(0,0,0,0);a.setDate(a.getDate()-6);const recent=rows.filter(x=>x.t>=+a&&x.t<=r.t);return{t:r.t,v:displayValue(recent.reduce((n,x)=>n+x.weight,0)/recent.length,'weight')};}).filter(p=>p.t>=since20());return card(`<h2>7-day moving average</h2>${period20()}${points.length?spark20(points,'7-day weight moving average'): '<p class="hint">No readings in this period.</p>'}<p>${points.length?'Latest average: <b>'+fmt(points.at(-1).v)+' '+unitLabel('weight')+'</b>':''}${S.profile.target?' · Target: <b>'+weightText(S.profile.target)+'</b>':''}</p><p class="hint">Average of available selected daily weights in the trailing seven calendar days. Dashed connections bridge missing dates; they are not measured readings. Original records and goal projection calculations are unchanged.</p>`);}
function calculator20(){const d=document.createElement('div');d.innerHTML=legacy20.calculator();d.querySelector('#calc-detail').insertAdjacentHTML('afterend',`${select('unit-scale20','Actual syringe scale',[['ml','mL only'],['100','U-100 · 100 units/mL'],['40','U-40 · 40 units/mL']],'ml')}<p id="units-result20" class="hint">Select the scale printed on your actual syringe to convert mL to its marked units.</p>`);d.querySelector('#capacity-wrap').insertAdjacentHTML('beforeend',field('custom-capacity20','Custom illustrated capacity · mL (optional)','','number')+button('Apply capacity','customCapacity20()','secondary'));return d.innerHTML;}
const calculateBefore20=calculate;calculate=function(){calculateBefore20();if(v2())unitsResult20();};
function unitsResult20(){const out=$('#units-result20');if(!out)return;const scale=+val('unit-scale20');out.textContent=calcValue!=null&&Number.isFinite(scale)&&scale>0?fmt(calcValue*scale,3)+' marked units at '+scale+' units/mL. This is a volume conversion, not units of retatrutide or a pen setting.': 'Select the scale printed on your actual syringe to convert mL to its marked units.';}
function customCapacity20(){try{const n=Core.positive(val('custom-capacity20'),'Capacity');if(n>100)throw Error('Check the capacity in mL.');const select=$('#capacity');if(![...select.options].some(o=>+o.value===n))select.add(new Option(fmt(n)+' mL · custom',n));select.value=n;deviceTab(false);$('#device-note').textContent='Custom schematic capacity. Verify real graduations on your device; the drawing is not a measuring scale.';}catch(e){formError(e);}}
document.addEventListener('change',e=>{if(v2()&&e.target.id==='unit-scale20')unitsResult20();});
document.addEventListener('input',e=>{if(v2()&&['cm','cv','cd'].includes(e.target.id))unitsResult20();});
function supplyStatuses20(){document.querySelectorAll('.supply-card').forEach(el=>{const v=S.vials.find(v=>'supply-'+v.id===el.id),badge=el.querySelector('.stock-badge');if(!v||!badge)return;const x=Core.bacExpiry(v);if(x&&['expired','discarded','soon','unknown'].includes(x.state))return;const b=stock(v),low=v.type==='water'?S.settings.lowMl:S.settings.lowMg??3;const status=b.remaining===0?'low':low!=null&&b.remaining<=low?'almost':'met';badge.textContent=status==='low'?'EMPTY':status==='almost'?'LOW':'OK';badge.className='stock-badge status-'+status;});}

function inventoryPanel20(){const d=document.createElement('div');d.innerHTML=legacy20.inventory();const breakdown=d.querySelector('.balance-breakdown');if(breakdown){const details=document.createElement('details');details.className='v2-stock-breakdown';details.innerHTML='<summary>Capacity & usage by category</summary>';breakdown.before(details);details.append(breakdown);}const legend=d.querySelector('.stock-legend');if(legend)legend.innerHTML='<span class="status-met">● OK</span><span class="status-almost">● LOW</span><span class="status-low">● EMPTY</span>';d.querySelectorAll('button').forEach(el=>{if(el.textContent.trim()==='Calculator')el.remove();});const summary=d.querySelector('section');if(summary)summary.insertAdjacentHTML('beforeend',`<p class="hint">${fmt(Core.doses(S.entries).reduce((n,r)=>n+r.mg,0))} mg total injected · all taken records</p>`);return d.innerHTML;}

function quickExtras20(){const last=[...S.proteinLog].sort((a,b)=>Date.parse(b.at)-Date.parse(a.at))[0];return (S.settings.waterLogging?`<p class="hint">Quick water · today</p><div class="chipbar">${[250,300,500].map(n=>button('+'+fmt(displayValue(n,'water'))+' '+unitLabel('water'),`closeModal();quickWater(${n})`,'small-button')).join('')}</div>`:'')+(S.settings.proteinLogging&&last?button('Repeat last protein entry',`editDaily('protein','${last.id}',true)`,'secondary'):'');}
const nativeBefore20=window.nativeEvent;
window.nativeEvent=function(name,data){nativeBefore20?.(name,data);if(v2()&&page==='profile'&&ui20.you==='settings'&&['lock','error'].includes(name)&&!$('#modal').innerHTML)render();};
render();
