const assert=require('node:assert/strict');
const C=require('../app/src/main/assets/core.js');
const now=Date.parse('2026-09-18T12:00:00Z');
const records=Array.from({length:22},(_,i)=>({at:new Date(now-(21-i)*C.DAY).toISOString(),values:{weight:92-i*.1}}));
const result=C.forecast(records,80,now);
assert.equal(result.status,'ready');assert.ok(Math.abs(result.weekly-.7)<1e-8);assert.ok(result.days>=101&&result.days<=103);
assert.equal(C.forecast([],80,now).status,'insufficient');
assert.equal(C.forecast(records,0,now).status,'no-target');
assert.equal(C.forecast(records.slice(0,4),80,now).status,'stale');
assert.equal(C.forecast(records.map(m=>({...m,values:{weight:90}})),80,now).status,'no-decline');
assert.equal(C.forecast(records,95,now).status,'reached');
const repeated=[...records,...Array(50).fill(records.at(-1))];
assert.equal(C.forecast(repeated,80,now).days,result.days);
assert.equal(C.forecast(records.slice(-4),80,now).status,'insufficient');
assert.equal(C.amount([{t:now,mg:2}],now+6*C.DAY),1);
assert.equal(C.amount([{t:now+1,mg:2}],now),0);
assert.ok(Math.abs(C.mean([{t:now,mg:2}],now,now+6*C.DAY)-1/Math.log(2))<1e-8);
assert.equal(C.doses([{at:new Date(now).toISOString(),mg:1,status:'planned'}]).length,0);
assert.deepEqual(C.parseCSV('Date;Weight\n"18/09/2026";"89,2"').rows,[['18/09/2026','89,2']]);
assert.throws(()=>C.parseDate('31/02/2026'));
assert.throws(()=>C.concentration(1,0,1));
console.log('Core checks passed: forecast, daily weighting, missing data, PK model, CSV and validation.');
const supplyEntries=[{vial:'v',at:'2026-09-01T10:00:00Z',mg:2,status:'taken'},{vial:'v',at:'2026-09-02T10:00:00Z',mg:3,status:'planned'},{vial:'v',at:'2026-09-03T10:00:00Z',mg:3,status:'skipped'},{vial:'other',at:'2026-09-03T10:00:00Z',mg:2,status:'taken'}];
assert.deepEqual(C.supplyBalance({id:'v',mg:10},supplyEntries,now),{declared:10,used:2,remaining:8,overdrawn:0});
assert.equal(C.supplyBalance({id:'v',mg:1},supplyEntries,now).overdrawn,1);
assert.equal(C.supplyBalance({id:'v',mg:10},[],now).remaining,10);
const days=C.weightDays([{at:'2025-12-31T10:00:00',values:{weight:90}},{at:'2025-12-31T14:00:00',values:{weight:92}},{at:'2026-01-02T12:00:00',values:{weight:89}},{at:'2026-01-03',values:{fat:20}}]);
assert.equal(days.length,2);assert.equal(days[0].weight,91);assert.equal(days[0].count,2);assert.equal(days[1].weight,89);assert.equal(days[1].key,'2026-1-2');
console.log('1.4 checks passed: supply status/link accounting and daily weights across year boundaries.');
const history=[{id:'a',vial:'v',at:'2026-09-03T10:00:00Z',mg:1,status:'taken'},{id:'b',vial:'v',at:'2026-09-08T10:00:00Z',mg:1.5,status:'taken'},{id:'c',vial:'v',at:'2026-09-09T10:00:00Z',mg:2,status:'skipped'},{id:'d',vial:'other',at:'2026-09-09T10:00:00Z',mg:5,status:'taken'}],v={id:'v',mg:10};
assert.equal(C.supplyBalanceAfter(v,history,history[0]).remaining,9);
assert.equal(C.supplyBalanceAfter(v,history,history[1]).remaining,7.5);
assert.equal(C.supplyBalanceAfter(v,history,history[2]).remaining,7.5);
assert.equal(C.supplyBalanceAfter(v,history.slice(1),history[1]).remaining,8.5);
const sameTime=[history[0],{...history[0],id:'b',mg:2}];
assert.equal(C.supplyBalanceAfter(v,sameTime,sameTime[0]).remaining,9);
assert.equal(C.supplyBalanceAfter(v,[...sameTime].reverse(),sameTime[1]).remaining,7);
console.log('1.5 checks passed: historical balances, timestamp ties, deleted earlier entry and supply isolation.');
