(function(){const C=typeof module!=='undefined'?require('./core16.js'):Core;
const validate16=C.validateStore;
C.isoDay=function(t){const d=new Date(t);return [d.getFullYear(),String(d.getMonth()+1).padStart(2,'0'),String(d.getDate()).padStart(2,'0')].join('-');};
C.validateStore=function(s){validate16(s);for(const key of ['hydration','proteinLog']){if(s[key]===undefined)s[key]=[];if(!Array.isArray(s[key])||s[key].length>50000)throw Error('Invalid '+key+' history.');const seen=new Set();for(const r of s[key]){if(!r||!/^[A-Za-z0-9_-]{1,150}$/.test(r.id||'')||seen.has(r.id)||!Number.isFinite(Date.parse(r.at))||Date.parse(r.at)>Date.now()+60000)throw Error('Invalid '+key+' record.');seen.add(r.id);const n=Number(key==='hydration'?r.ml:r.grams);if(!Number.isFinite(n)||n<=0||n>(key==='hydration'?5000:500))throw Error('Invalid '+key+' amount.');if(key==='proteinLog'&&!['food','whey','isolate','other'].includes(r.source))throw Error('Invalid protein source.');}}
 for(const v of s.vials||[])if(v.openedAt&&!Number.isFinite(Date.parse(v.openedAt)))throw Error('Invalid supply opening date.');if(s.circumferences===undefined)s.circumferences=[];
 if(!Array.isArray(s.circumferences)||s.circumferences.length>50000)throw Error('Invalid body measures history.');
 const seenMeasures=new Set();for(const r of s.circumferences){if(!r||!/^[A-Za-z0-9_-]{1,150}$/.test(r.id||'')||seenMeasures.has(r.id)||!Number.isFinite(Date.parse(r.at))||Date.parse(r.at)>Date.now()+60000||!r.values||typeof r.values!=='object'||Array.isArray(r.values)||!Object.keys(r.values).length)throw Error('Invalid body measures record.');seenMeasures.add(r.id);for(const [k,v] of Object.entries(r.values))if(!['waist','biceps','thigh','hips','chest','neck','calf','bicepsLeft','bicepsRight','thighLeft','thighRight','calfLeft','calfRight'].includes(k)||!Number.isFinite(Number(v))||Number(v)<=0||Number(v)>300)throw Error('Invalid circumference value.');}return s;};
C.dayTotals=(s,day)=>({water:(s.hydration||[]).filter(r=>C.isoDay(r.at)===day).reduce((n,r)=>n+Number(r.ml),0),protein:(s.proteinLog||[]).filter(r=>C.isoDay(r.at)===day).reduce((n,r)=>n+Number(r.grams),0)});
C.supplyStatus=function(v,entries){const b=v.type==='water'?{remaining:Math.max(0,(+v.volume||0)-(+v.usedMl||0)),used:+v.usedMl||0}:C.supplyBalance(v,entries);const recorded=entries.filter(e=>e.vial===v.id&&(!e.status||e.status==='taken')&&Date.parse(e.at)<=Date.now()).sort(C.entryOrder);return {state:b.remaining<=0?'empty':(v.openedAt||v.prepared||b.used>0)?'in-use':'unopened',openedAt:v.openedAt||v.prepared||(recorded[0]?C.isoDay(recorded[0].at):null)};};
if(typeof module!=='undefined')module.exports=C;
})();
