const {chromium}=require(process.env.CODEX_PRIMARY_RUNTIME_NODE_MODULES+'/playwright');
const fs=require('fs'),path=require('path'),assert=require('node:assert/strict');
const C=require('../app/src/main/assets/core.js');
if(!process.env.RETA_EUFY_FIXTURE){console.log('SKIP real Eufy fixture: set RETA_EUFY_FIXTURE to your private original CSV. No health data is included in this repository.');process.exit(0);}
const fixture=fs.readFileSync(process.env.RETA_EUFY_FIXTURE,'utf8');
const parsed=C.parseCSV(fixture);
assert.equal(parsed.headers.length,21);assert.equal(parsed.rows.length,338);assert.ok(C.isEufyCsv(parsed.headers,parsed.rows));
assert.equal(C.guessHeader('Time',parsed.rows.slice(0,3).map(r=>r[0])),'timestamp');
assert.equal(C.guessHeader('MUSCLE MASS %'), 'musclePercent');assert.equal(C.guessHeader('BONE MASS %'),'bonePercent');assert.equal(C.guessHeader('HEAD SIZE (cm)'),'headSize');
assert.equal(parsed.rows.filter(r=>{try{C.parseDate(r[0]);return false;}catch{return true;}}).length,0);
assert.equal(C.parseDate('2026-09-19T15:48:02+02:00'),'2026-09-19T13:48:02.000Z');
(async()=>{const browser=await chromium.launch({executablePath:process.env.RETA_CHROME,args:['--no-sandbox']});const p=await browser.newPage({viewport:{width:390,height:844}}),errors=[];p.on('pageerror',e=>errors.push(e.message));p.on('dialog',d=>d.accept());await p.route('http://reta.test/**',async r=>{const n=new URL(r.request().url()).pathname,f=path.join(__dirname,'../app/src/main/assets',n==='/'?'index.html':n);await r.fulfill({body:fs.readFileSync(f),contentType:f.endsWith('.js')?'application/javascript':f.endsWith('.css')?'text/css':'text/html'});});await p.goto('http://reta.test/');await p.waitForTimeout(350);await p.getByRole('button',{name:'Explore first',exact:true}).click();
await p.evaluate(text=>receiveFile('csv',text),fixture);assert.match(await p.locator('.sheet').innerText(),/Eufy CSV detected\s+21 columns found · 338 measurements/);assert.equal(await p.locator('#map-0').inputValue(),'timestamp');assert.equal(await p.locator('#map-1').inputValue(),'person');assert.equal(await p.locator('#map-9').inputValue(),'water');assert.equal(await p.locator('#csv-order').count(),0);assert.match(await p.locator('.sheet').innerText(),/Source: 2026-09-19 15:48:02/);
await p.getByRole('button',{name:'Preview import',exact:true}).click();assert.equal(await p.evaluate(()=>importData.rows.length),338);assert.equal(await p.evaluate(()=>importData.rows.every(r=>r.externalId&&r.values.weight!==undefined)),true);assert.equal(await p.evaluate(()=>importData.rows[0].values.water),49.2);assert.equal(await p.evaluate(()=>importData.rows[0].values.musclePercent),65.7);assert.equal(await p.evaluate(()=>importData.rows[0].values.bonePercent),3.4);assert.equal(await p.evaluate(()=>importData.rows[0].values.headSize),0);assert.match(await p.locator('.sheet').innerText(),/338 found · 338 new · 0 changed · 0 unchanged/);
await p.getByRole('button',{name:'Import / apply selected changes',exact:true}).click();assert.equal(await p.evaluate(()=>S.measurements.length),338);await p.evaluate(text=>receiveFile('csv',text),fixture);await p.getByRole('button',{name:'Preview import',exact:true}).click();assert.match(await p.locator('.sheet').innerText(),/338 found · 0 new · 0 changed · 338 unchanged/);assert.equal(await p.getByRole('button',{name:'Import / apply selected changes',exact:true}).count(),1);await p.getByRole('button',{name:'Import / apply selected changes',exact:true}).click();assert.equal(await p.evaluate(()=>S.measurements.length),338);assert.deepEqual(errors,[]);await browser.close();console.log('Eufy CSV import checks passed: 338 timestamps, auto mapping, all fields, preserved readings and repeat-import duplicate protection.');})().catch(e=>{console.error(e);process.exit(1)});
