package hr.mentalblue.retadnevnik;

import android.app.*;
import android.os.*;
import android.content.*;
import android.content.pm.PackageManager;
import android.content.res.Configuration;
import android.graphics.Color;
import android.hardware.biometrics.BiometricPrompt;
import android.hardware.biometrics.BiometricManager;
import android.database.Cursor;
import android.net.Uri;
import android.provider.CalendarContract;
import android.view.*;
import android.webkit.*;
import android.widget.*;
import org.json.*;
import java.io.*;
import java.nio.charset.StandardCharsets;
import java.time.*;
import java.util.*;

public class MainActivity extends Activity {
    WebView web; FrameLayout root; LinearLayout lockView; boolean unlocked=false,authenticating=false,external=false,enableAfterAuth=false,disableAfterAuth=false;
    String importKind="",exportMime="";byte[] pendingExport; boolean healthPending=false,immersive=false,barsDark=false;
    long healthStart=0,healthEnd=0;
    @Override protected void attachBaseContext(Context base){Configuration c=new Configuration(base.getResources().getConfiguration());c.setLocale(Locale.ENGLISH);super.attachBaseContext(base.createConfigurationContext(c));}
    @Override public void onCreate(Bundle state){super.onCreate(state);root=new FrameLayout(this);root.setBackgroundColor(Color.rgb(9,23,36));setContentView(root);if(Build.VERSION.SDK_INT>=30)getWindow().setDecorFitsSystemWindows(false);
        root.setOnApplyWindowInsetsListener((v,i)->{int left=i.getSystemWindowInsetLeft(),top=i.getSystemWindowInsetTop(),right=i.getSystemWindowInsetRight(),bottom=i.getSystemWindowInsetBottom();if(Build.VERSION.SDK_INT>=28&&i.getDisplayCutout()!=null){DisplayCutout cutout=i.getDisplayCutout();left=Math.max(left,cutout.getSafeInsetLeft());top=Math.max(top,cutout.getSafeInsetTop());right=Math.max(right,cutout.getSafeInsetRight());bottom=Math.max(bottom,cutout.getSafeInsetBottom());}root.setPadding(left,top,right,bottom);return i.consumeSystemWindowInsets();});root.requestApplyInsets();
        lockView=new LinearLayout(this);lockView.setOrientation(1);lockView.setGravity(Gravity.CENTER);lockView.setPadding(40,40,40,40);lockView.setBackgroundColor(Color.rgb(9,23,36));
        TextView title=new TextView(this);title.setText("Reta Log");title.setTextSize(34);title.setTextColor(Color.WHITE);lockView.addView(title);TextView sub=new TextView(this);sub.setText("Your personal journal. Privately yours.");sub.setTextColor(Color.rgb(159,184,201));sub.setPadding(0,20,0,40);lockView.addView(sub);Button unlock=new Button(this);unlock.setText("Unlock Reta Log");unlock.setOnClickListener(v->authenticate());lockView.addView(unlock);root.addView(lockView,new FrameLayout.LayoutParams(-1,-1));
        updateSecure();if(!locked()){unlocked=true;showApp();}}
    boolean locked(){return getSharedPreferences("privacy",0).getBoolean("locked",false);}
    void updateSecure(){if(locked())getWindow().addFlags(WindowManager.LayoutParams.FLAG_SECURE);else getWindow().clearFlags(WindowManager.LayoutParams.FLAG_SECURE);}
    void showApp(){if(web==null){web=new WebView(this);web.setBackgroundColor(Color.rgb(9,23,36));web.getSettings().setJavaScriptEnabled(true);web.getSettings().setTextZoom(Math.round(getResources().getConfiguration().fontScale*100));web.getSettings().setDomStorageEnabled(false);web.getSettings().setAllowFileAccess(false);web.getSettings().setAllowContentAccess(false);web.getSettings().setMixedContentMode(WebSettings.MIXED_CONTENT_NEVER_ALLOW);web.addJavascriptInterface(new Bridge(),"Native");web.setWebChromeClient(new WebChromeClient(){@Override public boolean onJsConfirm(WebView v,String url,String message,JsResult result){new AlertDialog.Builder(MainActivity.this).setTitle("Reta Log").setMessage(message).setPositiveButton("Confirm",(d,w)->result.confirm()).setNegativeButton("Cancel",(d,w)->result.cancel()).setOnCancelListener(d->result.cancel()).show();return true;}});web.setWebViewClient(new WebViewClient(){@Override public WebResourceResponse shouldInterceptRequest(WebView view,WebResourceRequest request){Uri u=request.getUrl();if("https".equals(u.getScheme())&&"app.retalog.local".equals(u.getHost())){String path=u.getPath();if(path!=null&&path.startsWith("/assets/")&&!path.contains("..")){String name=path.substring(8);try{String mime=name.endsWith(".js")?"application/javascript":name.endsWith(".css")?"text/css":name.endsWith(".png")?"image/png":"text/html";return new WebResourceResponse(mime,name.endsWith(".png")?null:"UTF-8",getAssets().open(name));}catch(Exception e){return new WebResourceResponse("text/plain","UTF-8",404,"Not found",new java.util.HashMap<String,String>(),new java.io.ByteArrayInputStream(new byte[0]));}}}return new WebResourceResponse("text/plain","UTF-8",403,"Blocked",new java.util.HashMap<String,String>(),new java.io.ByteArrayInputStream(new byte[0]));}@Override public boolean shouldOverrideUrlLoading(WebView v,WebResourceRequest r){Uri u=r.getUrl();if("https".equals(u.getScheme())&&"app.retalog.local".equals(u.getHost()))return false;if("https".equals(u.getScheme())){try{external=true;startActivity(new Intent(Intent.ACTION_VIEW,u));}catch(Exception e){external=false;event("error","Cannot open this link.");}}return true;}});root.addView(web,0,new FrameLayout.LayoutParams(-1,-1));web.loadUrl("https://app.retalog.local/assets/index.html");}web.setVisibility(View.VISIBLE);lockView.setVisibility(View.GONE);}
    void showLock(){unlocked=false;if(web!=null)web.setVisibility(View.INVISIBLE);lockView.setVisibility(View.VISIBLE);lockView.bringToFront();}
    @Override protected void onPause(){super.onPause();if(locked()&&!authenticating)showLock();}
    @Override protected void onResume(){super.onResume();if(locked()&&!unlocked&&!authenticating&&!external)authenticate();if(access())event("resume","");}
    void authenticate(){if(authenticating)return;KeyguardManager km=getSystemService(KeyguardManager.class);if(!km.isDeviceSecure()){event("error","Set a screen lock on your phone first.");enableAfterAuth=false;disableAfterAuth=false;return;}authenticating=true;
        if(Build.VERSION.SDK_INT>=30){new BiometricPrompt.Builder(this).setTitle("Unlock Reta Log").setSubtitle("Your health journal stays private").setAllowedAuthenticators(BiometricManager.Authenticators.BIOMETRIC_STRONG|BiometricManager.Authenticators.DEVICE_CREDENTIAL).build().authenticate(new CancellationSignal(),getMainExecutor(),new BiometricPrompt.AuthenticationCallback(){@Override public void onAuthenticationSucceeded(BiometricPrompt.AuthenticationResult r){authSuccess();}@Override public void onAuthenticationError(int code,CharSequence msg){authenticating=false;enableAfterAuth=false;disableAfterAuth=false;if(locked())showLock();else{unlocked=true;showApp();}event("lock","Authentication cancelled or unavailable.");}});
        }else{Intent i=km.createConfirmDeviceCredentialIntent("Unlock Reta Log","Confirm your device credential");startActivityForResult(i,90);}}
    void authSuccess(){authenticating=false;if(enableAfterAuth)getSharedPreferences("privacy",0).edit().putBoolean("locked",true).commit();if(disableAfterAuth)getSharedPreferences("privacy",0).edit().putBoolean("locked",false).commit();enableAfterAuth=false;disableAfterAuth=false;unlocked=true;updateSecure();showApp();event("lock",locked()?"Journal unlocked. Biometric lock is enabled.":"Journal unlocked.");}
    void event(String name,Object data){runOnUiThread(()->{if(web!=null){String json=(data instanceof JSONObject||data instanceof JSONArray)?data.toString():JSONObject.quote(String.valueOf(data));web.evaluateJavascript("window.nativeEvent && window.nativeEvent("+JSONObject.quote(name)+","+json+")",null);}});}
    boolean access(){return !locked()||unlocked;}
    class Bridge {
        @JavascriptInterface public float fontScale(){return getResources().getConfiguration().fontScale;}
        @JavascriptInterface public String deviceFormats(){try{return new JSONObject().put("dateOrder",Locale.getDefault().getCountry().equals("US")?"MDY":"DMY").put("timeFormat",android.text.format.DateFormat.is24HourFormat(MainActivity.this)?"24":"12").toString();}catch(Exception e){return "{}";}}
        @JavascriptInterface public void setImmersive(boolean value){runOnUiThread(()->{immersive=value;applyBars();});}
        @JavascriptInterface public void setHealthRange(long start,long end){if(!access())return;healthStart=start;healthEnd=end;}
        @JavascriptInterface public void queryCalendarRange(String id,long start,long end){if(!access())return;new Thread(()->calendarRange(id,start,end)).start();}
        @JavascriptInterface public String readStore(){if(!access())return "";String value=getPreferences(0).getString("store",null);if(value!=null)return value;try{return new JSONObject().put("schema",2).put("entries",new JSONArray(getPreferences(0).getString("entries","[]"))).toString();}catch(Exception e){return "INVALID_DATA";}}
        @JavascriptInterface public boolean saveStore(String raw){if(!access())return false;try{JSONObject s=new JSONObject(raw);if(s.getJSONArray("entries").length()>20000||raw.length()>12000000)return false;return getPreferences(0).edit().putString("store",raw).commit();}catch(Exception e){return false;}}
        @JavascriptInterface public void setBars(boolean dark){runOnUiThread(()->{barsDark=dark;applyBars();});}
        @JavascriptInterface public void haptic(){runOnUiThread(()->{if(web!=null)web.performHapticFeedback(HapticFeedbackConstants.CLOCK_TICK);});}
        @JavascriptInterface public boolean isLockEnabled(){return locked();}
        @JavascriptInterface public void setLockEnabled(boolean value){if(!access())return;runOnUiThread(()->{enableAfterAuth=value;disableAfterAuth=!value;authenticate();});}
        @JavascriptInterface public void lockNow(){runOnUiThread(()->{if(locked()){showLock();authenticate();}else event("error","Enable biometric lock in Settings first.");});}
        @JavascriptInterface public void openFile(String kind){if(!access())return;runOnUiThread(()->{importKind=kind;external=true;try{startActivityForResult(new Intent(Intent.ACTION_OPEN_DOCUMENT).addCategory(Intent.CATEGORY_OPENABLE).setType("*/*"),10);}catch(Exception e){external=false;event("error","No file picker available.");}});}
        @JavascriptInterface public void exportText(String name,String mime,String text){if(!access())return;runOnUiThread(()->export(name,mime,text.getBytes(StandardCharsets.UTF_8)));}
        @JavascriptInterface public void exportReport(String raw){if(!access())return;runOnUiThread(()->{try{JSONObject data=new JSONObject(raw);export("Reta-Log-report.pdf","application/pdf",data.has("reportTitle")?ReportSummary.create(data):Report.create(data));}catch(Exception e){event("error","Could not create the PDF: "+e.getMessage());}});}
        @JavascriptInterface public void openCalendar(){if(!access())return;runOnUiThread(()->{if(checkSelfPermission("android.permission.READ_CALENDAR")!=PackageManager.PERMISSION_GRANTED)requestPermissions(new String[]{"android.permission.READ_CALENDAR"},20);else listCalendars();});}
        @JavascriptInterface public void queryCalendar(String id,int days){if(!access())return;new Thread(()->calendarEvents(id,days)).start();}
        @JavascriptInterface public void connectHealth(){if(!access())return;runOnUiThread(()->{if(Build.VERSION.SDK_INT<34){event("error","Health Connect integration in this build requires Android 14 or newer. Use CSV import on older Android versions.");return;}new AlertDialog.Builder(MainActivity.this).setTitle("Read Health Connect").setMessage("Read available weight and body-composition history on this device, then review before importing. Only data shared by your source apps can appear. Access may require enabling this app in Health Connect settings.").setNegativeButton("Cancel",null).setPositiveButton("Continue",(d,w)->{try{requestPermissions(HealthReader.permissions(MainActivity.this),30);}catch(Exception e){event("error","Health Connect permission request failed: "+e.getMessage());}}).show();});}
        @JavascriptInterface public void scheduleReminders(String raw){if(!access())return;runOnUiThread(()->{try{ReminderReceiver.configure(MainActivity.this,new JSONArray(raw));if(Build.VERSION.SDK_INT>=33&&checkSelfPermission("android.permission.POST_NOTIFICATIONS")!=PackageManager.PERMISSION_GRANTED)requestPermissions(new String[]{"android.permission.POST_NOTIFICATIONS"},40);}catch(Exception e){event("error","Reminder scheduling failed: "+e.getMessage());}});}
    }
    void applyBars(){getWindow().setStatusBarColor(barsDark?Color.rgb(9,23,36):Color.rgb(241,245,247));getWindow().setNavigationBarColor(barsDark?Color.rgb(9,23,36):Color.WHITE);
        if(Build.VERSION.SDK_INT>=30){WindowInsetsController c=getWindow().getInsetsController();if(c!=null){c.setSystemBarsBehavior(WindowInsetsController.BEHAVIOR_SHOW_TRANSIENT_BARS_BY_SWIPE);if(immersive)c.hide(WindowInsets.Type.systemBars());else c.show(WindowInsets.Type.systemBars());c.setSystemBarsAppearance(barsDark?0:WindowInsetsController.APPEARANCE_LIGHT_STATUS_BARS|WindowInsetsController.APPEARANCE_LIGHT_NAVIGATION_BARS,WindowInsetsController.APPEARANCE_LIGHT_STATUS_BARS|WindowInsetsController.APPEARANCE_LIGHT_NAVIGATION_BARS);}}
        else getWindow().getDecorView().setSystemUiVisibility(View.SYSTEM_UI_FLAG_LAYOUT_STABLE|View.SYSTEM_UI_FLAG_LAYOUT_FULLSCREEN|View.SYSTEM_UI_FLAG_LAYOUT_HIDE_NAVIGATION|(immersive?View.SYSTEM_UI_FLAG_IMMERSIVE_STICKY|View.SYSTEM_UI_FLAG_FULLSCREEN|View.SYSTEM_UI_FLAG_HIDE_NAVIGATION:barsDark?0:View.SYSTEM_UI_FLAG_LIGHT_STATUS_BAR|View.SYSTEM_UI_FLAG_LIGHT_NAVIGATION_BAR));root.requestApplyInsets();}
    void calendarRange(String id,long start,long end){try{
        if(end<=start||start<0)throw new Exception("Invalid calendar range");
        Uri.Builder builder=CalendarContract.Instances.CONTENT_URI.buildUpon();ContentUris.appendId(builder,start);ContentUris.appendId(builder,end);
        JSONArray out=new JSONArray();boolean limited=false;
        String[] columns={"event_id","title","description","begin","allDay",CalendarContract.Events.ORIGINAL_ID,CalendarContract.Events.ORIGINAL_INSTANCE_TIME,CalendarContract.Events.RRULE,CalendarContract.Events.RDATE};
        try(Cursor c=getContentResolver().query(builder.build(),columns,"calendar_id=?",new String[]{id},"begin ASC")){
            if(c!=null)while(c.moveToNext()){
                long t=c.getLong(3);if(t<start||t>=end)continue;if(out.length()>=10000){limited=true;break;}
                String event=c.isNull(5)?c.getString(0):c.getString(5);
                boolean repeats=!c.isNull(6)||(!c.isNull(7)&&!c.getString(7).isEmpty())||(!c.isNull(8)&&!c.getString(8).isEmpty());
                String occurrence=repeats?String.valueOf(c.isNull(6)?t:c.getLong(6)):"single";
                out.put(new JSONObject().put("title",c.getString(1)==null?"":c.getString(1)).put("description",c.getString(2)==null?"":c.getString(2)).put("at",Instant.ofEpochMilli(t).toString()).put("allDay",c.getInt(4)==1).put("externalId","calendar:"+id+":"+event+":"+occurrence).put("legacyExternalId","calendar:"+id+":"+c.getString(0)+":"+t));
            }
        }
        event("calendarRange",new JSONObject().put("rows",out).put("limited",limited));
    }catch(Exception e){event("error","Calendar read failed: "+e.getMessage());}}
    void export(String name,String mime,byte[] bytes){pendingExport=bytes;exportMime=mime;external=true;try{startActivityForResult(new Intent(Intent.ACTION_CREATE_DOCUMENT).addCategory(Intent.CATEGORY_OPENABLE).setType(mime).putExtra(Intent.EXTRA_TITLE,name),11);}catch(Exception e){pendingExport=null;external=false;event("error","Could not open a save destination.");}}
    void listCalendars(){new Thread(()->{JSONArray out=new JSONArray();try(Cursor c=getContentResolver().query(CalendarContract.Calendars.CONTENT_URI,new String[]{"_id","calendar_displayName","account_name"},"sync_events=1",null,null)){if(c!=null)while(c.moveToNext())out.put(new JSONObject().put("id",c.getString(0)).put("name",c.getString(1)).put("account",c.getString(2)));event("calendars",out);}catch(Exception e){event("error","Calendar read failed: "+e.getMessage());}}).start();}
    void calendarEvents(String calendarId,int days){try{if(days<1||days>3660)throw new Exception("Invalid date range");long end=System.currentTimeMillis(),start=end-days*86400000L;Uri.Builder builder=CalendarContract.Instances.CONTENT_URI.buildUpon();ContentUris.appendId(builder,start);ContentUris.appendId(builder,end);JSONArray out=new JSONArray();try(Cursor c=getContentResolver().query(builder.build(),new String[]{"event_id","title","description","begin","allDay"},"calendar_id=?",new String[]{calendarId},"begin ASC")){if(c!=null)while(c.moveToNext()){String title=c.getString(1)==null?"":c.getString(1),description=c.getString(2)==null?"":c.getString(2);if(!java.util.regex.Pattern.compile("(?i)\\b(reta|retatrutid|retatrutide)\\b").matcher(title+" "+description).find())continue;long t=c.getLong(3);out.put(new JSONObject().put("title",title).put("description",description).put("at",Instant.ofEpochMilli(t).toString()).put("allDay",c.getInt(4)==1).put("externalId","calendar:"+calendarId+":"+c.getString(0)+":"+t));if(out.length()>=2000)break;}}event("calendar",out);}catch(Exception e){event("error","Calendar import failed: "+e.getMessage());}}
    @Override public void onRequestPermissionsResult(int request,String[] permissions,int[] results){super.onRequestPermissionsResult(request,permissions,results);if(request==20){if(results.length>0&&results[0]==PackageManager.PERMISSION_GRANTED)listCalendars();else event("error","Calendar access was not granted.");}if(request==30&&Build.VERSION.SDK_INT>=34){new HealthReader(this,(data)->event("health",data),healthStart,healthEnd).read();}if(request==40&&results.length>0&&results[0]!=PackageManager.PERMISSION_GRANTED)event("error","Notifications are disabled. Enable them in Android settings for reminders.");}
    @Override protected void onActivityResult(int request,int result,Intent data){super.onActivityResult(request,result,data);if(request==90){if(result==RESULT_OK)authSuccess();else{authenticating=false;enableAfterAuth=false;disableAfterAuth=false;}return;}external=false;
        if(result!=RESULT_OK||data==null||data.getData()==null){pendingExport=null;return;}
        try{if(request==10){ByteArrayOutputStream out=new ByteArrayOutputStream();try(InputStream in=getContentResolver().openInputStream(data.getData())){if(in==null)throw new IOException("Cannot read file");byte[] b=new byte[8192];int n;while((n=in.read(b))!=-1){out.write(b,0,n);if(out.size()>12000000)throw new IOException("File exceeds 12 MB");}}byte[] bytes=out.toByteArray();String text;if(bytes.length>=2&&bytes[0]==(byte)0xff&&bytes[1]==(byte)0xfe)text=new String(bytes,2,bytes.length-2,"UTF-16LE");else text=new String(bytes,StandardCharsets.UTF_8);event("file",new JSONObject().put("kind",importKind).put("text",text));}else if(request==11&&pendingExport!=null){try(OutputStream out=getContentResolver().openOutputStream(data.getData(),"wt")){if(out==null)throw new IOException("Cannot open destination");out.write(pendingExport);}pendingExport=null;event("saved","File saved.");}}catch(Exception e){pendingExport=null;event("error",e.getMessage());}}
    @Override public void onBackPressed(){if(web!=null&&access())web.evaluateJavascript("goBack()",null);else super.onBackPressed();}
}
