package hr.mentalblue.retadnevnik;
import android.app.*;
import android.content.*;
import android.os.Build;
import org.json.*;
import java.time.*;

public class ReminderReceiver extends BroadcastReceiver {
    static final String CHANNEL="reta_private_reminders";
    static PendingIntent pending(Context c,String id){return PendingIntent.getBroadcast(c,id.hashCode(),new Intent(c,ReminderReceiver.class).setAction("reminder:"+id).putExtra("id",id),PendingIntent.FLAG_UPDATE_CURRENT|PendingIntent.FLAG_IMMUTABLE);}
    static void configure(Context c,JSONArray reminders)throws Exception{JSONArray old=new JSONArray(c.getSharedPreferences("reminders",0).getString("items","[]"));AlarmManager am=c.getSystemService(AlarmManager.class);for(int i=0;i<old.length();i++)am.cancel(pending(c,old.getJSONObject(i).getString("id")));c.getSharedPreferences("reminders",0).edit().putString("items",reminders.toString()).commit();for(int i=0;i<reminders.length();i++)schedule(c,reminders.getJSONObject(i));}
    static void schedule(Context c,JSONObject r)throws Exception{if(!r.optBoolean("enabled"))return;String[] hh=r.getString("time").split(":");ZonedDateTime now=ZonedDateTime.now(),next=null;JSONArray days=r.getJSONArray("days");for(int add=0;add<=7;add++){ZonedDateTime t=now.plusDays(add).withHour(Integer.parseInt(hh[0])).withMinute(Integer.parseInt(hh[1])).withSecond(0).withNano(0);if(!r.optString("until", "").isEmpty()&&!r.optString("until").equals("null")&&t.toLocalDate().isAfter(LocalDate.parse(r.getString("until"))))break;int day=t.getDayOfWeek().getValue()%7;for(int i=0;i<days.length();i++)if(day==days.getInt(i)&&t.isAfter(now)){next=t;break;}if(next!=null)break;}if(next!=null)c.getSystemService(AlarmManager.class).setAndAllowWhileIdle(AlarmManager.RTC_WAKEUP,next.toInstant().toEpochMilli(),pending(c,r.getString("id")));}
    @Override public void onReceive(Context c,Intent intent){try{JSONArray items=new JSONArray(c.getSharedPreferences("reminders",0).getString("items","[]"));if(Intent.ACTION_BOOT_COMPLETED.equals(intent.getAction())||Intent.ACTION_TIME_CHANGED.equals(intent.getAction())||Intent.ACTION_TIMEZONE_CHANGED.equals(intent.getAction())){for(int i=0;i<items.length();i++)schedule(c,items.getJSONObject(i));return;}String id=intent.getStringExtra("id");for(int i=0;i<items.length();i++){JSONObject r=items.getJSONObject(i);if(r.getString("id").equals(id)&&r.optBoolean("enabled")&&(r.optString("until", "").isEmpty()||r.optString("until").equals("null")||!LocalDate.now().isAfter(LocalDate.parse(r.getString("until"))))){NotificationManager nm=c.getSystemService(NotificationManager.class);NotificationChannel channel=new NotificationChannel(CHANNEL,"Private reminders",NotificationManager.IMPORTANCE_DEFAULT);channel.setLockscreenVisibility(Notification.VISIBILITY_PRIVATE);nm.createNotificationChannel(channel);PendingIntent open=PendingIntent.getActivity(c,0,new Intent(c,MainActivity.class),PendingIntent.FLAG_UPDATE_CURRENT|PendingIntent.FLAG_IMMUTABLE);Notification n=new Notification.Builder(c,CHANNEL).setSmallIcon(android.R.drawable.ic_dialog_info).setContentTitle("Your reminder is ready").setContentText("Open your personal journal.").setContentIntent(open).setAutoCancel(true).setVisibility(Notification.VISIBILITY_PRIVATE).build();try{nm.notify(id.hashCode(),n);}catch(SecurityException ignored){}schedule(c,r);break;}}}catch(Exception ignored){}}
}
