const {chromium}=require(process.env.CODEX_PRIMARY_RUNTIME_NODE_MODULES+'/playwright');const fs=require('fs'),path=require('path'),assert=require('node:assert/strict');
(async()=>{const browser=await chromium.launch({executablePath:process.env.RETA_CHROME,args:['--no-sandbox']});const p=await browser.newPage({viewport:{width:412,height:860}}),errors=[];p.on('pageerror',e=>errors.push(e.message));p.on('dialog',d=>d.accept());await p.route('http://reta.test/**',async r=>{const n=new URL(r.request().url()).pathname,f=path.join(__dirname,'../app/src/main/assets',n==='/'?'index.html':n);await r.fulfill({body:fs.readFileSync(f),contentType:f.endsWith('.js')?'application/javascript':f.endsWith('.css')?'text/css':f.endsWith('.png')?'image/png':'text/html'});});await p.goto('http://reta.test/');await p.waitForTimeout(400);await p.getByRole('button',{name:'Explore first',exact:true}).click();
await p.evaluate(()=>{S.settings.theme='dark';S.profile={name:'Demo',sex:'male',height:173,age:52,weight:88,target:80,activity:1.375,deficit:15,macroMode:'auto',resistance:true,proteinBasis:'current'};S.vials=[{id:'v1',name:'Cartridge A',type:'cartridge',mg:10},{id:'empty',name:'Used vial',type:'vial',mg:1},{id:'water',name:'Water bottle',type:'water',volume:10,usedMl:2,mg:0}];S.entries=[{id:'a',at:'2026-09-03T10:00:00Z',mg:1,vial:'v1'},{id:'b',at:'2026-09-08T10:00:00Z',mg:1.5,vial:'v1'},{id:'c',at:'2026-09-10T10:00:00Z',mg:1,vial:'empty'}];S.measurements=[{id:'m1',at:'2026-09-01T10:00:00Z',values:{weight:93}},{id:'m2',at:'2026-09-15T10:00:00Z',values:{weight:90}},{id:'m3',at:'2026-09-15T18:00:00Z',values:{weight:92}},{id:'m4',at:'2026-09-17T10:00:00Z',values:{weight:89}}];persist();render()});
assert.match(await p.locator('main').innerText(),/Weekly dose history/);const range=await p.locator('.hero').innerText();await p.getByRole('button',{name:'Previous 7 days',exact:true}).click();assert.notEqual(await p.locator('.hero').innerText(),range);await p.screenshot({path:'/tmp/reta16-overview.png',fullPage:true});
await p.evaluate(()=>navigate('inventory'));assert.match(await p.locator('main').innerText(),/7.5 mg/);assert.match(await p.locator('main').innerText(),/8 mL/);assert.equal(await p.locator('details[open]').count(),0);await p.locator('#supply-v1 summary').click();assert.equal(await p.locator('#supply-v1').getAttribute('open'),'');await p.locator('#supply-v1').getByRole('button',{name:'Duplicate supply'}).click();assert.equal(await p.locator('#v-prepared').inputValue(),'');await p.getByRole('button',{name:'Save supply',exact:true}).click();assert.equal(await p.evaluate(()=>S.vials.length),4);assert.equal(await p.evaluate(()=>S.entries.length),3);assert.match(await p.locator('main').innerText(),/17.5 mg/);
await p.evaluate(()=>{navigate('journal');openSupply('v1','a')});await p.waitForTimeout(50);assert.equal(await p.evaluate(()=>page),'inventory');await p.evaluate(()=>goBack());await p.waitForTimeout(50);assert.equal(await p.evaluate(()=>page),'journal');assert.equal(await p.evaluate(()=>document.activeElement.id),'entry-a');
await p.evaluate(()=>editEntry('a'));assert.equal(await p.locator('#entry-vial option[value="water"]').count(),0);await p.evaluate(()=>closeModal());
await p.evaluate(()=>editProfile());assert.equal(await p.locator('#p-mode').inputValue(),'auto');assert.ok(await p.locator('#p-protein').evaluate(e=>e.readOnly));await p.locator('#p-keto').check();await p.getByRole('button',{name:'Save profile',exact:true}).click();assert.ok(await p.evaluate(()=>S.profile.keto));assert.ok(await p.evaluate(()=>S.profile.carbs<=30));assert.ok(await p.evaluate(()=>S.profile.protein>100));
await p.evaluate(()=>{navigate('insights')});assert.equal(await p.locator('#weight-chart').count(),1);await p.locator('#weight-mode-inline').selectOption('latest');assert.equal(await p.evaluate(()=>selectedWeightRecords().find(r=>new Date(r.at).getDate()===15).values.weight),92);await p.locator('#weight-mode-inline').selectOption('average');assert.equal(await p.evaluate(()=>selectedWeightRecords().find(r=>new Date(r.at).getDate()===15).values.weight),91);await p.evaluate(()=>{weightChart.picked=Core.dayKey('2026-09-15T12:00:00Z');drawWeight()});assert.match(await p.locator('#weight-value').innerText(),/91 kg/);const span=await p.evaluate(()=>weightChart.b-weightChart.a);await p.getByRole('button',{name:'Zoom weight in',exact:true}).click();assert.ok(await p.evaluate(s=>weightChart.b-weightChart.a<s,span));await p.getByRole('button',{name:'Full weight chart',exact:true}).click();await p.screenshot({path:'/tmp/reta16-weight.png'});await p.evaluate(()=>goBack());
await p.evaluate(()=>{navigate('settings');setSetting('color','#ffee44');setSetting('background','#ffee44')});assert.ok(await p.evaluate(()=>Core.contrast(S.settings.color,getComputedStyle(document.documentElement).getPropertyValue('--accent-ink').trim())>=4.5));await p.screenshot({path:'/tmp/reta16-appearance.png',fullPage:true});
await p.evaluate(()=>{navigate('reminders');editReminder()});await p.locator('#r-day-1').check();await p.locator('#r-end-mode').selectOption('date');await p.locator('#r-until').fill('2027-01-01');await p.getByRole('button',{name:'Save reminder',exact:true}).click();assert.equal(await p.evaluate(()=>S.reminders[0].until),'2027-01-01');await p.evaluate(()=>editReminder(S.reminders[0].id));await p.locator('#r-end-mode').selectOption('never');await p.getByRole('button',{name:'Save reminder',exact:true}).click();assert.equal(await p.evaluate(()=>S.reminders[0].until),null);
await p.evaluate(()=>{S.profile.sex='female';editEntry()});assert.match(await p.locator('#torso svg').getAttribute('aria-label'),/Female/);await p.evaluate(()=>closeModal());await p.evaluate(()=>editFeeling());assert.equal(await p.locator('textarea#feeling-note').count(),1);await p.evaluate(()=>closeModal());await p.evaluate(()=>navigate('learn'));assert.equal(await p.locator('img.equipment-photo').evaluate(e=>e.naturalWidth>0),true);
for(const v of ['overview','journal','inventory','profile','settings','learn','reminders','insights']){await p.evaluate(v=>navigate(v),v);assert.equal(await p.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false,v+' overflow');}
// 1.6.1 regressions: one-row nav, controlled appearance, collapsible log, anchored journey.
for(const width of [320,360,412]){await p.setViewportSize({width,height:860});await p.evaluate(()=>navigate('overview'));assert.ok(await p.locator('nav button').evaluateAll(es=>new Set(es.map(e=>e.getBoundingClientRect().top)).size===1));assert.ok(await p.locator('nav button span').evaluateAll(es=>es.every(e=>e.scrollWidth<=e.parentElement.clientWidth)));}
await p.setViewportSize({width:390,height:860});
await p.evaluate(()=>{navigate('settings');S.settings.background='#ffee44';render()});
assert.equal(await p.getByText('More colour. More clarity.',{exact:true}).count(),0);assert.equal(await p.locator('#custom-bg').count(),0);
for(const theme of ['light','dark','system','midnight','forest','slate'])for(const color of ['#087e88','#247957','#7858aa','#566474','#44ccff','#96ff40','#ffee44']){await p.evaluate(({theme,color})=>{S.settings.theme=theme;S.settings.color=color;render();},{theme,color});assert.ok(await p.evaluate(()=>{const s=getComputedStyle(document.body),r=getComputedStyle(document.documentElement),c=r.getPropertyValue('--accent').trim();return Core.contrast(c,s.getPropertyValue('--card').trim())>=4.5&&Core.contrast(c,r.getPropertyValue('--accent-ink').trim())>=4.5;}),theme+' '+color);}
await p.evaluate(()=>{setSetting('theme','slate');setSetting('color','#ffee44')});await p.screenshot({path:'/tmp/reta161-settings.png',fullPage:true});
await p.evaluate(()=>navigate('journal'));assert.equal(await p.locator('.journal-details[open]').count(),0);assert.equal(await p.locator('#entry-a .supply-link').isVisible(),false);await p.getByRole('button',{name:'Open all',exact:true}).click();assert.equal(await p.locator('.journal-details[open]').count(),3);await p.getByRole('button',{name:'Close all',exact:true}).click();assert.equal(await p.locator('.journal-details[open]').count(),0);await p.locator('#entry-a summary').click();assert.ok(await p.locator('#entry-a .supply-link').isVisible());await p.locator('#entry-a .supply-link').click();await p.evaluate(()=>goBack());await p.waitForTimeout(100);assert.ok(await p.locator('#entry-a .supply-link').isVisible());await p.screenshot({path:'/tmp/reta161-journal.png',fullPage:true});
await p.evaluate(()=>{navigate('overview');weekIndex=0;render()});assert.match(await p.locator('main').innerText(),/Thu, 3 Sept 2026 — Wed, 9 Sept 2026/);await p.screenshot({path:'/tmp/reta161-overview.png',fullPage:true});
await p.evaluate(()=>{S.feelings=[{id:'f',at:'2026-09-03T12:00:00Z',values:{},note:''}];navigate('insights')});assert.match(await p.locator('main').innerText(),/Daily check-ins[\s\S]*Thu, 3 Sept 2026/);assert.equal(await p.evaluate(()=>Core.progress(S.entries,selectedWeightRecords()).firstWeight),91);await p.evaluate(()=>editFeeling());assert.match(await p.locator('#feeling-day').innerText(),/Mon|Tue|Wed|Thu|Fri|Sat|Sun/);await p.evaluate(()=>closeModal());
await p.reload();assert.equal(await p.evaluate(()=>S.vials.length),4);assert.equal(await p.evaluate(()=>S.settings.weightMode),'average');assert.deepEqual(errors,[]);await browser.close();console.log('1.6.1 UI checks passed: navigation widths, all theme/accent contrasts, journal accordion/return, first-dose journey and weekday dates; navigation, weekly windows, inventory, copy, water, nutrition, weight chart/preference, contrast, reminder end date, female torso and persistence.');})().catch(e=>{console.error(e);process.exit(1)});
