const {chromium}=require(process.env.CODEX_PRIMARY_RUNTIME_NODE_MODULES+'/playwright');const fs=require('fs'),path=require('path'),assert=require('node:assert/strict');
(async()=>{const browser=await chromium.launch({executablePath:process.env.RETA_CHROME,args:['--no-sandbox']});const p=await browser.newPage({viewport:{width:390,height:844}}),errors=[];p.on('pageerror',e=>errors.push(e.message));p.on('dialog',d=>d.accept());await p.route('http://reta.test/**',async r=>{const n=new URL(r.request().url()).pathname,f=path.join(__dirname,'../app/src/main/assets',n==='/'?'index.html':n);await r.fulfill({body:fs.readFileSync(f),contentType:f.endsWith('.js')?'application/javascript':f.endsWith('.css')?'text/css':f.endsWith('.png')?'image/png':'text/html'});});await p.goto('http://reta.test/');await p.waitForTimeout(450);await p.getByRole('button',{name:'Explore first',exact:true}).click();assert.deepEqual(errors,[]);assert.equal(await p.locator('.legal-notice').count(),1);await p.getByRole('button',{name:'Understood',exact:true}).click();
await p.evaluate(()=>{S.settings.theme='dark';S.settings.depth=true;S.profile={name:'Demo',sex:'male',height:173,age:52,weight:88,target:80,activity:1.375,deficit:15,macroMode:'auto',resistance:true,proteinBasis:'current'};S.vials=[{id:'v1',name:'Cartridge A',type:'cartridge',mg:10},{id:'empty',name:'Used vial',type:'vial',mg:1},{id:'new',name:'Unopened vial',type:'vial',mg:10},{id:'pen1',name:'Disposable pen',type:'pen',mg:8},{id:'water',name:'Water bottle',type:'water',volume:10,usedMl:2,mg:0}];S.entries=[{id:'a',at:'2026-09-03T10:00:00Z',mg:1,vial:'v1'},{id:'b',at:'2026-09-08T10:00:00Z',mg:1.5,vial:'v1'},{id:'c',at:'2026-09-10T10:00:00Z',mg:1,vial:'empty'}];S.measurements=[{id:'m1',at:'2026-09-01T10:00:00Z',values:{weight:93}},{id:'m2',at:'2026-09-15T10:00:00Z',values:{weight:90}},{id:'m3',at:'2026-09-15T18:00:00Z',values:{weight:92}},{id:'m4',at:'2026-09-17T10:00:00Z',values:{weight:89}}];persist();render()});
assert.ok(await p.locator('body').evaluate(e=>e.classList.contains('depth')));await p.getByRole('button',{name:'Open weight chart',exact:true}).click();assert.equal(await p.evaluate(()=>page),'insights');assert.ok(await p.evaluate(()=>!!weightChart.picked));await p.evaluate(()=>goBack());assert.equal(await p.evaluate(()=>page),'overview');
await p.evaluate(()=>navigate('inventory'));assert.equal(await p.locator('.supply-group').count(),4);assert.ok(await p.locator('#supply-v1').evaluate(e=>e.classList.contains('supply-in-use')));assert.ok(await p.locator('#supply-new').evaluate(e=>e.classList.contains('supply-unopened')));assert.ok(await p.locator('#supply-empty').evaluate(e=>e.classList.contains('supply-empty')));await p.locator('#supply-v1 summary').click();assert.equal(await p.getByRole('button',{name:'Edit supply',exact:true}).first().innerText(),'');await p.locator('#supply-v1').getByRole('button',{name:'Duplicate supply',exact:true}).click();assert.equal(await p.locator('#v-opened').inputValue(),'');await p.getByRole('button',{name:'Save supply',exact:true}).click();assert.equal(await p.evaluate(()=>S.vials.length),6);assert.equal(await p.evaluate(()=>status17(S.vials.at(-1)).state),'unopened');
await p.evaluate(()=>markOpened('pen1'));await p.getByRole('button',{name:'Save supply',exact:true}).click();assert.equal(await p.evaluate(()=>status17(S.vials.find(v=>v.id==='pen1')).state),'in-use');assert.doesNotMatch(await p.locator('main').innerText(),/Invalid Date/);await p.screenshot({path:'/tmp/reta17-inventory.png',fullPage:true});
await p.evaluate(()=>navigate('journal'));await p.locator('#entry-a summary').click();await p.locator('#entry-a .supply-link').click();assert.equal(await p.evaluate(()=>page),'inventory');await p.evaluate(()=>goBack());await p.waitForTimeout(80);assert.equal(await p.evaluate(()=>document.activeElement.id),'entry-a');assert.ok(await p.locator('#entry-a .supply-link').isVisible());
await p.evaluate(()=>dailySettings());await p.locator('#water-target').fill('2000');await p.locator('#water-enabled').check();await p.locator('#protein-enabled').check();await p.getByRole('button',{name:'Save tracking settings',exact:true}).click();await p.evaluate(()=>quickWater(250));assert.equal(await p.evaluate(()=>Core.dayTotals(S,Core.isoDay(Date.now())).water),250);await p.evaluate(()=>undoLast());assert.equal(await p.evaluate(()=>S.hydration.length),0);await p.evaluate(()=>quickWater(500));
await p.evaluate(()=>editDaily('protein'));await p.locator('#daily-amount').fill('25');await p.locator('#daily-source').selectOption('isolate');await p.locator('#daily-meal').fill('Breakfast');await p.getByRole('button',{name:'Save record',exact:true}).click();assert.equal(await p.evaluate(()=>S.proteinLog[0].grams),25);await p.evaluate(()=>navigate('wellness'));assert.equal(await p.locator('#daily-date').inputValue(),await p.evaluate(()=>Core.isoDay(Date.now())));await p.getByRole('button',{name:'Repeat last protein entry',exact:true}).click();assert.equal(await p.locator('#daily-amount').inputValue(),'25');await p.getByRole('button',{name:'Save record',exact:true}).click();assert.equal(await p.evaluate(()=>Core.dayTotals(S,Core.isoDay(Date.now())).protein),50);await p.evaluate(()=>dailySettings());await p.locator('#protein-enabled').uncheck();await p.getByRole('button',{name:'Save tracking settings',exact:true}).click();assert.equal(await p.evaluate(()=>S.proteinLog.length),2);assert.equal(await p.getByRole('button',{name:'+ Add protein',exact:true}).count(),0);
await p.evaluate(()=>{dailySettings()});await p.locator('#protein-enabled').check();await p.getByRole('button',{name:'Save tracking settings',exact:true}).click();await p.evaluate(()=>navigate('overview'));await p.screenshot({path:'/tmp/reta17-overview.png',fullPage:true});
await p.evaluate(()=>{editHome();moveHome('weight',-1)});assert.equal(await p.evaluate(()=>cardOrder()[0]),'weight');await p.evaluate(()=>{closeModal();navigate('settings')});await p.locator('#depth-style').uncheck();assert.ok(await p.locator('body').evaluate(e=>!e.classList.contains('depth')));await p.locator('#depth-style').check();
await p.evaluate(()=>navigate('calculator'));await p.getByRole('button',{name:'Reconstitution guide ↗',exact:true}).click();await p.waitForFunction(()=>document.getElementById('reconstitution-guide')?.open);assert.equal(await p.locator('#reconstitution-guide').getAttribute('open'),'');await p.evaluate(()=>{document.querySelectorAll('img').forEach(i=>i.loading='eager')});await p.waitForFunction(()=>[...document.querySelectorAll('.equipment-photo')].every(i=>i.complete&&i.naturalWidth>0));assert.equal(await p.locator('.equipment-photo').count(),4);await p.screenshot({path:'/tmp/reta17-learn.png',fullPage:true});
await p.evaluate(()=>navigate('legal'));assert.match(await p.locator('main').innerText(),/Privacy Policy/);assert.match(await p.locator('main').innerText(),/Terms of Use/);await p.evaluate(()=>navigate('summary'));assert.match(await p.locator('.report-preview').innerText(),/500 mL/);assert.match(await p.locator('.report-preview').innerText(),/Whey isolate/);
await p.evaluate(()=>navigate('wellness'));await p.getByRole('button',{name:'Previous daily date',exact:true}).click();assert.doesNotMatch(await p.locator('main').innerText(),/Invalid Date/);await p.getByRole('button',{name:'Next daily date',exact:true}).click();
await p.evaluate(()=>navigate('insights'));await p.locator('#weight-mode-inline').selectOption('latest');assert.equal(await p.evaluate(()=>selectedWeightRecords().find(r=>new Date(r.at).getDate()===15).values.weight),92);await p.locator('#weight-mode-inline').selectOption('average');assert.equal(await p.evaluate(()=>selectedWeightRecords().find(r=>new Date(r.at).getDate()===15).values.weight),91);
for(const theme of ['light','dark','system','midnight','forest','slate'])for(const color of ['#087e88','#247957','#7858aa','#566474','#44ccff','#96ff40','#ffee44']){await p.evaluate(({theme,color})=>{S.settings.theme=theme;S.settings.color=color;applyTheme();},{theme,color});assert.ok(await p.evaluate(()=>{const s=getComputedStyle(document.body),r=getComputedStyle(document.documentElement),c=r.getPropertyValue('--accent').trim();return Core.contrast(c,s.getPropertyValue('--card').trim())>=4.5&&Core.contrast(c,r.getPropertyValue('--accent-ink').trim())>=4.5;}),theme+' '+color);}
await p.evaluate(()=>{S.settings.theme='midnight';S.settings.color='#44ccff';navigate('settings');$('#toast').classList.remove('show');persist()});await p.screenshot({path:'/tmp/reta17-settings.png',fullPage:true});
// Full backup round trip and rejection without data loss.
await p.evaluate(()=>{window.testBackup=JSON.stringify(S);S.hydration=[];receiveFile('backup',window.testBackup)});assert.equal(await p.evaluate(()=>S.hydration.length),1);const before=await p.evaluate(()=>JSON.stringify(S));await p.evaluate(()=>{const b=JSON.parse(window.testBackup);b.proteinLog[0].grams=-5;receiveFile('backup',JSON.stringify(b))});assert.equal(await p.evaluate(()=>JSON.stringify(S)),before);
for(const v of ['overview','journal','inventory','settings','wellness','learn','legal','summary','insights']){await p.evaluate(v=>navigate(v),v);assert.equal(await p.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false,v+' overflow');}
for(const width of [320,360,412]){await p.setViewportSize({width,height:844});await p.evaluate(()=>navigate('overview'));assert.ok(await p.locator('nav button').evaluateAll(es=>new Set(es.map(e=>e.getBoundingClientRect().top)).size===1));assert.equal(await p.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);}
await p.reload();assert.equal(await p.evaluate(()=>S.proteinLog.length),2);assert.equal(await p.evaluate(()=>S.settings.depth),true);assert.equal(await p.evaluate(()=>cardOrder()[0]),'weight');assert.equal(await p.locator('.legal-notice').count(),0);assert.deepEqual(errors,[]);await browser.close();console.log('1.7 UI checks passed: groups/status/copy/open, journal return, weight link, 3D, hydration/protein logs & undo, optional logging, images, legal, report, backup validation/restore, narrow screens and persistence.');})().catch(e=>{console.error(e);process.exit(1)});
