const {chromium}=require(process.env.CODEX_PRIMARY_RUNTIME_NODE_MODULES+'/playwright');const fs=require('fs'),path=require('path'),assert=require('node:assert/strict');
(async()=>{const browser=await chromium.launch({executablePath:process.env.RETA_CHROME,args:['--no-sandbox']});const p=await browser.newPage({viewport:{width:390,height:844}}),errors=[];p.on('pageerror',e=>errors.push(e.message));p.on('dialog',d=>d.accept());await p.route('http://reta.test/**',async r=>{const n=new URL(r.request().url()).pathname,f=path.join(__dirname,'../app/src/main/assets',n==='/'?'index.html':n);await r.fulfill({body:fs.readFileSync(f),contentType:f.endsWith('.js')?'application/javascript':f.endsWith('.css')?'text/css':f.endsWith('.png')?'image/png':'text/html'});});await p.goto('http://reta.test/');await p.waitForTimeout(400);await p.getByRole('button',{name:'Explore first',exact:true}).click();
await p.evaluate(()=>{S.settings.legalSeen='2026-09-19';S.settings.depth=true;S.profile.sex='female';S.vials=[{id:'a',name:'Reta A',type:'vial',mg:10},{id:'b',name:'Reta B',type:'vial',mg:10},{id:'water',name:'Water',type:'water',volume:10,usedMl:2,mg:0},{id:'pen',name:'Pen',type:'pen',mg:10},{id:'cart',name:'Cartridge',type:'cartridge',mg:10}];S.entries=[{id:'e',at:'2026-09-01T12:00:00Z',mg:8,vial:'a'}];S.measurements=[{id:'w',at:'2026-09-01T10:00:00Z',values:{weight:90}}];persist();navigate('inventory')});
assert.equal(await p.locator('.supply-card>summary .supply-mini').count(),5);assert.equal(await p.locator('#group-water>summary .supply-mini text').textContent(),'BAC');assert.equal(await p.locator('#supply-a>summary .supply-mini text').textContent(),'RET');assert.deepEqual(await p.locator('.supply-group').evaluateAll(es=>es.map(e=>e.id)),['group-vial','group-water','group-pen','group-cartridge']);assert.equal(await p.locator('#supply-a .low-label').innerText(),'Low');assert.equal(await p.locator('#supply-b .low-label').count(),0);assert.equal(await p.locator('#supply-water .low-label').count(),0);assert.match(await p.locator('#group-vial>summary').innerText(),/2 × 10 mg · 12 mg left · 8 mg used/);
await p.evaluate(()=>editVial('a'));assert.equal(await p.getByRole('button',{name:'Save supply',exact:true}).count(),2);assert.equal(await p.getByRole('button',{name:'Remove supply',exact:true}).count(),2);await p.locator('#v-name').fill('Updated vial');await p.getByRole('button',{name:'Save supply',exact:true}).first().click();assert.equal(await p.evaluate(()=>S.vials.find(v=>v.id==='a').name),'Updated vial');
await p.evaluate(()=>arrangeSupplies());await p.waitForTimeout(250);const before=await p.evaluate(()=>supplyOrder()),h=await p.locator('.drag-handle').first().boundingBox(),t=await p.locator('.home-sort-row').nth(2).boundingBox();await p.mouse.move(h.x+24,h.y+28);await p.mouse.down();await p.waitForTimeout(300);await p.mouse.move(t.x+t.width-30,t.y+t.height-8,{steps:10});await p.mouse.up();assert.notDeepEqual(await p.evaluate(()=>supplyOrder()),before);await p.getByRole('button',{name:'Done',exact:true}).click();await p.screenshot({path:'/tmp/reta173-inventory.png',fullPage:true});
await p.evaluate(()=>{navigate('profile');editCircumferences()});assert.match(await p.locator('.body-measure-art').getAttribute('aria-label'),/Female/);await p.locator('#zone-waist').click();assert.equal(await p.evaluate(()=>document.activeElement.id),'circ-waist');await p.locator('#circ-waist').fill('96.5');await p.locator('#circ-neck').focus();assert.ok(await p.locator('#zone-neck').evaluate(e=>e.classList.contains('selected')));await p.locator('#circ-neck').fill('39');await p.screenshot({path:'/tmp/reta173-measures.png'});await p.getByRole('button',{name:'Save measurements',exact:true}).click();assert.equal(await p.evaluate(()=>S.circumferences[0].values.waist),96.5);assert.equal(await p.evaluate(()=>S.circumferences[0].values.neck),39);assert.equal(await p.evaluate(()=>Object.keys(S.circumferences[0].values).length),2);
await p.evaluate(()=>{window.backup173=JSON.stringify(S);S.circumferences=[];receiveFile('backup',window.backup173)});assert.equal(await p.evaluate(()=>S.circumferences.length),1);const stored=await p.evaluate(()=>JSON.stringify(S));await p.evaluate(()=>{const b=JSON.parse(window.backup173);b.circumferences[0].values.waist=-2;receiveFile('backup',JSON.stringify(b));});assert.equal(await p.evaluate(()=>JSON.stringify(S)),stored);
for(const theme of ['light','dark']){await p.evaluate(theme=>{S.settings.theme=theme;navigate('insights')},theme);assert.ok(await p.locator('.graph-surface').evaluateAll(es=>es.length>=2&&es.every(e=>getComputedStyle(e).backgroundImage==='none')));assert.equal(await p.locator('nav').evaluate(e=>getComputedStyle(e).paddingBottom),'8px');}
await p.evaluate(()=>{$('#toast').classList.remove('show')});await p.screenshot({path:'/tmp/reta173-chart.png'});
await p.reload();assert.equal(await p.evaluate(()=>S.circumferences[0].values.waist),96.5);assert.notDeepEqual(await p.evaluate(()=>supplyOrder()),before);assert.equal(await p.evaluate(()=>S.settings.newDesign),undefined);assert.deepEqual(errors,[]);await browser.close();console.log('1.7.3 checks passed: compact summaries, Low threshold/units, default/custom supply order and drag persistence, paired save actions, interactive dated circumferences, backup validation, clean graphs and menu padding.');})().catch(e=>{console.error(e);process.exit(1)});
