const {chromium}=require(process.env.CODEX_PRIMARY_RUNTIME_NODE_MODULES+'/playwright');
const fs=require('fs'),path=require('path'),assert=require('node:assert/strict');
const assets=path.join(__dirname,'../app/src/main/assets');
(async()=>{
const browser=await chromium.launch({executablePath:process.env.RETA_CHROME,args:['--no-sandbox']});
const page=await browser.newPage({viewport:{width:412,height:915}}),errors=[];
page.on('pageerror',e=>{errors.push(e.message);console.error('PAGE ERROR',e.message)});
await page.route('http://reta.test/**',r=>{const n=new URL(r.request().url()).pathname,f=path.join(assets,n==='/'?'index.html':n);return r.fulfill({body:fs.readFileSync(f),contentType:f.endsWith('.js')?'application/javascript':f.endsWith('.css')?'text/css':f.endsWith('.ttf')?'font/ttf':f.endsWith('.png')?'image/png':'text/html'});});
await page.goto('http://reta.test/');await page.waitForTimeout(450);await page.evaluate(()=>{closeModal();S.onboarded=true;S.settings.legalSeen=legalVersion;S.settings.design='new';S.settings.theme='dark';S.profile={name:'Test user',sex:'male',weight:89,target:80,height:173,age:50,activity:1.375,deficit:15,macroMode:'auto'};S.settings.waterTarget=2200;S.settings.waterLogging=true;S.settings.proteinLogging=true;S.vials=[{id:'v',name:'Retatrutide',type:'vial',mg:10,volume:2},{id:'bac',name:'BAC Water',type:'water',volume:10,usedMl:1,multidose:true,openedAt:new Date(Date.now()-26*Core.DAY).toISOString()}];S.entries=[{id:'d1',at:new Date(Date.now()-3*Core.DAY).toISOString(),mg:1,vial:'v'},{id:'d2',at:new Date(Date.now()-Core.DAY).toISOString(),mg:1.5,vial:'v'},{id:'plan',at:new Date(Date.now()+2*Core.DAY).toISOString(),mg:1.5,status:'planned',vial:'v'}];S.measurements=Array.from({length:31},(_,i)=>({id:'m'+i,at:new Date(Date.now()-(30-i)*Core.DAY).toISOString(),source:'Test scale',values:{weight:92-i*.1,fat:33-i*.05,muscle:58,water:49}}));S.hydration=[{id:'h',at:new Date().toISOString(),ml:300}];S.proteinLog=[{id:'p',at:new Date().toISOString(),grams:52,source:'food',meal:'Test meal'}];S.feelings=[{id:'f',at:new Date().toISOString(),values:{Mood:4,Energy:3},note:'Test check-in'}];S.circumferences=[{id:'c',at:new Date().toISOString(),values:{waist:95,bicepsLeft:34},note:''}];persist();navigate('overview');});
const original=await page.evaluate(()=>JSON.stringify([S.entries,S.measurements,S.vials,S.hydration,S.proteinLog,S.feelings,S.circumferences]));
assert.equal(await page.locator('#app>nav>button').count(),5);
assert.deepEqual(await page.locator('#app>nav>button').allTextContents(),['Today','Journal','Progress','Supplies','You']);
const screens=[['overview'],['journal'],...['overview','body','reta','nutrition','activity'].map(t=>['insights',t]),...['inventory','calculator','learn'].map(t=>['inventory',t]),...['goals','health data','connections','settings'].map(t=>['profile',t])];
for(const theme of ['light','dark']){await page.evaluate(t=>S.settings.theme=t,theme);for(const [route,tab]of screens){await page.evaluate(([r,t])=>go20(r,t),[route,tab]);for(const width of [320,412,915]){await page.setViewportSize({width,height:width===915?412:915});await page.waitForTimeout(30);assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1),`overflow ${theme}/${route}/${tab}/${width}`);}await page.setViewportSize({width:412,height:915});await page.screenshot({path:`/tmp/reta20-${theme}-${route}-${tab||'main'}.png`,fullPage:true});}}
assert.equal(await page.evaluate(()=>JSON.stringify([S.entries,S.measurements,S.vials,S.hydration,S.proteinLog,S.feelings,S.circumferences])),original);
console.log('stage: Every Quick');
// Every Quick Add item opens a real form.
await page.evaluate(()=>go20('overview'));
for(const label of ['Log Injection','Weight','Protein / Meal','Water','Check-in','Workout / Activity','Body Measurement','Note']){await page.getByRole('button',{name:'Quick Add',exact:true}).click();await page.getByRole('button',{name:label,exact:true}).click();assert.ok(await page.locator('#modal input,#modal textarea').count()>0,label);await page.evaluate(()=>closeModal());}
console.log('stage: New records');
// New records save, reload, filter, edit, delete and undo with canonical original records untouched.
await page.evaluate(()=>editExtra20('activity'));await page.locator('#extra-title').fill('Resistance training');await page.locator('#extra-minutes').fill('60');await page.locator('#extra-steps').fill('3500');await page.getByRole('button',{name:'Save record',exact:true}).click();
assert.equal(await page.evaluate(()=>extra20('activity').length),1);
await page.evaluate(()=>editExtra20('notes'));await page.locator('#extra-note').fill('Standalone note');await page.getByRole('button',{name:'Save record',exact:true}).click();assert.equal(await page.evaluate(()=>extra20('notes').length),1);
await page.evaluate(()=>{ui20.filter='all';ui20.day='';go20('journal')});assert.equal(await page.locator('.v2-record').count(),40);
await page.evaluate(()=>{ui20.filter='body';render()});assert.equal(await page.locator('.v2-record').count(),32);
await page.evaluate(()=>{ui20.filter='activity';render()});assert.equal(await page.locator('.v2-record').count(),1);
await page.getByRole('button',{name:'Delete Resistance training'}).click();await page.getByRole('button',{name:'Delete',exact:true}).click();assert.equal(await page.evaluate(()=>extra20('activity').length),0);await page.getByRole('button',{name:'Undo',exact:true}).click();assert.equal(await page.evaluate(()=>extra20('activity').length),1);
console.log('stage: Existing injection');
// Existing injection edit/delete/Undo updates inventory through original shared logic.
await page.evaluate(()=>editEntry('d1'));await page.locator('#entry-mg').fill('2');await page.getByRole('button',{name:/Save entry/}).first().click();assert.equal(await page.evaluate(()=>stock(S.vials[0]).remaining),6.5);
await page.evaluate(()=>confirmRecord18('dose','d1'));await page.getByRole('button',{name:'Delete',exact:true}).click();assert.equal(await page.evaluate(()=>stock(S.vials[0]).remaining),8.5);await page.evaluate(()=>undoLast());assert.equal(await page.evaluate(()=>stock(S.vials[0]).remaining),6.5);
console.log('stage: Chart state');
// Equipment remains separate from drug stock, supports Undo; calculator reuses original formula.
await page.evaluate(()=>{go20('inventory','inventory');editEquipment20();});await page.locator('#eq-name').fill('31G test needles');await page.locator('#eq-quantity').fill('10');await page.getByRole('button',{name:'Save equipment'}).click();await page.getByRole('button',{name:'Use one',exact:true}).click();assert.equal(await page.evaluate(()=>extra20('equipment')[0].quantity),9);await page.evaluate(()=>undoLast());assert.equal(await page.evaluate(()=>extra20('equipment')[0].quantity),10);assert.equal(await page.evaluate(()=>stock(S.vials[0]).remaining),6.5);
await page.evaluate(()=>go20('inventory','calculator'));await page.locator('#cm').fill('10');await page.locator('#cv').fill('2');await page.locator('#cd').fill('1');await page.getByRole('button',{name:'Calculate volume →'}).click();assert.match(await page.locator('#calc-result').innerText(),/0.2/);await page.locator('#unit-scale20').selectOption('100');assert.match(await page.locator('#units-result20').innerText(),/^20 marked units/);await page.locator('#custom-capacity20').fill('2');await page.getByRole('button',{name:'Apply capacity'}).click();assert.equal(await page.locator('#capacity').inputValue(),'2');
// Native import bridges retain preview and explicit commit, and same source does not duplicate.
await page.evaluate(()=>{receiveHealth({rows:[{id:'hc1',at:new Date(Date.now()-2*Core.DAY).toISOString(),values:{weight:90},source:'Health Connect',externalId:'hc-test-1'}],warnings:[]});});assert.equal(await page.getByRole('dialog',{name:'Review body data'}).count(),1);await page.getByRole('button',{name:'Import / apply selected changes'}).click();const count=await page.evaluate(()=>S.measurements.length);await page.evaluate(()=>{receiveHealth({rows:[{id:'hc2',at:S.measurements.find(r=>r.externalId==='hc-test-1').at,values:{weight:90},source:'Health Connect',externalId:'hc-test-1'}],warnings:[]});});await page.getByRole('button',{name:'Import / apply selected changes'}).click();assert.equal(await page.evaluate(()=>S.measurements.length),count);
// Backup keeps extension and all original data through actual restore and confirmation.
const backup=await page.evaluate(()=>JSON.stringify(S));page.once('dialog',d=>d.accept());await page.evaluate(raw=>receiveFile('backup',raw),backup);assert.equal(await page.evaluate(()=>JSON.stringify(S)),backup);
// Chart state survives rerender, fullscreen and tab/back.
await page.evaluate(()=>go20('insights','reta'));await page.evaluate(()=>{chartRange(14);toggleSeries18('weight');});const chartState=await page.evaluate(()=>[chart.start,chart.end,$('#layer-weight').checked]);await page.evaluate(()=>{render();toggleFull();toggleFull();});assert.deepEqual(await page.evaluate(()=>[chart.start,chart.end,$('#layer-weight').checked]),chartState);
await page.evaluate(()=>{tab20('progress','body');goBack();});assert.deepEqual(await page.evaluate(()=>[chart.start,chart.end,$('#layer-weight').checked]),chartState);
console.log('stage: All hidden');
// All hidden series shows empty-state; reenabling recovers.
await page.evaluate(()=>{document.querySelectorAll('[id^="layer-"]').forEach(e=>e.checked=false);chart.draw()});assert.match(await page.locator('#chart-value').innerText(),/Select a series/);await page.evaluate(()=>{toggleSeries18('model');render()});assert.equal(await page.locator('#layer-model').isChecked(),true);
await page.evaluate(()=>go20('profile','settings'));await page.locator('#new-design').uncheck();assert.equal(await page.locator('body.new-design').count(),0);await page.evaluate(()=>navigate('settings'));await page.locator('#new-design').check();await page.reload();await page.waitForTimeout(100);assert.equal(await page.evaluate(()=>S.settings.design),'new');assert.equal(await page.evaluate(()=>extra20('activity').length),1);assert.equal(await page.evaluate(()=>extra20('notes').length),1);
assert.deepEqual(errors,[]);await browser.close();console.log('V2 passed: 14 views × 2 themes × 3 widths; Quick Add forms, unified timeline, new records, injection stock, Undo, chart state, reversible design and reload.');
})().catch(e=>{console.error(e);process.exit(1)});
