const {chromium}=require(process.env.CODEX_PRIMARY_RUNTIME_NODE_MODULES+'/playwright');
const fs=require('fs'),path=require('path'),assert=require('node:assert/strict');
const assets=path.join(__dirname,'../app/src/main/assets');
(async()=>{
const browser=await chromium.launch({executablePath:process.env.RETA_CHROME,args:['--no-sandbox']});
const page=await browser.newPage({viewport:{width:412,height:915}}),errors=[];
page.on('pageerror',e=>{errors.push(e.message);console.error('PAGE ERROR',e.message)});
await page.route('http://reta.test/**',r=>{const n=new URL(r.request().url()).pathname,f=path.join(assets,n==='/'?'index.html':n);return r.fulfill({body:fs.readFileSync(f),contentType:f.endsWith('.js')?'application/javascript':f.endsWith('.css')?'text/css':f.endsWith('.ttf')?'font/ttf':f.endsWith('.png')?'image/png':'text/html'});});
await page.goto('http://reta.test/');await page.waitForTimeout(450);await page.evaluate(()=>{closeModal();S.onboarded=true;S.settings.legalSeen=legalVersion;S.settings.design='new';S.settings.theme='dark';S.profile={name:'Test user',sex:'male',weight:89,target:80,height:173,age:50,activity:1.375,deficit:15,macroMode:'auto'};S.settings.waterTarget=2200;S.settings.waterLogging=true;S.settings.proteinLogging=true;S.vials=[{id:'v',name:'Retatrutide',type:'vial',mg:10,volume:2},{id:'bac',name:'BAC Water',type:'water',volume:10,usedMl:1,multidose:true,openedAt:new Date(Date.now()-26*Core.DAY).toISOString()}];S.entries=[{id:'d1',at:new Date(Date.now()-3*Core.DAY).toISOString(),mg:1,vial:'v'},{id:'d2',at:new Date(Date.now()-Core.DAY).toISOString(),mg:1.5,vial:'v'},{id:'plan',at:new Date(Date.now()+2*Core.DAY).toISOString(),mg:1.5,status:'planned',vial:'v'}];S.measurements=Array.from({length:31},(_,i)=>({id:'m'+i,at:new Date(Date.now()-(30-i)*Core.DAY).toISOString(),source:'Test scale',values:{weight:92-i*.1,fat:33-i*.05,muscle:58,water:49}}));S.hydration=[{id:'h',at:new Date().toISOString(),ml:300}];S.proteinLog=[{id:'p',at:new Date().toISOString(),grams:52,source:'food',meal:'Test meal'}];S.feelings=[{id:'f',at:new Date().toISOString(),values:{Mood:4,Energy:3},note:'Test check-in'}];S.circumferences=[{id:'c',at:new Date().toISOString(),values:{waist:95,bicepsLeft:34},note:''}];persist();navigate('overview');});

await page.evaluate(()=>go20('inventory','calculator'));await page.locator('#cm').fill('10');await page.evaluate(()=>refreshExpiry18());assert.equal(await page.locator('#cm').inputValue(),'10','BAC refresh must not clear calculator input');
await page.evaluate(()=>{ui20.day=Core.isoDay(Date.now()-3*Core.DAY);go20('journal');quickAdd20();});await page.getByRole('button',{name:'Weight',exact:true}).click();assert.equal((await page.locator('#measure-at').inputValue()).slice(0,10),await page.evaluate(()=>ui20.day));await page.evaluate(()=>closeModal());
await page.evaluate(()=>{go20('profile','settings');const before=document.querySelector('main');window.nativeEvent('lock','Test callback');if(before===document.querySelector('main'))throw Error('Lock callback did not refresh You settings');});
// Font enlargement is a browser layout proxy, not a native font-scale certification.
await page.evaluate(()=>{document.body.style.zoom='1.3';});for(const r of ['overview','journal','profile','inventory']){await page.evaluate(r=>go20(r),r);assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1),'large text overflow '+r);}await page.evaluate(()=>document.body.style.zoom='');
// Empty store across all destinations; no invented numeric body values.
await page.evaluate(()=>{S=defaults();Core.migrate18(S);S.settings.design='new';S.onboarded=true;S.settings.legalSeen=legalVersion;rendered20='';chart=null;weightChart=null;});
for(const [r,t]of [['overview'],['journal'],['insights','overview'],['insights','body'],['insights','reta'],['insights','nutrition'],['insights','activity'],['inventory','inventory'],['inventory','calculator'],['inventory','learn'],['profile','goals'],['profile','health data'],['profile','connections'],['profile','settings']]){await page.evaluate(([r,t])=>go20(r,t),[r,t]);}
assert.deepEqual(errors,[]);await browser.close();console.log('V2 edge checks: pending calculator input survives expiry refresh, selected-day entry, enlarged layout, all empty views.');
})().catch(e=>{console.error(e);process.exit(1)});
